### ISSUE TITLE
Add diagnostic:  thetao  & thetaoga

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#101]
Add the 'thetao' diagnostic, in z-coordinates.  In addition, the global average field "thetaoga" needs to be implemented.

(@adcroft-gfdl may have already completed this.  If so, please close this issue.)

**Comment by StephenGriffies** [comment]
thetao diagnostic has been added to CMOR name for id_T in MOM.F90 with this commit

2fcecebc6087e7842f34dbffc6ada9104e0300a4

**Comment by StephenGriffies** [comment]
Both thetao and thetoga are available in MOM6.  Issue is now complete.
