### ISSUE TITLE
id check on 0. rather than 0

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#1016]
https://github.com/NOAA-GFDL/MOM6/blob/ceaca560c975fe32cc463041e1549ca6c69da813/src/ALE/MOM_ALE.F90#L807

Tr%id_remap_cont>0.  

should be 

Tr%id_remap_cont>0

That is, there is an extra decimal after the  0 in the check for diagnostic id.

**Comment by marshallward** [comment]
Thanks Steve, I will fix this.

In the future we should look into a compiler warning which flags integer-vs-real inequalities but ignores real-vs-real.

**Comment by marshallward** [comment]
This has been fixed.
