### ISSUE TITLE
flux_units should be conv_units for diagnostic of remapping on heat

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#1017]
https://github.com/NOAA-GFDL/MOM6/blob/ceaca560c975fe32cc463041e1549ca6c69da813/src/tracer/MOM_tracer_registry.F90#L547-L556

This block of code registers the diagnostic for the remapping tendency acting on heat content. It does so for the 3d tendency as well as the 2d depth integrated tendency.

The "flux_units" in the registry should instead be "conv_units", since all other heat content tendencies are in W m-2 rather than W. 

Can @ashao please examine to be sure I am correct?

**Comment by Hallberg-NOAA** [comment]
I agree with @StephenGriffies that the units for these two entries should be changed from flux_units to conv_units.

**Comment by StephenGriffies** [comment]
Thanks for pushing this forward @Hallberg-NOAA
