### ISSUE TITLE
Add diagnostic:  rhopoto

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#104]
Add the "rhopoto" diagnostic, where:

cmor_field_name='rhopoto', cmor_long_name='Sea Water Potential
Density', cmor_units='kg m-3', cmor_standard_name='sea_water_potential_density'

CMIP has requested this field be referenced to the surface.  @adcroft-gfdl asked if providing N^2 would be preferred over rhopoto.

**Comment by StephenGriffies** [comment]
CMIP6 now requests buoyancy frequency rather than potential density.  Nonetheless, it would be useful for some applications to have a potential density diagnostic.  So this issue should remain open.

**Comment by Hallberg-NOAA** [comment]
This diagnostic was added on April 6, 2016, as a part of https://github.com/NOAA-GFDL/MOM6/commit/5bd8ac054cf2a547544bd5eb5ebc67cd4566fd88 .
