### ISSUE TITLE
Requirements for running .testing suite on gaea

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MOM6#1043]
@marshallward 
It is necessary to include a directive (or directives) to correctly configure the environment to run the test suite in the .testing folder on gaea. The fre-generated build scripts do this via the following command:

```
source env.cshrc
```
where env.cshrc contains:
```
setenv MAKEFLAGS --jobs=16

source /opt/modules/default/init/tcsh

# Platform environment defaults from /ncrc/home2/fms/local/opt/fre-commands/bronx-16/site/ncrc4/env.defaults.gnu
module unload cray-netcdf cray-hdf5 fre
module unload PrgEnv-pgi PrgEnv-intel PrgEnv-gnu PrgEnv-cray
module load PrgEnv-gnu/6.0.3
module swap gcc gcc/7.2.0
module load fre/bronx-16
module load cray-hdf5/1.8.16
module load git

setenv KMP_STACKSIZE 512m
setenv NC_BLKSZ 1M
setenv F_UFMTENDIAN big
# MAIN_PROGRAM env is needed by the GNU compiler
setenv MAIN_PROGRAM coupler/coupler_main.o

# Platform environment overrides from XML

limit stacksize unlimited
```
It would be easiest to include something similar to `env.cshrc` file in the .testing directory that a build script can source prior to running make, or that can be triggered from within the makefile.

**Comment by marshallward** [comment]
The Makefile currently source a file `config.mk` inside `.testing` which is primarily for platform-specific configurations like this.  For example, I have `MPIRUN=srun` in mine for Gaea.  Would this work?

**Comment by wrongkindofdoctor** [comment]
I have also set MPIRUN=srun in my Makefile copy, and had to change `-npes` to `--ntasks`, and placels the `--ntasks=#` option immediately after MPIRUN_CMD  in the lines with the run command.The gaea environment still requires the magic combo of module files shown in the env.cshrc file to be loaded to link in netCDF, mpich, etc... Perhaps noting this in the .testing readme file would suffice for gaea users, since the testing suite is meant for a broad user base.

It would also help to remind users to run `git submodule init` and `git submodule update` before running the tests, since some of them require the CVMix modules in the pkg directory. 

Finally, I had to add the lines:
```
$(BASE)/pkg/CVMix-src/src/*F90 \
$(BASE)/pkg/CVMix-src/drivers/*F90 \
$(BASE)/pkg/CVMix-src/shared/*F90
```
 to the `SOURCE` definition.

**Comment by marshallward** [comment]
The makefile just uses `-n`, not `-npes`, right?   Did you need to replace `-n` in this case?

Also, have you added tests with more parallelization?  That could be why it needs different flags.

BTW if we do need to work out an MPI-specific PE flag: There is an autoconf-like test used to figure out the environment variable config flags, which could be adapted to also determine the MPI rank flag.

I'm not sure why CVMix is not being picked up, I'm not seeing this error.  I'll try to come by if I get a chance.

**Comment by wrongkindofdoctor** [comment]
Yes, I meant `-n`, not `npes`; I followed the style of the run command in the fre-generated runscript, but -n may suffice for these single-core tests.
I haven't added any other tests.
