### ISSUE TITLE
Rewrite the register tracer diagnostic interface

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#105]
Interface needs to be generalized and must support adding additional attributes:

cmor_field_name
cmor_long_name
cmor_units
cmor_standard_name

**Comment by Hallberg-NOAA** [comment]
These interfaces were implemented in January, 2018, and merged into the dev/gfdl branch of MOM6 on https://github.com/NOAA-GFDL/MOM6/pull/689.
