### ISSUE TITLE
Can't open module file ‘cvmix_convection.mod’ 

### ISSUE THREAD

**Issue by yeyuejin** [NOAA-GFDL/MOM6#1079]
when I compile MOM6 ocean-only module , it generate an error ---- Can't open module file ‘cvmix_convection.mod’ . but I still cat not find corresponding file even I search all files beneath MOM6. what should I do ?

**Comment by marshallward** [comment]
Did you do a recursive checkout?
```
git clone --recursive https://github.com/NOAA-GFDL/MOM6-examples.git MOM6-examples
```
CVMix is a submodule in the MOM6 repository.

There is more information here if you have not yet seen it:
https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started

**Comment by yeyuejin** [comment]
> Did you do a recursive checkout?
> 
> ```
> git clone --recursive https://github.com/NOAA-GFDL/MOM6-examples.git MOM6-examples
> ```
> 
> CVMix is a submodule in the MOM6 repository.
> 
> There is more information here if you have not yet seen it:
> https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started

thank you very mach! I try to git all codes using git-instruction again, obviously, I got.

**Comment by marshallward** [comment]
Seems to be resolved so I'm closing this.  Feel free to re-open if you need to though.
