### ISSUE TITLE
Name of bathymetry file

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#1117]
Searching on topog in the inputs gives:
```
MOM_input:TOPO_FILE = "ocean_topog.nc"    ! default = "topog.nc"
input.nml: &topography_nml
input.nml:            topog_file = 'INPUT/navy_topography.data.nc'
```
and yet my job failed with:
```
FATAL from PE    44:  initialize_topography_from_file: Unable to open INPUT/topog.nc
```
Making a symlink between INPUT/ocean_topo.nc and INPUT/topog.nc makes things work.

**Comment by marshallward** [comment]
Hi Kate, can you check if `MOM_parameter_doc.all` is also setting `TOPO_FILE` to `ocean_topog.nc`?

**Comment by kshedstrom** [comment]
Yes, it is.

**Comment by MJHarrison-GFDL** [comment]
Kate,

Check SIS parameters

**Comment by kshedstrom** [comment]
Yes, that's it: TOPO_FILE = "topog.nc"          ! default = "topog.nc"
