### ISSUE TITLE
Divide by zero in OBC reservoirs

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#1121]
At say L#4780 in MOM_open_boundaries.F90, there is a divide by h. This fails in debug mode inside the land mask where h is zero.

**Comment by MJHarrison-GFDL** [comment]
The persistent h=0 problem. Is there a way to fix this without making the code slower?

**Comment by Hallberg-NOAA** [comment]
In other parts of the code, we do not divide by h, but instead we divide (h + GV%H_subroundoff). H_subroundoff is so small that if h is anything that is not physically insignificant, it is at least 17 orders of magnitude than h, so, at roundoff for 64-bit IEEE reals, (h + GV%H_subroundoff) = h, but when h is 0, (h + GV%H_subroundoff) = GV%H_subroundoff.  There does not seem to be a noticeable slowdown in the code from this change. However, the proposed changes in PR#1122 seem like they would work too.

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by https://github.com/NOAA-GFDL/MOM6/pull/1122.
