### ISSUE TITLE
Bad link in diag_table documentation

### ISSUE THREAD

**Issue by mnlevy1981** [NOAA-GFDL/MOM6#1131]
There's a link from [the diagnostics page](https://mom6.readthedocs.io/en/dev-gfdl/api/generated/pages/Diagnostics.html#the-diag-table) of the documentation to http://data1.gfdl.noaa.gov/~nnz/MOM/mom5_pubrel_August2012/src/shared/diag_manager/diag_table.html but the latter no longer exists:

> The requested URL /~nnz/MOM/mom5_pubrel_August2012/src/shared/diag_manager/diag_table.html was not found on this server

**Comment by adcroft** [comment]
It's referring to a MOM5 link. I don't know what it was but this looks like the most recent MOM5 docs: https://mom-ocean.github.io/docs/userguide/#the-diagnostics-table  Comparing what we have on the MOM6 RTD page that links to MOM5, I'd say the MOM6 one is more complete. I have no recollection of what the old link had in it.

**Comment by marshallward** [comment]
I agree with @adcroft, let's just remove the link?

**Comment by StephenGriffies** [comment]
Yes, remove the link.

**Comment by marshallward** [comment]
Removed in this PR: https://github.com/NOAA-GFDL/MOM6/pull/1132
