### ISSUE TITLE
Add diagnostic:  water flux into sea water

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#115]
Add the total water flux into sea water diagnostic.  This is the net mass flux going into the ocean, i.e. the sum from all contributions.

**Comment by StephenGriffies** [comment]
This diagnostic is available via the CMOR field "wfo".  I do not recall when this diagnostic was added.  But it works, and is now enabled in the OM4 test case diag_table.MOM6.
