### ISSUE TITLE
Current xmls will not load all required git submodules

### ISSUE THREAD

**Issue by GFDL-Eric** [NOAA-GFDL/MOM6#1151]
Hi MOM team,

We've had a couple issues come up in the helpdesk regarding xmls (specifically for AM4, ESM4) that do not compile. When requesting older versions of MOM6 (e.g. xanadu), two of the requisite submodules do not properly load. I believe I have traced this to the way in which MOM6 is obtained in these xmls. Here is the appropriate csh block:
```
  git clone -b $(MOM6_GIT_TAG) https://github.com/NOAA-GFDL/MOM6-examples.git mom6
  pushd mom6
  git checkout $(MOM6_GIT_TAG)  #needed for older git on zeus
  git submodule init src/MOM6 src/SIS2 src/icebergs tools/python/MIDAS
  git clone --recursive https://github.com/NOAA-GFDL/MOM6.git src/MOM6
  git clone             https://github.com/NOAA-GFDL/SIS2.git src/SIS2
  git clone             https://github.com/NOAA-GFDL/icebergs.git src/icebergs
  git submodule update #This gets the right version of submodules
```
The `git clone --recursive` line obtains the latest commit from the default branch of MOM6, which I believe is the dev/gfdl branch. In the latest commit, however, two submodules that had previously been included (data assimilation and geokdtree) are no longer there, indeed they have been moved to config_src/external. However, requesting an older version of MOM6 (via the MOM6_GIT_TAG parameter) doesn't pull these submodules either, nor does the older version have access to config_src/external, and errors result. I have devised a workaround, which is functional but has a somewhat major caveat: change the `git submodule update` line to `git submodule update --recursive`. This will get all of the submodules that exist for the requested version of MOM6, but it relies on the **latest** commit in dev/gfdl having **at least** one submodule, otherwise no submodules will be pulled and errors will again result. A more robust solution that does not contain this dependence might be necessary if there are ever plans to remove all of the submodules from MOM6 in the future.

**Comment by adcroft** [comment]
We are not removing all submodules: the two in pkg/ will remain so that should solve your future-proofing question. I agree that adding `--recursive` to the submodule update would be a good thing but it seems that cloning the default branches and then updating the submodules is the source of the missing directories. I believe making the original clone recursive would solve the problem but that clones much much more than is needed. i.e.
```csh
git clone --recursive -b $(MOM6_GIT_TAG) https://github.com/NOAA-GFDL/MOM6-examples.git mom6
```
get everything you want but also a whole lot more which I think is why @nikizadehgfdl does it the longer way. I tried
```csh
git clone -b $(MOM6_GIT_TAG) https://github.com/NOAA-GFDL/MOM6-examples.git mom6
pushd mom6
git submodule init src/MOM6 src/SIS2 src/icebergs
git submodule update --recursive src/MOM6 src/SIS2 src/icebergs
```
thinking it would be cleaner but that last `--recursive` doesn't seem to propagate down. Not sure why. However, this even more succinct block
```csh
git clone -b $(MOM6_GIT_TAG) https://github.com/NOAA-GFDL/MOM6-examples.git mom6
pushd mom6
git submodule update --recursive --init src/MOM6 src/SIS2 src/icebergs
```
does exactly what you want.

**Comment by adcroft** [comment]
BTW, I realized why `git submodule update --recursive src/MOM6 src/SIS2 src/icebergs` is insufficient. `git submodule update` assumes all submodules have already been initialized. That was probably obvious to you given your OP description.

**Comment by GFDL-Eric** [comment]
Indeed, I find your 3 line solution to work splendidly. Unless there's a specific reason to want the latest commit from the default branch as a part of the process, I'd suggest xmls be updated with this new approach.

**Comment by adcroft** [comment]
Assuming you're happy, can we close this issue now?

**Comment by GFDL-Eric** [comment]
Of course, thanks!
