### ISSUE TITLE
Add diagnostic:  salt flux into sea water

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#116]
This is the downward sea ice basal sea water flux, positive or negative.  Salt flux is in the coupler and available for diagnostic use.

**Comment by Hallberg-NOAA** [comment]
@jkrasting what is the CMOR name of the variable you are asking for?

**Comment by jkrasting** [comment]
I believe we addressed this in preparing the data request for CMIP6.
