### ISSUE TITLE
inconsistent array copies in MOM_wave_structure

### ISSUE THREAD

**Issue by raphaeldussin** [NOAA-GFDL/MOM6#1182]
@Hallberg-NOAA I know you're looking at this rn but just wanted to point out this problem:

when layers are merged, this becomes incorrect:

https://github.com/NOAA-GFDL/MOM6/blob/dd75807adddb749aecee20cf6a992904269b5900/src/diagnostics/MOM_wave_structure.F90#L488

also similar issues on line 521 and below.
I can submit a PR unless it would interfere with your rewriting

**Comment by Hallberg-NOAA** [comment]
@raphaeldussin, I need to put my work on MOM_wave_structure.F90 on hold for the next few weeks, so if you are working on MOM_wave_structure.F90 and are able to identify and correct any bugs, please do not hesitate to fix them and put in a PR. To the best of my knowledge, there is very limited testing of the MOM_wave_structure.F90 code, so if along the way you identify a good test case to add this to, that would also be appreciated.
