### ISSUE TITLE
Add vertical SGS transformations as diagnostics

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#121]
Add vertical SGS transformations as diagnostics.  These are found in Table 2.10.

**Comment by Hallberg-NOAA** [comment]
@jkrasting, could you please provide the names of any CMOR variables that are still missing from MOM6?

**Comment by jkrasting** [comment]
> @jkrasting, could you please provide the names of any CMOR variables that are still missing from MOM6?

We are OK now.
