### ISSUE TITLE
The MOM6 available_diags files have become excessively large

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#1224]
The available_diags files document all of the available diagnostics, and they are intended to facilitate the identification of diagnostics that a user might wish to save with a particular configuration, and to prevent the addition of duplicative diagnostics. However, because MOM6 now generates a large number of diagnostics that are derived from the original diagnostic, such as spatial averages or diagnostics on alternate vertical grids, the number of entries in these files is many times larger than the number of root diagnostics.

  For example, the MOM6 available_diags file for the OM4_025 test case is 644Kb, and has 3651 entries, running for 14,953 lines.   Because this case uses two possible horizontal grids, 3 vertical coordinates for diagnostics, and spatially averaged versions of many diagnostics, there 12 entries for many diagnostics.  With plans for even greater flexibility in diagnostics, this inflation factor could grow much larger in the future.

  To remedy this file-size bloat and to make these available_diags files useful once again for selecting diagnostics, I am proposing that we add a run-time option to indicate that only the primary diagnostic should be logged in this file, perhaps with an additional entry in this file indicating the alternative vertical coordinates, horizontal grids, or other automatically derived variants (e.g., spatial averages) are available for each diagnostic.

**Comment by StephenGriffies** [comment]
Sounds like a very good idea @Hallberg-NOAA .
