### ISSUE TITLE
Add the following fields to the diag_tables for relevant examples

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#124]
The following variables need to be incorporated to the diag_tables for all relevant examples:

tos
tosga
tossq
sos
sosga
mlotst
omlmax   -- still requires post-processing
omldamax -- still requires post-processing
UHBT
VHBT

**Comment by StephenGriffies** [comment]
A/  tos, tosga, tossq, sos, sosga, mlotst are available in OM4_025 diag table.  

B/ omlmax and omldamax are no longer requested for CMIP6.

**Comment by Hallberg-NOAA** [comment]
There are no diag_tables in the MOM6 code directories or anywhere else in MOM6 git repository. This issue may still be relevant for some of the test cases or for specific configurations, but it should be added in those places instead. As a MOM6 issue, this should be closed.
