### ISSUE TITLE
Use of deferred length characters in MOM6 (discussion)

### ISSUE THREAD

**Issue by alperaltuntas** [NOAA-GFDL/MOM6#1254]
We occasionally hit large character length limits (even when the lengths are on the order of 1000) and solve the issue by simply increasing the lengths of those characters, e.g, from len=1024 to len=2048, etc. This recently happened when we (NCAR) ran with large number of vertical layers. (See https://github.com/NCAR/MOM6/pull/165)

This time, we implemented a different solution, which we think is more sustainable and results in cleaner character operations: Instead of increasing the character lengths, we converted the character variables with hardcoded lengths to character variables with deferred lengths. The advantage of deferred-length characters is that their lengths are dynamic, and thus, are not subject to overflow issues.

The purpose of this issue (discussion) post is, thus:
(1) to get approval of others on the use of deferred-length characters. (It has never been used in MOM6)
(2) to advertise this solution for future issues of character length overflows.

**Comment by marshallward** [comment]
[My comments](https://github.com/NCAR/MOM6/pull/165#issuecomment-731769466), repeated below:

> I suspect it is no problem, it's a simple patch, the allocatable is better than fixed-size, and there's no real benefit to write() vs assignment for pure string manipulation.
> 
> There might be some objection to the implicit allocation, which I think is an f03 construct, and it has generally been discouraged, but I am generally in favor of them. At worst, this may only require an explicit allocate() statement.
> 

While I wouldn't want to lose much time over this, I think it's worth a short discussion on Monday about how to handle this or future implicit allocations.  (Emphasis on *short*, btw!)

**Comment by marshallward** [comment]
We talked this over and agreed that it's time to start phasing out these fixed-width strings and start handling them a little more efficiently.  [Your proposal](https://github.com/NCAR/MOM6/pull/165) is certainly a good one, and we think you should go ahead with it, and we can cherry-pick it into the GFDL fork after it's merged.

A grep search found 1051 instances of fixed-width strings across `src` and `config_src`, with over 410 being at least 100 characters, so it would be good to get a plan together and decide how to tackle them.

I'll have a look myself and see what might be done here, and let's stay in touch about your own plans.

**Comment by alperaltuntas** [comment]
Great! We merged the PR to dev/ncar. I guess you can close this issue now unless you'd like to continue the discussion on future plans here.

**Comment by marshallward** [comment]
No problems, I can close this, but let's stay in touch about this and similar issues.
