### ISSUE TITLE
typo in cfc index check

### ISSUE THREAD

**Issue by klindsay28** [NOAA-GFDL/MOM6#1273]
In the line of code
https://github.com/NOAA-GFDL/MOM6/blob/446becc0ec83541ce7c469a7d907d6b382433bae/src/tracer/MOM_OCMIP2_CFC.F90#L129
the value of `ind_cfc_11_flux` is being checked twice. It seems likely to me that the one of the conditionals should be checking `ind_cfc_12_flux`.

**Comment by Hallberg-NOAA** [comment]
This is a good catch, @klindsay28. Is there any chance you would be interested in putting in a pull request to either the dev/ncar or dev/gfdl branches of MOM6 that fixes this problem?
