### ISSUE TITLE
KPP_OBLdepth becomes too small ~ 1 cm

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#132]
commit 4a0c1b2a7d16a085e76f2877f4ebb0632b8d840c
Author: Robert Hallberg Robert.Hallberg@noaa.gov
Date:   Wed Mar 18 18:18:49 2015 -0400

 Investigating a testcase  crash I found that the diagnostic called
KPP_OBLdepth becomes too low (1.2cm) at some points on the map. Alistair says this should never happen.    

More about the test:
I ran an experiment to test the capability for DT_THERM = 2\* dt_cpld and the model crashed on the 3rd day with SST suddenly hiking up to 30C at an isolated point in high latitudes [(-5E,82N) (Greenland Sea)](https://www.google.com/maps/place/82%C2%B027'50.4%22N+4%C2%B055'08.8%22E/@78.9510417,4.9191,4z/data=!4m2!3m1!1s0x0:0x0) . Looking for the reasons I noticed KPP_OBLdepth becomes suspiciously low (1.2cm) at the same point. Thinking (mistakenly) that this would be the depth of the grid box that would accept the heat fluxes and heat up, I set KPP%MINIMUM_OBL_DEPTH = 10.0 and the test ran for at least a month. 

The history file is too large to transfer to gfdl (since it's every timestep) but here it is on gaea:

/lustre/f1/unswept/Niki.Zadeh/archive/safe/KPP_OBL_DEPTH_going_1cm/19000101.ocean_month.nc

**Comment by Hallberg-NOAA** [comment]
If this is still a problem, it should be raised via NCAR.
