### ISSUE TITLE
Missing line to reset vbt with vel_underflow in the barotropic solver?

### ISSUE THREAD

**Issue by herrwang0** [NOAA-GFDL/MOM6#1336]
It looks like a line is missing before line 1908
https://github.com/NOAA-GFDL/MOM6/blob/45b336670988773c050e3d59e3bd0ebe7b948ecb/src/core/MOM_barotropic.F90#L1906-L1910

`[uv]bt` is reset to zero when its abs() is smaller than `CS%vel_underflow`  in the other three places, for instance, https://github.com/NOAA-GFDL/MOM6/blob/45b336670988773c050e3d59e3bd0ebe7b948ecb/src/core/MOM_barotropic.F90#L2045-L2050

but not in the segment above.

**Comment by marshallward** [comment]
Good spotting, looks like a straightforward fix, unless I'm missing something.

Our rotation tests might have caught this - if we had been testing this feature... :neutral_face:

**Comment by herrwang0** [comment]
Looks like so. `VEL_UNDERFLOW` is either 0.0 or 1e-30 in MOM-examples runs, so I guess not likely it will change previous results. 
I will make PR to patch this then.
