### ISSUE TITLE
read_attribute() doesn't behave quite the same as code it replaced in MOM_tracer_Z_init

### ISSUE THREAD

**Issue by mnlevy1981** [NOAA-GFDL/MOM6#1375]
I'm finally merging some recent commits to a branch where I'm introducing a new tracer module, and am having problems with this change in `src/tracer/MOM_tracer_Z_init.F90:read_Z_edges()` from [`44a8bde`](https://github.com/NOAA-GFDL/MOM6/commit/44a8bde1c4ddcd1cdfbabcfe3c932a6cc966b791#diff-925d91e0eeb0a776c258e755e51f18de30ca3f6a2a360cc4b9f9dcf3a9eb2e4dR418)

```diff
-  status = NF90_GET_ATT(ncid, layid, "edges", edge_name)
-  if (status /= NF90_NOERR) then
-    call MOM_mesg(mdl//" "//trim(dim_msg)//&
-         " has no readable edges attribute - "//trim(NF90_STRERROR(status)))
-    has_edges = .false.
-  else
-    has_edges = .true.
-    status = NF90_INQ_VARID(ncid, edge_name, intid)
-    if (status /= NF90_NOERR) then
-      call MOM_error(WARNING,mdl//" Difficulties finding edge variable "//&
-          trim(edge_name)//" in "//trim(filename)//" - "//trim(NF90_STRERROR(status)))
-      has_edges = .false.
-    endif
-  endif
+  call read_attribute(filename, "edges", edge_name, varname=dim_names(3), found=has_edges)
```

My initial condition file does not have an `edges` attribute for `DEPTH`, and it is triggering the `Attribute data type is not a char` error from [`src/framework/MOM_io.F90:read_attribute_str()`](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/framework/MOM_io.F90#L912) Since I'm passing in the optional `found` argument, I would expect it to return `.false.` rather than abort.

It's late (and Friday, at least in this time zone) so I'm not going to propose a fix right now... I'll probably come back to this mid-week, but won't be offended if somebody beats me to a patch.

**Comment by mnlevy1981** [comment]
I was able to get past this error with the following changes (note that I'm ignoring whitespace changes in this diff):

```diff
diff --git a/src/framework/MOM_io.F90 b/src/framework/MOM_io.F90
index 1159ac87e..34f872e6c 100644
--- a/src/framework/MOM_io.F90
+++ b/src/framework/MOM_io.F90
@@ -792,6 +792,7 @@ subroutine read_attribute_str(filename, attname, att_val, varname, found, all_re
     endif
     if ((varid > 0) .or. (varid == NF90_GLOBAL)) then ! The named variable does exist, and found would be true.
       rc = NF90_inquire_attribute(ncid, varid, attname, xtype=att_type, len=att_len)
+      if ((.not. present(found)) .or. (rc /= NF90_ENOTATT)) then
         if ((rc /= NF90_NOERR) .and. (rc /= NF90_ENOTATT)) &
           call MOM_error(FATAL, trim(hdr) // trim(NF90_STRERROR(rc)) //" Error getting info for "//trim(att_str))
         if (att_type /= NF90_CHAR) &
@@ -806,6 +807,7 @@ subroutine read_attribute_str(filename, attname, att_val, varname, found, all_re
             call MOM_error(FATAL, trim(hdr) // trim(NF90_STRERROR(rc)) //" Difficulties reading "//trim(att_str))
         endif
       endif
+    endif
     if (present(found)) found = (rc == NF90_NOERR)

     if (.not.present(ncid_in)) call close_file_to_read(ncid, filename)
@@ -815,6 +817,10 @@ subroutine read_attribute_str(filename, attname, att_val, varname, found, all_re
     ! Communicate the string length
     info(1) = att_len ; info(2) = 0 ; if (do_read .and. found) info(2) = 1
     call broadcast(info, 2, blocking=.true.)
+    if (present(found)) then
+      found = (info(2) /= 0)
+      if (.not. found) return
+    endif
     att_len = info(1)

     if (att_len > 0) then
@@ -824,7 +830,6 @@ subroutine read_attribute_str(filename, attname, att_val, varname, found, all_re
       if (do_read) tmp_str(1) = att_val
       call broadcast(tmp_str, att_len, blocking=.true.)
       att_val = tmp_str(1)
-      if (present(found)) found = (info(2) /= 0)
     elseif (.not.allocated(att_val)) then
       allocate(character(4) :: att_val) ; att_val = ''
     endif
```

Should I submit a PR here? Or run it through the NCAR branch? (If the latter, should I create a small PR just for this change or bring it in my with tracer module?)

**Comment by Hallberg-NOAA** [comment]
Thank you for these changes, @mnlevy1981.  They look like a lovely, parsimonious correction to the inadvertent behavior changes you noted in this issue.

  You would be welcome to submit the PR with these changes either via dev/gfdl or via dev/ncar; either would work.

  Given that we are trying to sort out as many of the issues posted to dev/gfdl as possible in preparation to move the main branch from NOAA-gfdl over to MOM-ocean, we would find it very convenient if to have the correcting PR come to dev/gfdl soon, but we are also expecting a PR from dev/ncar to main soon, so as long as these corrections are in that collective PR, that would work as well.

**Comment by gustavo-marques** [comment]
Thanks, @mnlevy1981  and @Hallberg-NOAA. I think a small PR to dev/gfdl is the best option for this correction.
