### ISSUE TITLE
Inconsistent units and conversion factors in numerous diagnostics

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#1384]
Prompted by Issue #1017, I decided to survey all of the conversion factors that are used in the calls to register_diag_field, and found that there were at least 17 places where these are inconsistent with the documented units.  With 17 instances out of 715 calls, this is about a 2.5% error rate.

  I will be putting in a pull request to correct these inconsistencies, but I would also like to encourage people to put the units and conversion factor arguments for all register_diag_field calls on the same line to facilitate the detection of inconsistencies.  We do test that the conversion factors are correct with our dimensional consistency testing, but this examination for consistency seems to be the most effective way of scanning through all of our diagnostics to detect these inconsistencies.

**Comment by Hallberg-NOAA** [comment]
This issue has been corrected for now, which can be verified with some relatively simple greps, but it will have to be reexamined periodically in the future, and it should be something that is examined with all new commits that add diagnostics.

**Comment by marshallward** [comment]
I think we could integrate the cited grep command into `trailer.py`-like script without too much trouble if there's a demand.
