### ISSUE TITLE
Trouble with u,v sponges

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#1401]
I am trying out the sponges in my Arctic domain. It runs with sponges on temperature and salt, not with the u,v sponges. I get:
```
FATAL from PE   145: external field u  does not have an associated record dimension (REQUIRED)
```
All five of the time-dependent variables have 12 records.

**Comment by andrew-c-ross** [comment]
I've gotten an error like this when the netcdf data file did not have time as an unlimited dimension.

**Comment by kshedstrom** [comment]
Time is unlimited here, for all the variables.

**Comment by andrew-c-ross** [comment]
I just looked over my notes again and I had the same error when I first started, and it was because there is a new separate namelist variable `SPONGE_UV_STATE_FILE` for the u and v data.

Below is my MOM_input in case it helps:
```
SPONGE_UV = True
SPONGE_DAMPING_FILE = "damping_t_zero.nc"
SPONGE_IDAMP_VAR = "Idamp"
SPONGE_UV_DAMPING_FILE = "damping_uv.nc"
SPONGE_IDAMP_U_var = "Idamp_u"
SPONGE_IDAMP_V_var = "Idamp_v"
SPONGE_STATE_FILE = "1993_test_sponge.nc"
SPONGE_UV_STATE_FILE = "1993_test_sponge.nc"
SPONGE_PTEMP_VAR = "thetao"
SPONGE_SALT_VAR = "salt"
SPONGE_U_VAR = "u"
SPONGE_V_VAR = "v"
INTERPOLATE_SPONGE_TIME_SPACE = True
SPONGE_DATA_ONGRID = True
```

**Comment by kshedstrom** [comment]
Great, thanks! Now I'm getting a different error...
