### ISSUE TITLE
U,V Sponges

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#1410]
As discussed here: [https://bb.cgd.ucar.edu/cesm/threads/trouble-with-u-v-sponges.6130/#post-40283](url),
the u,v sponges are being read on tracer points. It would be nice to have an option to provide them on the proper u,v points and have MOM6 read them as such. We need the equivalent of horiz_interp_and_extrap_tracer_record for the u,v points.

**Comment by kshedstrom** [comment]
I'm not sure this is true. The sponge code as is works once PR #1412 is applied.

**Comment by MJHarrison-GFDL** [comment]
#1412 will mask the u.v sponge at boundaries for regional cases. I agree that this is the correct approach - only apply in the interior and not interfere with the OBC conditions.
