### ISSUE TITLE
DTBT_RESET_PERIOD affects answers when DTBT is the same

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#143]
I just removed DTBT_RESET_PERIOD from OM4_025 and found that DTBT was identical **but** the timestats changed.

We should be able to use DEBUG=True to find out where the differences are coming from.

**Comment by Hallberg-NOAA** [comment]
The logfile is only created during initialization, whereas when the parameter DTBT is set to be negative in the MOM_input file and is set dynamically, the value of dtbt can evolve, with a frequency dermined by DTBT_RESET_PERIOD, and the default is to redo the calculation every thermodynamic time step.  The log file did not lie, in that the initial value of dtbt was properly logged.  At one point in GOLD we also logged whenever dtbt was changed, and perhaps this behavior should be replicated here, perhaps conditional on the value of DEBUG.

**Comment by adcroft** [comment]
How about reporting DTBT depending on the value of VERBOSITY? I agree we don't want to write DTBT every step if we are re-evaluating all the time but it would be good to have the option to see it even when not using DEBUG.

**Comment by adcroft** [comment]
I just sat down to implement reporting DTBT when it changes and found that @Hallberg-NOAA implemented this years and years ago. [See L735](https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/core/MOM_barotropic.F90#L735) that require VERBOSITY>3 to get the messages. @Hallberg-NOAA gets a :clap: 

I'm therefore closing the issue.
