### ISSUE TITLE
Compile FMS in testing with -Duse_LARGEFILE? 

### ISSUE THREAD

**Issue by herrwang0** [NOAA-GFDL/MOM6#1433]
I was running testing on Gaea. It looks like there may be an issue with `libFMS.a` and `.mods` compiled by testing when doing a simple make without additional setting. Error message is "permission denied" when writing netCDF files. Adding a `-Duse_LARGEFILE` to the Makefile that compiles FMS solves the problem. 

I suspect this is an issue of translating the specification of "NETCDF=3" in `mkmf` to Makefile constructed by autoconf? If so, does it make sense to make the tag default (given that `LARGE_FILE_SUPPORT` parameter will go obsolete in MOM6)?

**Comment by marshallward** [comment]
Hi @herrwang0 I accidentally overlooked this issue, I may have been traveling.  It's been a while so perhaps it is no longer a problem.

Does this happen in the `.testing` directory?  Did you add or modify the tests, or re-configure anything?

Generally I have been able to run everything without the `-Duse_LARGEFILE`, and I'm not sure why it was not included, but perhaps it ought to be there for the sake of testing.

**Comment by herrwang0** [comment]
Hi @marshallward, 
Thanks for the rely! 
I tried to redo the tests with a clean set of code but failed to reproduce the issue. Not sure what went wrong the first time... Will close the issue for now.
