### ISSUE TITLE
MOM_io:read_var_sizes sets all dim_names to last dimname

### ISSUE THREAD

**Issue by klindsay28** [NOAA-GFDL/MOM6#1439]
In the following loop
https://github.com/NOAA-GFDL/MOM6/blob/52f906cfc458ee77630f75c9d65da52a87fcfa70/src/framework/MOM_io.F90#L712-L719
the assignment on line 717 sets the full array of strings `dim_names` to `dimname`, instead of just setting `dim_names(n)`. The effect is that all `dim_names` values get set to the last value of `dimname`.

I encountered the above in an experiment where I set `AGE_IC_FILE_IS_Z=True`, and `AGE_IC_FILE` to a file containing `age` with a singleton `time` dimension and the corresponding `time` variable didn't have an `edges` attribute. This combination led to `dim_names(3)='time'` in `MOM_tracer_Z_init:read_Z_edges` and `MOM_io:read_attribute_str` aborted at line 916 in the following block
https://github.com/NOAA-GFDL/MOM6/blob/52f906cfc458ee77630f75c9d65da52a87fcfa70/src/framework/MOM_io.F90#L910-L927
So it looks like `read_attribute_str` is aborting with message `Attribute data type is not a char ...` if the `edges` attribute is not found. I find that error message confusing, as it misdirects the user in this scenario.

Also, is aborting the desired behavior if the argument `found` is passed to `read_attribute_str`, which is the case in `read_Z_edges`'s call to `read_attribute`? I would have expected `rc == NF90_ENOTATT` to be a non-fatal error if the optional argument `found` were present.

**Comment by mnlevy1981** [comment]
> So it looks like read_attribute_str is aborting with message Attribute data type is not a char ... if the edges attribute is not found. I find that error message confusing, as it misdirects the user in this scenario.
> 
> Also, is aborting the desired behavior if the argument found is passed to read_attribute_str, which is the case in read_Z_edges's call to read_attribute? I would have expected rc == NF90_ENOTATT to be a non-fatal error if the optional argument found were present.

First, this looks like the block of code I touched with #1380, which was meant to address the issue of aborting instead of setting `found = .false.` (#1375). If `found` is present and `rc = NF90_ENOTATT`, then the if block at 912 should not be entered so the abort at 916 can't be called.  It looks to me like the issue is that netCDF is reporting that the attribute does exist, but the value of the attribute is not a string so it can not be stored in `att_val`.

**Comment by klindsay28** [comment]
Thanks for chiming in @mnlevy1981. I now see that my sandbox is not up to date. In particular, it doesn't have #1380. So I'm not getting the benefit of that fix. (My sandbox is based on dev/ncar from https://github.com/NCAR/MOM6, which doesn't appear to have #1380 yet.)

The issue with mis-setting `dim_names` still stands though.
