### ISSUE TITLE
Error: Floating-point exception - erroneous artithmetic operation

### ISSUE THREAD

**Issue by markusqs** [NOAA-GFDL/MOM6#1452]
Hello
Im new to the ROMS socitey  so my knowledge is limited. I am turning here to hopefully get some answers.

When running ROMS I get  the error described below, and I have tried for so long without figuring out how to solve it. Can anyone please help

                  Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
                  
                  Backtrace for this error:
                  #0  0x7f0d5ba47d21 in ???
                  #1  0x7f0d5ba46ef5 in ???
                  #2  0x7f0d5ada220f in ???
                  #3  0x55d3a9eb2f7b in __set_depth_mod_MOD_set_depth_tile
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/set_depth.f90:202
                  #4  0x55d3abff1f4e in metrics_tile
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/metrics.f90:482
                  #5  0x55d3ac010339 in __metrics_mod_MOD_metrics
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/metrics.f90:91
                  #6  0x55d3ab67472d in set_grid_
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/set_grid.f90:72
                  #7  0x55d3a9d1089c in initial_
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/initial.f90:127
                  #8  0x55d3a9d08f36 in __roms_kernel_mod_MOD_roms_initialize
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/roms_kernel.f90:131
                  #9  0x55d3a9d0921f in myroms
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/master.f90:73
                  #10  0x55d3a9d09a48 in main
	                  at /home/markus/roms_project2/NORSJO2/Build_romsG/master.f90:50
                  Floating point exception (core dumped)

Markus

**Comment by marshallward** [comment]
I think you probably meant to send this to the ROMS forums.  This site is for the MOM6 ocean model.

You might have more luck here:  https://www.myroms.org/forum/

**Comment by markusqs** [comment]
Thank you
