### ISSUE TITLE
Spatially inconsistent expression for GM+E backscatter coefficient

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#1466]
The expression for the GM+E backscatter coefficients at the corner (q-) points at
https://github.com/NOAA-GFDL/MOM6/blob/e88cdaa785b9fab4e24286031bdd409caf673034/src/parameterizations/lateral/MOM_hor_visc.F90#L1407-L1413
is not properly collocated in space and is not rotationally invariant.  It uses the bathymetry with the same indices as for the other arrays, but this bathymetry is descretized a half-gridpoint to the south and west of the rest of this expression.

  To correct this problem, something like the maximum, the minimum, or the 4-point average of the four neighboring bathymetric depths should be used. @gustavo-marques or @sdbachman, do you have any thoughts on what transformation of the 4 neighboring bathymetries to use?

  Correcting this problem seems likely to change answers for any cases that have `USE_GME = True`.

**Comment by sdbachman** [comment]
The use of the bathymetric depth in that expression is an ad-hoc way of
tapering the backscatter strength in shallow water.  The discretization
should be changed in whatever way is convenient to ensure rotational
invariance and collocation with the other arrays; there is nothing special
about the way it is done at present.

I don't think we have any important cases right now that have USE_GME =
True, so fixing this shouldn't cause us any problems.

**Comment by gustavo-marques** [comment]
@Hallberg-NOAA, thanks for finding this issue and letting us know. I can confirm that we do not have any case with `USE_GME = True`.
