### ISSUE TITLE
Add diagnostic: wmo

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#153]
upward_ocean_mass_transport
wmo
resolved + parameterized 
units = kg/s month 
scope:  XYZ native & sphere, z/p 

This will depend on introducing the ability to diagnose vertical velocity in MOM6.  We can also diagnose this based off of umo and vmo.

We need double check that umo and vmo are resolved + parameterized.

**Comment by adcroft** [comment]
There is also a new diagnostic in OMIP6 document associated with this ticket is "wo" which excludes the parameterized (SGS).

**Comment by jkrasting** [comment]
This is now in the refineDiag step based on a script by @ashao
