### ISSUE TITLE
Unfinished diagnostics

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#161]
There are several diagnostics that are registered but never calculated. Others are registered and calculated but there is no post_data in the code. 

This issue is a reminder to either finish implementing these diagnostics or remove the registration call. When this is done the unfinished_diags list in MOM-examples/test/test_diagnostic_output.py should be updated. 

They are:

 unfinished_diags = [('ocean_model', 'uml_restrat'),
                            ('ocean_model', 'vml_restrat'),
                            ('ocean_model', 'created_H'),
                            ('ocean_model', 'seaice_melt'),
                            ('ocean_model', 'fsitherm'),
                            ('ocean_model', 'total_seaice_melt'),
                            ('ocean_model', 'heat_restore'),
                            ('ocean_model', 'total_heat_restore'),
                            ('ice_model', 'Cor_ui'),
                            ('ice_model', 'Cor_vi'),
                            ('ice_model', 'OBI'),
                            ('ice_model', 'RDG_OPEN'),
                            ('ice_model', 'RDG_RATE'),
                            ('ice_model', 'RDG_VOSH'),
                            ('ice_model', 'STRAIN_ANGLE'),
                            ('ice_model', 'SW_DIF'),
                            ('ice_model', 'SW_DIR'),
                            ('ice_model', 'TA')]

**Comment by marshallward** [comment]
Most of these diagnostics seem to be done, and the few that I can find now have `post_data` statements.  (Possibly resolved in #331).  Thinking we can probably close this?

**Comment by Hallberg-NOAA** [comment]
I believe that all of these diagnostics have now been completed or the registration call removed or at least commented out. If there are still incomplete diagnostics, new issues should be created with an updated lists of missing diagnostics, and this should be done separately for MOM6 and SIS2.
