### ISSUE TITLE
neutral diffusion module needed

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#166]
I am opening this issue to identify the need to write a new module for neutral diffusion.  I propose a title for this module as "MOM_tracer_neutral_diff.F90".  

The present module that performs lateral tracer diffusion, MOM_tracer_horz_diff.F90, should be retained for legacy.  It has limitations for ALE, as this module has comments suggesting it assumes "along coordinate" diffusion is "isopycnal diffusion".  We can not make that assumption with ALE.

**Comment by StephenGriffies** [comment]
Here is an email exchange that is best kept as part of this ticket.  

-----------------------------------------------------------------
Alistair and Bob,

I recommend that the neutral diffusion operator in MOM6 become horizontal diffusion in the surface boundary layer, and in regions shallower than the N^2 cutoff.  Doing so is consistent with the present treatment in z-models, and it follows from the boundary layer work of Treguier, Held, Larichev (1997), and Ferrari et al (2008).  Quite simply, it makes little sense diffusing along neutral directions within the boundary layer.  

Is this modification to the scheme readily doable?

Steve

--------------------------------------------------------------------

Yes, and it might already work that way.
A.

---------------------------------------------------------------------

Hi Steve,

  Making mixing horizontal near the surface is numerically trivial, but I disagree that this is physically the right thing to do. I am aware of the arguments of the papers that you cite, but have never found them to be convincing. Stirring does not lead directly to diapycnal mixing precisely because density surfaces are advected along with the stirred fluid.  If mixing were truly horizontal (and isotropic) near the surface, using similar diffusivities to those appropriate to epineutral mixing in the interior, there would be no sharp near-surface fronts, and yet these fronts are ubiquitous.

  - Bob Hallberg

---------------------------------------------------------------------
Hi,

Your points are well made, though eddies that interact with the ocean surface do mix horizontally. Though I accept that perhaps they do so with less horizontal diffusivity than epineutral diffusivity in the interior. Furthermore, fronts at the surface are reinforced by air-sea fluxes.  But we are not going to settle these questions now.   

I recommend we have options to test the mainstream (horizontal diffusion in the boundary layer) to the alternative (neutral diffusion all the way to the surface).  If the alternative is effective and shown to be physically sound, then it should be published, as it distinctly disagrees with all publications discussing this issue. 

If offer a historical note that indirectly supports your recommendation to dispense with horizontal diffusion. Namely, the arguments for horizontal diffusion in the boundary layer have partly been embraced for numerical reasons, since the use of rotated diffusion in z-models is problematic in the boundary layer. An early NCAR option was to simply remove neutral diffusion in the boundary layer, whereas GFDL made use of horizontal diffusion in this region since the Griffies et al 1998 papers. However, noisy behaviour was found by NCAR given the absence of any lateral mixing in the surface region. So when physical arguments were made to support adding a horizontal diffusion, those arguments were readily embraced.  If the MOM6 neutral diffusion scheme performs well all the way to the surface boundary, then we may dispense with horizontal diffusion for numerical purposes, in which case the physical arguments may be revisited with less prejudice.  

Steve

**Comment by Hallberg-NOAA** [comment]
The requested module has existed for some time now as src/tracer/MOM_neutral_diffusion.F90, while some of the specific capabilities regarding mixing near the surface are in src/tracer/MOM_lateral_boundary_diffusion.F90.
