### ISSUE TITLE
Removal of `public post_data_1d_k` is incompatible with ocean_BGC

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#168]
We recently removed the statement
```
public post_data_1d_k
```
from src/framework/MOM_diag_mediator.F90. Unfortunately, ocean_BGC/generic_tracers/generic_tracer_utils.F90 has the line:
```
    use MOM_diag_mediator, only : post_data_MOM=>post_data, post_data_1d_k
```
so our BGC models no longer compile.

**Comment by Hallberg-NOAA** [comment]
As of July 5. 2022, the offending line has been removed from the master branch of ocean_BGC/generic_tracers/generic_tracer_utils.F90.  However, the deprecated interface should be restored to MOM_diag_mediator.F90 to give a decent interval for this change to ocean_BGC to become widely used.

**Comment by nikizadehgfdl** [comment]
I updated the master branch of ocean_BGC to divert post_data_1d_k to post_data_MOM. Regression tests passed.
