### ISSUE TITLE
Nb (bottom buoyancy frequency) using wrong axes to post diagnostic

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#175]
src/parameterizations/vertical/MOM_set_diffusivity.F90:2797 Nb is using T1 axes in diag registration. I assume this should be Ti?

**Comment by nicjhan** [comment]
OK, there must be some other problem then. 

If FMS is built with DEBUG=1 then this diagnostic with T1 will trigger the following error:

At line 1389 of file ../../../../src/FMS/diag_manager/diag_manager.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'rmask' (31/23)

This goes away when Ti is used instead.

**Comment by MJHarrison-GFDL** [comment]
TKE_itidal uses T1 . The test case is diagnosing TKE_itidal as well? I expect you would get the same error for that diagnostic.

Can you look at output. Nb should be written as a 3-d array with NK-1 levels with zeros, right?

**Comment by nicjhan** [comment]
This is due to incorrect array allocations around MOM_set_diffusivity.F90:2908. Probably all the arrays here should be allocated on data domain not compute. @angus-g has a fix.
