### ISSUE TITLE
No underscores in `sigsetjmp` on MacOS 12

### ISSUE THREAD

**Issue by pittwolfe** [NOAA-GFDL/MOM6#184]
Recent updates have included unit testing routines which reference `sigsetjmp` defined in `src/framework/posix.h` as `__sigsetjmp`. This causes linking to fail with an "unresolved symbol" error because `sigsetjmp` is defined without underscores on MacOS 12 (possible previous versions as well). 

There are a couple of ways to resolve this.  I define `__APPLE__` in my mkmf template and test for this definition in posix.h. Not sure what would fit best with the GFDL coding style.

**Comment by marshallward** [comment]
Hi Chris,
This is resolved in [the autoconf build](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/ac/README.md), but not in the mkmf templates.

You can temporarily resolve this by building with the following flag (with the slashes)

`-DSIGSETJMP_NAME=\"sigsetjmp\"`

But more likely we need to submit a patch the macos mkmf template file.

**Comment by marshallward** [comment]
With respect to your suggestion:

Unfortunately most internal Fortran preprocessors, gfortran included, are run in a very conservative "traditional" mode to avoid side effects from things like `//` style comments.  But it also means that many of the usual cpp macros such as  `__APPLE__` and `linux` are also left undefined.

I would have liked to do something like you suggest:
```
#ifdef linux
#define SIGSETJMP_NAME="_sigsetjmp"
#else
#define SIGSETJMP_NAME="sigsetjmp"
#endif
```
but unfortunately no such macros are available to do that.

(If you are interested: run `gfortran -cpp -dM -E x.f90` on any file `x.f90` to see the symbols, and compare to `cpp -dM < /dev/null`.  Also note `gfortran -dM -E < /dev/null` does not give the correct result!).

**Comment by pittwolfe** [comment]
@marshallward Yes, I have to define `__APPLE__` manually using `-D__APPLE__`, but your suggestion is better since it leaves `posix.h` untouched.

**Comment by marshallward** [comment]
I was about to submit a PR to mkmf which adds these flags, but I noticed that the OS X templates already add `-D__APPLE__` flag the Fortran builds.  So perhaps an `#ifdef __APPLE__` block would help bridge to the older mkmf builds.

But since you had to add it yourself, does that mean you are not using the mkmf templates?

**Comment by pittwolfe** [comment]
I'm using a heavily modified template, so I wasn't sure which bits are original and which are added. This one appears to be in the original mkmf templates, so it's probably safe to assume it'll always be defined for Mac builds.

**Comment by marshallward** [comment]
This conversation has convinced me that there's probably no safe way to implement this function, so I will modify it to be "opt-in", mostly likely via the autoconf builds.

The default will probably either go through `setjmp` with the necessary bits disabled, or just be disabled outright with a runtime FATAL.

**Comment by marshallward** [comment]
I have a potential fix here (https://github.com/NOAA-GFDL/MOM6/pull/196) which only implements `sigsetjmp` if it's been explicitly set (either by the user, mkmf template, or autoconf).

**Comment by marshallward** [comment]
This fix has been merged.  If you want to test it then that would be great, but otherwise we can just close the issue.

**Comment by marshallward** [comment]
Assuming that this has been resolved; closing.
