### ISSUE TITLE
dis-aggregate surface boundary fluxes

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#185]
I was unable to find this issue anywhere, so list it here.  

We need to make use of the code that splits apart the various boundary heat flux components.  There are needs for doing so to enhance diagnostic information, and allow for more realistic treatment of heat content of water fluxes. 

Code has been written, but it has yet to become the standard for OM4.  Problems with model crashes corrupted the initial tests in OM4, and we need to return to those test now that the model is more stable.

**Comment by Hallberg-NOAA** [comment]
@StephenGriffies thinks that issue has been satisfactorily resolved for both GFDL and NCAR.
