### ISSUE TITLE
Scale H_to_m and m_to_H and check that model results are unchanged

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#189]
It should be possible to set H_to_m to any power of 2 and m_to_H = 1 / H_to_m (or vice-verse) and have the model checksums and output remain the same. I have experimented with this and found the following:

1. with a Boussinesq configuration this does not work (e.g. I tried double-gyre), the timestats are very different. I did this by changing H_to_m (and m_to_H) in the code. 
2. with a non-Boussinesq configuration (I tried nonBous_global) this works for small powers of 2, e.g. 2, 4, 8. The timestats are identical. However with a large power of two 1e10 the results were similar but not bit-for-bit identical. I did this by setting the H_TO_KG_M2 parameter. 

Todo: - investigate why this method does not work in the Boussinesq case. - investigate why the timestats are not bit-for-bit identical in the non-Boussinesq case.

**Comment by Hallberg-NOAA** [comment]
Hi Nic,
      
        Of your findings, (1) is a clear indication of a missing
      lengthscale conversion factor somewhere in the Boussinesq code. To
      track this down, add "#override DEBUG = True" to your input file.
      This will cause frequent checksums on a number of variables when
      you run, so save your output to a file, and then rerun with a
      different setting for H_to_m (really this should be made into a
      run-time parameter). The missing unit conversion factor will occur
      in the code that is called just before the first difference in the
      checksums.
      
        (2) is not a a bug. You should only be able to get identical
      answers when you change H_TO_KG_M2 by an exact power of 2, so that
      the answers only change by an integer shift in the exponent when
      the unit conversion factor is applied. In other words setting
      H_TO_KG_M2 to 0.5, 1, 2, 4, 8, 128, 1024, and 1048576 should all
      give identical answers, whereas 3, 5, 1000 or 1000000 should not.
      
        - Bob Hallberg
      
      On 06/08/2015 04:59 PM, Nic Hannah wrote:
    
    
      It should be possible to set H_to_m to any power of 2 and
        m_to_H = 1 / H_to_m (or vice-verse) and have the model checksums
        and output remain the same. I have experimented with this and
        found the following:
      
        with a Boussinesq configuration this does not work (e.g. I
          tried double-gyre), the timestats are very different. I did
          this by changing H_to_m (and m_to_H) in the code. 
        with a non-Boussinesq configuration (I tried nonBous_global)
          this works for small powers of 2, e.g. 2, 4, 8. The timestats
          are identical. However with a large power of two 1e10 the
          results were similar but not bit-for-bit identical. I did this
          by setting the H_TO_KG_M2 parameter. 
      
      Todo: - investigate why this method does not work in the
        Boussinesq case. - investigate why the timestats are not
        bit-for-bit identical in the non-Boussinesq case.
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by nicjhan** [comment]
The ALE remapping gives the following error when passing in a H with units 2^20 * m:

k,h0(k),hNew,dx(+1),dx(0)=           1   1.0000000000000000E-003  -2.3927273881554356E-003  -0.0000000000000000     
 k,h0(k),hNew,dx(+1),dx(0)=           1   1.0000000000000000E-003  -1.6823386112264416E-002  -0.0000000000000000     
 k,h0(k),hNew,dx(+1),dx(0)=           1   1.0000000000000000E-003  -1.5054795516334707E-002  -0.0000000000000000     

FATAL from PE    20: MOM_remapping, remapping_core: negative h implied by fluxes
