### ISSUE TITLE
Floating point exceptions when using -fpe0

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#194]
When the model is built with -fpe0 (intel) or ffpe-trap=invalid,zero,overflow (gnu) a couple of FPEs are triggered. This issue will fix those.

In addition, should we consider making these options standard? I can't find any mention of a down-side on intel/amd procs.

**Comment by mom6jwd** [comment]
In general, setting FPE exception handling will slow performance. We 
haven't tested it recently. But historically the performance loss is 
quite signficant.

On 07/09/2015 10:23 AM, Nic Hannah wrote:
>
> When the model is built with -fpe0 (intel) or 
> ffpe-trap=invalid,zero,overflow (gnu) a couple of FPEs are triggered. 
> This issue will fix those.
>
> In addition, should we consider making these options standard? I can't 
> find any mention of a down-side on intel/amd procs.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NOAA-GFDL/MOM6/issues/194>.
>

-- 
Jeff Durachta
Engineering Lead for Modeling Services
NOAA Geophysical Fluid Dynamics Lab
Forrestal Campus, Princeton University
201 Forrestal Road
Princeton, NJ  08540
Office: +1-609-987-5054

**Comment by adcroft** [comment]
I think we could (should?) use these copmiler options in the DEBUG=1 mode. Right now, the FFLAGS_DEBUG in [ncrc-gnu.mk](https://github.com/NOAA-GFDL/mkmf/blob/master/templates/ncrc-gnu.mk) just turns off optimization and turns on bounds checking. I agree with @mom6jwd that we would not worry about catching these exceptions for production executables.

**Comment by nicjhan** [comment]
I have created an mkmf issue NOAA-GFDL/mkmf#6 to add -fpe0 for debug builds.
