### ISSUE TITLE
Various bugs/problems found running MOM6 on raijin in Aus

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#198]
This is a bit of a catch-all issue for problems that I've noticed while running MOM6 on raijin in Aus. Also I'm able to run valgrind on the compute nodes there, this may reveal some issues which I'll post here. 

* make_alloc() is not supported by the default gcc/gfortran version (4.4.7) on raijin. There is an assert in the code that checks for this but the error message could be improved. 

* line 1656 in MOM_set_diffusivity.F90 causes a 'floating invalid' exception. #194 will fix this. Interestingly the approach making sure that the denominator or is at least G%H_subroundoff works on gaea but not on raijin.

**Comment by nicjhan** [comment]
* various MEKE%<field> variables may have garbage at the edges ... e.g. in parameterizations/lateral/MOM_MEKE.F90:1190 MEKE%Kh is initialised on range j=js-1, je+1, i=is-1,ie+1 using barotrFac2, however this is only defined from js-je, is-ie. The same goes for bottomFac2 and variables initialised using this. .... actually it might only be a problem with MEKE%Kh

**Comment by adcroft** [comment]
Concerning MEKE: is the issue that the loops at [L439](https://github.com/NOAA-GFDL/MOM6/blob/9b132e2346468ed18d06957e2e42ee4f3d89cb82/src/parameterizations/lateral/MOM_MEKE.F90#L439), L446, L452 do not need to be wide since the is a halo update at L457?

If reducing those loop ranges to the computational domain works under valgrind then I think the model solutions will be unchanged (because of the halo update).

**Comment by nicjhan** [comment]
OK, I'll give that a try. Thanks

**Comment by adcroft** [comment]
Just realized that LmixScale is used at L465 in a wider loop so that needs to be calculated wide as you suggested earlier...

**Comment by adcroft** [comment]
Something like this...
```bash
% git diff -U0 src/parameterizations/lateral/MOM_MEKE.F90
diff --git a/src/parameterizations/lateral/MOM_MEKE.F90 b/src/parameterizations/lateral/MOM_MEKE.F90
index 562c22f..0ff7360 100644
--- a/src/parameterizations/lateral/MOM_MEKE.F90
+++ b/src/parameterizations/lateral/MOM_MEKE.F90
@@ -439 +439 @@ subroutine step_forward_MEKE(MEKE, h, SN_u, SN_v, visc, dt, G, CS)
-          do j=js-1,je+1 ; do i=is-1,ie+1
+          do j=js,je ; do i=is,ie
@@ -446 +446 @@ subroutine step_forward_MEKE(MEKE, h, SN_u, SN_v, visc, dt, G, CS)
-          do j=js-1,je+1 ; do i=is-1,ie+1
+          do j=js,je ; do i=is,ie
@@ -452 +452 @@ subroutine step_forward_MEKE(MEKE, h, SN_u, SN_v, visc, dt, G, CS)
-        do j=js-1,je+1 ; do i=is-1,ie+1
+        do j=js,je ; do i=is,ie
@@ -636 +636 @@ subroutine MEKE_lengthScales(CS, MEKE, G, SN_u, SN_v, &
-  do j=js,je ; do i=is,ie
+  do j=js-1,je+1 ; do i=is-1,ie+1
```

**Comment by nicjhan** [comment]
forrtl: error (63): output conversion error, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source             
MOM6               00000000054E649A  Unknown               Unknown  Unknown
MOM6               00000000054E4F96  Unknown               Unknown  Unknown
MOM6               0000000005490D10  Unknown               Unknown  Unknown
MOM6               000000000542DC5E  Unknown               Unknown  Unknown
MOM6               000000000542D19F  Unknown               Unknown  Unknown
MOM6               000000000546E8AF  Unknown               Unknown  Unknown
When running OM4_025 on raijin:

MOM6               00000000007035F7  ice_grid_mod_mp_s         573  ice_grid_mod.F90
MOM6               00000000006F8293  ice_grid_mod_mp_s         459  ice_grid_mod.F90
MOM6               00000000018ACC05  ice_model_mod_mp_        3732  ice_model.F90
MOM6               0000000001ACB443  coupler_main_IP_c        1447  coupler_main.F90
MOM6               0000000001ABBACC  MAIN__                    428  coupler_main.F90
MOM6               000000000040D36C  Unknown               Unknown  Unknown
libc.so.6          00007F88B0754D5D  Unknown               Unknown  Unknown
MOM6               000000000040D269  Unknown               Unknown  Unknown

**Comment by nicjhan** [comment]
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
MOM6               0000000001C96B7A  ice_dyn_cgrid_mp_         687  ice_dyn_cgrid.F90
MOM6               00000000016EC0B5  ice_model_mod_mp_        1968  ice_model.F90
MOM6               0000000001525A41  ice_model_mod_mp_         134  ice_model.F90
MOM6               0000000001AB8626  MAIN__                    783  coupler_main.F90
MOM6               000000000040D36C  Unknown               Unknown  Unknown
libc.so.6          00007F21EC6EAD5D  Unknown               Unknown  Unknown
MOM6               000000000040D269  Unknown               Unknown  Unknown

**Comment by nicjhan** [comment]
I am closing this issue and breaking the remain problems up into separate issues. They are:

make_alloc: #202
floating invalid: #194 
MEKE%Kh: #203

Formatting issues have been fixed and merged by @adcroft
