### ISSUE TITLE
MOM_parameter_doc and KPP% inconsistent

### ISSUE THREAD

**Issue by amylangenhorst** [NOAA-GFDL/MOM6#199]
This is partly my novice-ness, but I tried to modify this value which I saw in my MOM_parameter_doc:

MINIMUM_OBL_DEPTH = 6.0         !   [m] default = 0.0

However, this does not work:
# override MINIMUM_OBL_DEPTH = 0.0

When I appended "KPP%", the setting worked / had the expected value:
# override KPP%MINIMUM_OBL_DEPTH = 0.0

Maybe there's an issue with the "KPP%" coming out in MOM_parameter_doc.

**Comment by Hallberg-NOAA** [comment]
This is a case where this a parameter for a specific sub-module. The full parameter name is `KPP%MINIMUM_OBL_DEPTH`, but this can also be set along with other parameters for this module with a line like `KPP%` before this parameter is set in the input or override file. The block specifying the module is closed with `%KPP`. In this case the two options that would have worked are either resetting this parameter via:

  `override KPP%MINIMUM_OBL_DEPTH = 0.0`

or via:

  `KPP%`
  `override MINIMUM_OBL_DEPTH = 0.0`
  `%KPP`

The former is more convenient when only a single parameter is being set; the latter more convenient if there are large number of parameters being set or recorded. Examination of the MOM_parameter_doc.all file will show that it includes the additional `KPP%` and `%KPP` lines above and below this point where this parameter value is recorded.

  As always, this case serves as a reminder of the value of checking the MOM_parameter_doc.all files to figure out what the model actually did.
