### ISSUE TITLE
Scale diagnostics with optional argument at registration

### ISSUE THREAD

**Issue by jgjgfdl** [NOAA-GFDL/MOM6#201]
Similar to cmor_name, cmor_units, ... we like to be able to provide an optional real argument when we register a diagnostic that would be used to scale the diagnostic field and converting the units and place the results in a different component using the same variable name.

e.g.
"generic_cobalt", "o2", "o2", "ocean_cobalt_tracers_month", ...
"generic_cobalt_scaled", "o2", "o2", "ocean_cobalt_tracers_month_cmip", ...

where the registration for "o2" within COBALT has an optional arguments such as " scale_multiplier=1035.0, scale_units='moles m-3' " which would only be used for the "generic_cobalt_scaled" output.

**Comment by MJHarrison-GFDL** [comment]
This sounds like a fms change to diag table, e.g. "spatial_ops" column is used to scale diagnostics if real.
Does that sound reasonable?
On Jul 14, 2015 4:06 PM, jgjgfdl <notifications@github.com> wrote:Similar to cmor_name, cmor_units, ... we like to be able to provide an optional real argument when we register a diagnostic that would be used to scale the diagnostic field and converting the units and place the results in a different component using the same variable name.

e.g.
"generic_cobalt", "o2", "o2", "ocean_cobalt_tracers_month", ...
"generic_cobalt_scaled", "o2", "o2", "ocean_cobalt_tracers_month_cmip", ...

where the registration for "o2" within COBALT has an optional arguments such as " scale_multiplier=1035.0, scale_units='moles m-3' " which would only be used for the "generic_cobalt_scaled" output.

**Comment by MJHarrison-GFDL** [comment]
The question is , is this a cmor-specific thing? Not in principle, but the diag_manager solution would have the wrong units. So I guess in practice it is restrictive to CMOR-ization.
On Jul 14, 2015 4:06 PM, jgjgfdl <notifications@github.com> wrote:Similar to cmor_name, cmor_units, ... we like to be able to provide an optional real argument when we register a diagnostic that would be used to scale the diagnostic field and converting the units and place the results in a different component using the same variable name.

e.g.
"generic_cobalt", "o2", "o2", "ocean_cobalt_tracers_month", ...
"generic_cobalt_scaled", "o2", "o2", "ocean_cobalt_tracers_month_cmip", ...

where the registration for "o2" within COBALT has an optional arguments such as " scale_multiplier=1035.0, scale_units='moles m-3' " which would only be used for the "generic_cobalt_scaled" output.

**Comment by adcroft** [comment]
I don't think diag_manager can do this because the units change along with
the scaling. The idea is to provide the scaling and alternate units at
registration so that the model output is correct and self consistent if the
alternate diagnostic is requested. e.g. kg/m3 scaled to moles/l.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by Hallberg-NOAA** [comment]
This scaling is already done for MOM6. If this is still an issue for generic tracers it should be raised in the generic tracer github site.
