### ISSUE TITLE
Remove use of move_alloc() 

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#202]
move_alloc() is a fortran 2003 (?) feature. It does not work on older compiler versions, e.g. the default gcc/gfortran (4.4.7) on raijin. 

So it should be removed and replaced with copies.

**Comment by angus-g** [comment]
Would it be possible to instead just compile with `-std=f2003` on GNU compilers? Intel Fortran for example defaults to this, but GNU defaults to F95 + some GNU extensions. Compiler support for the feature has been there for a while

**Comment by adcroft** [comment]
In practice, yes, but I have generally found it more useful to stick with the older standards which are better supported. In this particular case there is little to be gained in using the new extension (saves a few lines of code and some copying during initialization). I think we've successfully managed to avoid F2003 extensions so far and it's helped on platforms where (incredibly) we don't have the latest compilers.  Although I wonder if any other uses have slipped through...?
On Aug 4, 2015 22:20, Angus Gibson <notifications@github.com> wrote:Would it be possible to instead just compile with -std=f2003 on GNU compilers? Intel Fortran for example defaults to this, but GNU defaults to F95 + some GNU extensions. Compiler support for the feature has been there for a while
