### ISSUE TITLE
test case timestats for other machines

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#212]
I have setup run tests on the NCI computer raijin:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/

Presently they only check the model return code. It would be good to also have tests that compare checksums. Perhaps a repo with per-site/machine timestats and config files?

**Comment by marshallward** [comment]
The diagnostic checksums in `.testing` and debug output tracking (`std.err`) presumably provide something very close to the checksums mentioned here, and the portability of `.testing` should permit it to be run on other platforms as needed.
