### ISSUE TITLE
GMwork array is not sign definite

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#217]
The GMwork array is computed in 

MOM6-examples/src/MOM6/src/parameterizations/lateral/MOM_thickness_diffuse.F90

This term has been found to be sign-indefinite.  That is wrong.  The physical term is sign-definite (GM is a potential energy sink).  For most of the ocean, it is negative (a sink).  But there are any number of positive locations found throughout the global ocean. The lack of sign-definiteness revealed in global_ALE/z as well as global (isopycnal moddel).   

The GMwork array must be coded wrong. This error must be corrected to ensure that the GM source term is properly handled if/when using the MEKE approach to compute diffusivities.  Without a sign-definite source term, the MEKE scheme will produce spurious diffusivities.

**Comment by Hallberg-NOAA** [comment]
This issue is merged with #965.
