### ISSUE TITLE
Global averaged flux diagnostics need CMOR names

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#223]
Global average flux diagnostics coded into core/MOM_forcing_types.F90 need to have CMOR 
names attached as part of the diagnostic registration.  For example, "sw_ga" should have a CMOR
name "rsntds_ga".  By attaching CMOR names to these "_ga" diagnostics, we can more readily move fully over to CMOR names.

**Comment by jkrasting** [comment]
Agreed.  How many of these diagnostics actually have formal CMOR names?

**Comment by StephenGriffies** [comment]
Here are the "ga" time series that need to have CMOR attributes:

prcme_ga = wfo_ga
evap_ga = evs_ga
net_heat_surface_ga = hfds_ga
lw_ga = rlntds_ga
lat_ga = hfls_ga
sw_ga = rsntds_ga
sens_ga = hfss_ga

**Comment by StephenGriffies** [comment]
Issue closed with tag 

31428b81b2803a6365db393edc6fd7ab0abb438b
