### ISSUE TITLE
ALE: Remove module polynomials_functions.F90

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#232]
Polynomials functions module provides two simple operations (evaluation and integration) for arbitrary order polynomials.

Todo:
- Replace the calls to evaluation_polynomial(), integration_polynomial() with explicit expressions for the evaluations/integrations.
- Currently the evaluations and integrals loop over each term in the polynomial. Expanding expressions by hand (e.g. for PCM, order=1, f=a(0), for PLM, order=2, f=a(0)+a(1)*x, ...) will avoid loop overhead at a cell-by-cell level.
- The order of polynomial is dynamically sized. Is there any benefit to hard code for order 5 in the memory allocation and simply ignore unused coefficients?
  - An advantage of dynamically sizing is we can catch out-of-bounds references with a debug executable.

This module is a leftover from a more OO-version of the ALE code used when first developed.

**Comment by adcroft** [comment]
Niki,

So far, and after inlining, we have only considered expanding powers into multiplies but without changing the order of summation in a futile attempt to not change answers (answers did change). Since the code did speed up with 328f83c3ecfb5b967268d8aadccf3bad08435f20 we might as well continue with answer changing optimizations.

Currently the polynomial evaluations are of the form
> f(x) = a + b . x + c . x.x ...

which has N(N-1)/2 multiplies. We discussed refactoring this to
> f(x) = a + x . ( b + x . ( c ... ) )

which has N-1. However, I just realized that we use this particular evaluation fairly rarely (only for edge values and vanished target layers) so this will not save much time.

I expect more time to be spent in the evaluations of the integral, F(x,y) = integral f between x..y . We currently have that coded as
> F(x,y) = a . ( x - y ) + b . ( x.x - y.y ) / 2 + c . ( x^3 - y^3 ) / 3 ...

which is somewhat natural to use when x-y is small but has N^2 multiples. To get the reduced number of multiplies we'll have to take the difference of two polynomials:
> g(x) = x . ( a + x . ( b/2 + x . ( c/3 ... ) ) )
> g(y) = y . ( a + y . ( b/2 + y . ( c/3 ... ) ) )
> F(x,y) = g(x) - g(y)

which will have different round off behavior but only 2N multiplies. It is actually slower for PCM (N=1) and no faster for PLM (N=2).

I'm therefore mixing things up and coding it as
> g'(x) = x . x . ( c/3 + x . ( d/4 ... ) )    for N>2
> g'(y) = y . y . ( c/3 + y . ( d/4 ... ) )    for N>2
> F(x,y) = ( x - y ) . ( a + b . ( x + y ) ) + g'(x) - g'(y)

which has N multiples for N=1,2 and 2N multiples for N>2.

**Comment by adcroft** [comment]
I made a mistake at the end of my last comment (I've edited OP to flag mistake) - I missed some multiplies in both the last expressions and my counting.

The best I think we can do is, for N>
> g(x) = x . ( a + x . ( b/2 + x . ( c/3 ... ) ) )
> g(y) = y . ( a + y . ( b/2 + y . ( c/3 ... ) ) )
> F(x,y) = g(x) - g(y)

and for N=1,2:
> F(x,y) = ( x - y ) . ( a + b . ( x + y ) )

**Comment by Hallberg-NOAA** [comment]
We will be using these integrals to calculate averages, so I suspect that we will find more robust behavior if we only use forms that explicitly factor out (x-y) in all terms.  We have such forms for x^N - y^N up to 5, and could find them for higher N.

The issue with the form F(x,y) = g(x) - g(y) is that it will include differences of large terms that may not cancel out nicely with x-y.

**Comment by adcroft** [comment]
Agreed. `F(x,y)= g(x) - g(y)` is not numerically robust. So...

N=1:
> F(x,y) = ( x - y ) . [ a ]

N=2:
> F(x,y) = ( x - y ) . [ a + b . ( x + y ) ]

N=3:
> F(x,y) = ( x - y ) . [ a + b/2 . ( x + y ) + c/3 (x.x + x.y + y.y ) ]

N=5:
> F(x,y) = ( x - y ) . [ a + b/2 . ( x + y ) + c/3 . (x.x + x.y + y.y )  + d/4 . ( x.x.x + x.x.y + x.y.y + y.y.y ) +
>     e/5 . ( x.x.x.x + x.x.x.y + x.x.y.y + x.y.y.y + y.y.y.y ) ]

better written as?
> F(x,y) = ( x - y ) . [ a + b/2 . ( x + y ) + c/3 . (x.x + x.y + y.y )  + d/4 . ( x.x + y.y ) . ( x + y ) +
>     e/5 { ( x.x.x + y.y.y ) . ( x + y ) + x.x.y.y } ]
