### ISSUE TITLE
ALE: Move select case (method) within integrateReconOnInterval() up the call tree

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#234]
Function integrateReconOnInterval() uses a `select case (method)` structure on a cell-by-cell basis which is very inefficient.

Todo:
- Create versions of integrateReconOnInterval() for PCM, PLM, PPM, PQM so the `select case` can be made at a higher level.

**Comment by Hallberg-NOAA** [comment]
Subsequent code refactoring has made this issue irrelevant.
