### ISSUE TITLE
MOM6 can not reopen existing NetCDF files for appending

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#243]
Due to changes that appear to have been introduced to mpp_open at some point for files that are to be appended, MOM6 is unable to continue writing to timestats.nc in multiple run segments. This occurs for multiple compilers. Work is underway to determine how widespread this problem is, how far back it goes, and how to correct it.

**Comment by nikizadehgfdl** [comment]
Zhi has provided a fix for this issue in the shared code which seems to work.  [gitlab shared branch user/z1l/dev] (http://gitlab.gfdl.noaa.gov/fms/shared/commit/98184d18a22fd01079e1eb2ca6ca813979842eb3 ).

**Comment by Hallberg-NOAA** [comment]
This no longer appears to be an issue with the version of FMS that is being used by MOM6 by default, and probably has not been a problem for a long time. This issue can be closed.
