### ISSUE TITLE
OM4_025 and OM4_05 not reproducing across different PE counts 

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [NOAA-GFDL/MOM6#246]
@nikizadehgfdl and @MJHarrison-GFDL both found reproducibility bugs for these experiments using 648 and 864 PEs on Gaea.

New version of FMS/shared  is on user/z1l/horiz_interp at gitlab.gfdl   

Switching to the newer version of FMS will cause an answer change for this test case.  Time 0 energy difference from timestats is O(10^-12). 6hr energy difference is O(10^-7) .

**Comment by nikizadehgfdl** [comment]
@MJHarrison-GFDL  and @adcroft  Zhi's fix is in dev/master for FMS at hithub

https://github.com/NOAA-GFDL/FMS/commit/8d59d412cf5b3cad3dbaa3d0b115af587746776f

This update should resolve the issue with  experiments using 648 and 864 PEs .

**Comment by MJHarrison-GFDL** [comment]
close

**Comment by MJHarrison-GFDL** [comment]
close

**Comment by MJHarrison-GFDL** [comment]
close
