### ISSUE TITLE
1/2 degree coupled model crashes with  NETCDF ERROR: NetCDF: Numeric conversion not representable 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#249]
CM4_c96L32_am4g7_2000_OMp5 using 1/2 degree grid crashes on the first day with:

FATAL from PE   576: NETCDF ERROR: NetCDF: Numeric conversion not representable File=00010101.ocean_annual.nc.0000 Field=opottemptend

Commenting out the diagnostics from diag_table let's the model run.

**Comment by nikizadehgfdl** [comment]
Here's another one that causes crash at the end of  1st year:

FATAL from PE  1150: NETCDF ERROR: NetCDF: Numeric conversion not representable File=00010101.ocean_annual.nc.0002 Field=T_tendency

**Comment by adcroft** [comment]
I was able to reproduce this problem in global_ALE/z by setting DIABATIC_FIRST=False.
