### ISSUE TITLE
PGI answers for OM4 do not match across restart 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#257]
MOM6 tag 2016.03.02 (the issue is probably much older)
When compiled with pgi15 on c3 the experiment OM4_SIS2_low_mixing3 does not reproduce when a restart is involved
(i.e., 2 days restart files do not match 1+1 days restart files) (irrespective of mask_table being used or not).

There is no such issue for the intel15 runs on c3.

I have not seen a non-repeatability issue (answer changes between dual runs) with pgi15  for this experiment (3 runs so far) . So this is most probably a restart issue (75%).

**Comment by nikizadehgfdl** [comment]
The restart issue also exists on c2 with pgi14

**Comment by nikizadehgfdl** [comment]
The problem exists in the much smaller (32 pes) test case MOM6_SIS2_bergs_cgrid 
PGI does not reproduce across a restart whereas Intel does.

Also, I think the issue exists only in prod mode (-O3) and goes away in repro mode (-O2).

**Comment by adcroft** [comment]
DEBUG=True issue has been fixed in b4f8cdb5fc60
<https://github.com/NOAA-GFDL/MOM6/commit/b4f8cdb5fc609e345787e9b72f12eaea18ff02f6>
.

-A.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540
