### ISSUE TITLE
1/2 degree coupled model crashes with a particular layout, No mask_table, Not backscatter

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#264]
CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE crashes in "debug" (-O0)  mode when using 432 pes with an ocean layout of 36,12 (no mask_table) with traceback:

```
forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source
fms_cm4_sis2_comp  00000000011FDFC8  mom_eos_wright_mp         150  MOM_EOS_Wright.F90
fms_cm4_sis2_comp  00000000011394EC  mom_eos_mp_calcul         199  MOM_EOS.F90
fms_cm4_sis2_comp  0000000003E57ED8  mom_isopycnal_slo         234  MOM_isopycnal_slopes.F90
fms_cm4_sis2_comp  000000000395E8BC  mom_lateral_mixin         373  MOM_lateral_mixing_coeffs.F90
fms_cm4_sis2_comp  00000000014EE9AB  mom_mp_step_mom_          784  MOM.F90
fms_cm4_sis2_comp  00000000011CFC97  ocean_model_mod_m         414  ocean_model_MOM.F90
fms_cm4_sis2_comp  000000000040588A  MAIN__                    912  coupler_main.F90
```
stdout:

/lustre/f1/Niki.Zadeh/ulm_201510_awg_v20160212_mom6dust_2016.03.22/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE/ncrc2.intel15-debug/stdout/run/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE_1x0m1d_504x1a_432x1o.o5043140

/lustre/f1/Niki.Zadeh/ulm_201510_awg_v20160212_mom6dust_2016.03.22/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE/ncrc2.intel15-debug-openmp/stdout/run/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE_1x0m1d_432x2a_432x1o1.o5043145

The same experiment and layout runs OK in "prod" (-O3) mode

/lustre/f1/Niki.Zadeh/ulm_201510_awg_v20160212_mom6dust_2016.03.22/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE/ncrc2.intel15-prod-openmp/stdout/run/CM4_c96L32_am4g9_2000_OMp5_COBALT_dust1_H5_MEKE_1x0m1d_432x2a_432x1o.o5043142

The same experiment runs in debug mode with other layout, including 42,12  and 16,36 

The following are the override parameters used in this model
```
cat > $work/INPUT/MOM_override << MOM_OVERRIDE_EOF
#override NIGLOBAL = 720
#override NJGLOBAL = 576
#override TEMP_SALT_Z_INIT_FILE = "WOA05_ptemp_salt_annual.nc"
#override Z_INIT_FILE_PTEMP_VAR = "ptemp"
#override TEMP_SALT_Z_INIT_FILE = "WOA05_ptemp_salt_annual.nc"
#override Z_INIT_FILE_SALT_VAR  = "salt"
#override TIDEAMP_FILE          = "tidal_amplitude.nc"
Z_INIT_REMAP_GENERAL = True
Z_INIT_REMAP_FULL_COLUMN = True
REMAP_AFTER_INITIALIZATION = False
#override REGRIDDING_COORDINATE_MODE = "HYCOM1"
#override ALE_COORDINATE_CONFIG = "HYBRID:hycom1_75_800m.nc,sigma2,FNC1:2,4000,4.5,.01"
MAXIMUM_INT_DEPTH_CONFIG = "FNC1:5,8000.0,1.0,.01"
MAX_LAYER_THICKNESS_CONFIG = "FNC1:400,31000.0,0.1,.01"
REGRID_COMPRESSIBILITY_FRACTION = 0.01
BOUNDARY_EXTRAPOLATION = True
DYNAMIC_SURFACE_PRESSURE = True
#override USE_NEUTRAL_DIFFUSION = True
#override KHTR = 300.
KH_RES_FN_POWER = 100
MEKE_KHTH_FAC = 1.0
VISC_RES_FN_POWER = 100
#override DT = 2400
#override DT_THERM = 10800
#override DIABATIC_FIRST = False
THERMO_SPANS_COUPLING = True
#override USE_generic_tracer = True
#override CHL_FROM_FILE = False
#override USE_RIVER_HEAT_CONTENT = True
#override USE_CALVING_HEAT_CONTENT = True

#override OCEAN_SURFACE_STAGGER = "C"
#override TOPO_EDITS_FILE       = ""

#override ENERGYSAVEDAYS = 30

MOM_OVERRIDE_EOF

cat > $work/INPUT/SIS_override << SIS_OVERRIDE_EOF
#override NIGLOBAL = 720
#override NJGLOBAL = 576

SIS_OVERRIDE_EOF

```

**Comment by nikizadehgfdl** [comment]
This is reproducible in any 1/2 degree ocean-ice CORE experiment when
THERMO_SPANS_COUPLING = True
#override DIABATIC_FIRST = False

It does not go away by the fix for #249

ddt shows huge values (10^64) for T&S on line 150  in MOM_EOS_Wright.F90 which I assume cause the machine to choke because they are being multiplied together. 

So far, this is occurring only for a specific layout of 36,12 and not any other (not even for 12,36).

**Comment by adcroft** [comment]
So the diagnostics I fixed in #249 do work in other layouts? Does turning
off the diagnostics fix it or is this another problem?

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by nikizadehgfdl** [comment]
Yes, the fix for #249 worked and let the model run for all layouts except 36,12.  This issue is unrelated to diagnostics and happens only for a particular layout (36,12) which I came up on by chance. It looks like a land mask issue.

**Comment by nikizadehgfdl** [comment]
Array T is initialized in a subroutine call from tv%T, Line 110 of MOM-isopycnal_slopes.F90
```
call vert_fill_TS(h, tv%T, tv%S, dt_kappa_smooth, 1.0, T, S, G, 1)
```
Here the halo size is passed as 1 (the last argument). In this test jsc=52, so the last element of T initialized is at j=53, and the rest has uninitialized junk in it (-2. e^+61).
But then at line 231 of MOM_isopycnal_slopes.F90 
```
T_v(i) = 0.25*((T(i,j,k) + T(i,j+1,k)) + (T(i,j,k-1) + T(i,j+1,k-1)))
```
array element j=54 of T (which is uninitialized and -2.e+61) is accessed and averaged on , making T_v(21)=-2.e+61
which is passed to the subroutine calculate_density_derivs which tries to cube it, at which point the machine chokes.

Now, why is the halo is passed to be 1 while in this example it is 4? (G%jsc=52, G%jed=56)

**Comment by nikizadehgfdl** [comment]
I proposed a fix in a pull request, basically I think the halo is missed in the call to vert_fill_TS

```
<  call vert_fill_TS(h, tv%T, tv%S, dt_kappa_smooth, 1.0, T, S, G, 1)
>  call vert_fill_TS(h, tv%T, tv%S, dt_kappa_smooth, 1.0, T, S, G, halo+1)
```

This is not changing answers as far as I tested, but please review critically.
