### ISSUE TITLE
ocean.stats.nc

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#266]
I'm getting this error from MOM6:
> WARNING from PE     0: MOM_io:  Reopening file ./ocean.stats.nc apparently had           -1  variables. Clobbering and creating file with           18  instead.
> 
> 
> WARNING from PE     0: MOM_io:  Reopening file ./ocean.stats.nc apparently had           -1  variables. Clobbering and creating file with           18  instead.
> 
> 
> FATAL from PE     0: NETCDF ERROR: Permission denied File=./ocean.stats.nc
> 
> 
> FATAL from PE     0: NETCDF ERROR: Permission denied File=./ocean.stats.nc

The file mode is:
  64 -rw-r--r-- 1 kate akwaters    63638 Apr 17 03:52 ocean.stats.nc

**Comment by adcroft** [comment]
I'm unable to reproduce this problem - I've tried in both restart and cold-start modes, with gnu, intel and pgi compilers.

The WARNING messages imply you have the fix that we implemented to handle the "-1 variables" problem coming from mpp  (NOAA-GFDL/MOM6@60ea31f1ec).

Clearly something is behaving differently for you than for us. I'm not sure how to debug this when we can't reproduce it.

-A.

**Comment by adcroft** [comment]
@kshedstrom Is this still happening? When we screen-shared week ago it seemed this problem had resolved itself but we weren't sure of the source of the problem. If it hasn't recurred, I'll put this down to "cosmic ray interfering with file permissions".

**Comment by kshedstrom** [comment]
Hi Alistair,

No, it's not happening now.

I'm playing totalview now, no idea what I'm doing.

Kate

**Comment by adcroft** [comment]
I hate that game, although Bob likes it. Most of the FPS games, including totalview, give me motion sickness. Oddly, minecraft also does that to me - I have to leave the room when kids start playing and they know it. I prefer space-combat strategy games, like ddt.

**Comment by kshedstrom** [comment]
I've had enough totalview for one day. It's taken time to get used to it
after the loss of our favorite prism game.

I used to be into Puzzle Pirates, where the best puzzle of all turned out
to be island design.

**Comment by adcroft** [comment]
Consensus is "cosmic ray interfering with file permissions".
