### ISSUE TITLE
division by zero  when doing z-diagnostics resulting debug mode crash

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#272]
I add the following to MOM_override to be able to produce z-diagnostics:

DIAG_REMAP_Z_GRID_DEF = "FILE:analysis_vgrid_lev35.v1.nc,zw"

This works fine in prod mode and produces the z-diagnostics.
But the model crashes in debug mode with the following traceback:

```
fms_MOM6_SIS2_com  00000000006B4CE2  mom_regridding_mp         620  MOM_regridding.F90
fms_MOM6_SIS2_com  00000000005D82CA  mom_diag_mediator         851  MOM_diag_mediator.F90
fms_MOM6_SIS2_com  0000000000898720  mom_mp_initialize        1792  MOM.F90
fms_MOM6_SIS2_com  000000000058C81E  ocean_model_mod_m         226  ocean_model_MOM.F90
fms_MOM6_SIS2_com  000000000041272E  coupler_main_IP_c        1559  coupler_main.F90
fms_MOM6_SIS2_com  00000000004014B9  MAIN__                    520  coupler_main.F90
```

Line 620 of MOM_regriding.F90 being:
```
  stretching = total_thickness / depth
```
ddt shows that depth=0 in this first call.

This is dev/master/2016.03.22   without my updates for COBALT diagnostics (although I get it when compiling my updates too).

xml: OM4.xml , experiment: OM4_SIS2_05_z_diag

**Comment by nikizadehgfdl** [comment]
Division by depth=0 happens everywhere on the land mask. Why isn't the call to  build_zstar_column() 
(line 851 of MOM_diag_mediator.F90 in the stack) masked?

**Comment by adcroft** [comment]
Isn't this line doing that?

https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/ALE/MOM_regridding.F90#L559

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by nikizadehgfdl** [comment]
No, this one is called directly from MOM_diag_mediator.F90 without going through that masking:

https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/framework/MOM_diag_mediator.F90#L839

**Comment by nikizadehgfdl** [comment]
I applied the logic in src/ALE/MOM_regridding.F90#L559 and made a pull request
