### ISSUE TITLE
Diagnostics FrictWork and FrictWorkIntz have incorrect axes

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#274]
Looking at lines ./parameterizations/lateral/MOM_hor_visc.F90:1175 and ./parameterizations/lateral/MOM_hor_visc.F90:1178 shouldn't the axes be axesBL and axesB1 respectively? 

On a symmetric grid the shape of the currently used axes (TL and T1) does not match the field, this will cause an array bound under/overrun.

**Comment by Hallberg-NOAA** [comment]
No, the axis definitions are correct, but the memory declarations of FrictWork and FrictWorkIntZ on lines 257 and 262 are wrong with symmetric memory. These arrays should have been declared consistently with being discretized at T points, not Bu points. Apart from diagnostics, this bug should be innocuous.
@nicjhan, do you want to fix this inconsistency, or should I do it?

**Comment by nicjhan** [comment]
Hi @Hallberg-NOAA thanks for the clarification. I'll send a fix soon.
