### ISSUE TITLE
Uninitialized T and S being used in MOM_isopycnal_slopes.F90

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#277]
The if-statement at src/MOM6/src/core/MOM_isopycnal_slopes.F90:204 which sets the slope of neutral surfaces can use uninitialised values. This will only happens when use_EOS is set. 

This occurs because the bounds used in vert_fill_TS() do not include halos, whereas the latter part of calc_isoneutral_slopes reads the halo in the i-direction. e.g. the loop at src/MOM6/src/core/MOM_isopycnal_slopes.F90:156

A simple fix would be to extend the domain of the calculation in vert_fill_TS(). Does this sound OK?

This bug can cause a floating invalid exception.

**Comment by nicjhan** [comment]
This is a duplicate of #264

**Comment by adcroft** [comment]
I take it you didn't have that fix?

**Comment by nicjhan** [comment]
No, :(, my MOM6 code was a few days behind. Also better keep a closer eye on new issues!
