### ISSUE TITLE
Floating invalid in calculation of h_Rlay, uh_Rlay etc diagnostics

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#278]
These diagnostics use a density variable Rcv (src/diagnostics/MOM_diagnostics.F90:206) defined on h grid points to calculate weights, e.g passed to find_weights() at src/diagnostics/MOM_diagnostics.F90:398. It looks like since the diagnostics are on q points Rcv is being accessed beyond it's bounds in the symmetric memory case. 

Can someone please suggest the best way to fix this?

**Comment by Hallberg-NOAA** [comment]
I am testing a fix for this now, and should have it checked in tomorrow.

**Comment by Hallberg-NOAA** [comment]
This issue is closed by MOM6 commit MOM6 commit NOAA-GFDL/MOM6@7e13eb5a229f8b3e45c99697bc9d8fa93d25529a .
