### ISSUE TITLE
Floating divide by zero in cvmix intel compiler DEBUG build

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#297]
Link to failure in jenkins:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-single_column-BML,memory_type=dynamic/

Some error output:

forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
MOM6               000000000077D57D  cvmix_math_mp_cvm         198  cvmix_math.F90
MOM6               0000000000A5E534  cvmix_kpp_mp_cvmi        1342  cvmix_kpp.F90
MOM6               000000000073FEEC  mom_kpp_mp_kpp_ca         607  MOM_KPP.F90
MOM6               00000000031121C6  mom_diabatic_driv         570  MOM_diabatic_driver.F90
MOM6               0000000002D93105  mom_mp_step_mom_         1010  MOM.F90
MOM6               0000000001BA84F9  MAIN__                    426  MOM_driver.F90
MOM6               000000000040C41C  Unknown               Unknown  Unknown
libc.so.6          00002B43D815FD5D  Unknown               Unknown  Unknown
MOM6               000000000040C319  Unknown               Unknown  Unknown

**Comment by adcroft** [comment]
It is true that the solver has an possible divide by zero at [L198](https://github.com/CVMix/CVMix-src/blob/493d354f9bb3406a4db6b853787a7d944985912b/src/shared/cvmix_math.F90#L198). I would suggest a ticket on CVMix's page but before that, we should establish what the inputs are from MOM_KPP.F90. It is entirely possible we are calling cvmis_kpp on a land point, or such.

That said, there are bracketing algorithms for root finders to avoid getting hung-up on a local inflexion.

**Comment by nicjhan** [comment]
I ran this in the debugger and the inputs look normal. So yes, it's Newton's method getting stuck at the stationary point. The CVMix issue is here https://github.com/CVMix/CVMix-src/issues/65

**Comment by adcroft** [comment]
@nicjhan I'm adding a work around at the MOM level to avoid this situation in the CVmix root finder. This is only a work around and CVmix still needs to be made robust to vanished layers. The work around adjusts the coordinates passed to CVmix by inflating vanished layers.
