### ISSUE TITLE
Single column CVmix, BLM, KPP, EPBL don't exit cleanly when run with dynamic symmetric memory

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#300]
They crash with an error message like:

FATAL from PE     1: mpp_sync_self: size_recv does not match of data received
FATAL from PE     2: mpp_sync_self: size_recv does not match of data received
FATAL from PE     3: mpp_sync_self: size_recv does not match of data received

Do we want a user friendly message instead to indicate that this combination is not supported? 

Full run output here:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-single_column-EPBL,memory_type=dynamic_symmetric/

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-CVmix_SCM_tests-wind_only-EPBL,memory_type=dynamic_symmetric/15/console

**Comment by adcroft** [comment]
This is a test with a horizontal grid of only 2x2 points. In #290 there is discussion about whether halo updates for halos wider than the compute domain work or even make sense. At GFDL we have been testing these experiments with only 1 core. For now, I recommend reducing the core count to 1. It is an open issue whether we should support 1 point per core but if we did then we could presumably reduce the problem size from 2x2 to 1x1 (i.e. truly single column).

**Comment by nicjhan** [comment]
The test cases run on a single PE. Otherwise this is a duplicate of #298.
