### ISSUE TITLE
MESO_025_63L does not run or exit cleanly on dynamic symmetric memory

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#301]
Here is the error output:

FATAL from PE   245: fms_io(read_data_3d_new), field u in file INPUT/MESO_025_63L_IC.nc: field size mismatch  1441         450          63        1440         450          63

Full output: https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-MESO_025_63L,memory_type=dynamic_symmetric/15/console

**Comment by adcroft** [comment]
Question for @Hallberg-NOAA : Can we use non-symmetric restarts for a symmetric executable? Based on the errors messages here I suspect not. Should we?

**Comment by nicjhan** [comment]
I this we call this a user error.
