### ISSUE TITLE
Baltic test case has memory errors

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#304]
==3093== Conditional jump or move depends on uninitialised value(s)
==3093==    at 0x29761AC: sis_tracer_advect_mp_advect_tracer_ (SIS_tracer_advect.F90:317)
==3093==    by 0x295A6C1: sis_tracer_advect_mp_advect_sis_tracers_ (SIS_tracer_advect.F90:133)
==3093==    by 0x2F67DDC: ice_transport_mod_mp_ice_transport_ (ice_transport.F90:330)
==3093==    by 0x1894B79: ice_model_mod_mp_update_ice_model_slow_ (in /short/v45/nah599/jenkins/workspace/mom-ocean.org/MOM6_pretest_run/MOM6-examples/build/intel/ice_ocean_SIS2/DEBUG/dynamic/MOM6)
==3093==    by 0x1687FF9: ice_model_mod_mp_update_ice_model_slow_dn_ (ice_model.F90:139)
==3093==    by 0x1DB0E8D: MAIN__ (coupler_main.F90:875)

And

==3099== Conditional jump or move depends on uninitialised value(s)
==3099==    at 0x297AA7A: sis_tracer_advect_mp_advect_tracer_ (SIS_tracer_advect.F90:362)
==3099==    by 0x295A6C1: sis_tracer_advect_mp_advect_sis_tracers_ (SIS_tracer_advect.F90:133)
==3099==    by 0x2F67DDC: ice_transport_mod_mp_ice_transport_ (ice_transport.F90:330)
==3099==    by 0x1894B79: ice_model_mod_mp_update_ice_model_slow_ (in /short/v45/nah599/jenkins/workspace/mom-ocean.org/MOM6_pretest_run/MOM6-examples/build/intel/ice_ocean_SIS2/DEBUG/dynamic/MOM6)
==3099==    by 0x1687FF9: ice_model_mod_mp_update_ice_model_slow_dn_ (ice_model.F90:139)
==3099==    by 0x1DB0E8D: MAIN__ (coupler_main.F90:875)

And

==3099== Conditional jump or move depends on uninitialised value(s)
==3099==    at 0x29B8AB3: sis_tracer_advect_mp_advect_x_ (SIS_tracer_advect.F90:836)
==3099==    by 0x297A0AD: sis_tracer_advect_mp_advect_tracer_ (SIS_tracer_advect.F90:353)
==3099==    by 0x295A6C1: sis_tracer_advect_mp_advect_sis_tracers_ (SIS_tracer_advect.F90:133)
==3099==    by 0x2F67DDC: ice_transport_mod_mp_ice_transport_ (ice_transport.F90:330)
==3099==    by 0x1894B79: ice_model_mod_mp_update_ice_model_slow_ (in /short/v45/nah599/jenkins/workspace/mom-ocean.org/MOM6_pretest_run/MOM6-examples/build/intel/ice_ocean_SIS2/DEBUG/dynamic/MOM6)
==3099==    by 0x1687FF9: ice_model_mod_mp_update_ice_model_slow_dn_ (ice_model.F90:139)
==3099==    by 0x1DB0E8D: MAIN__ (coupler_main.F90:875)

And

==3101== Conditional jump or move depends on uninitialised value(s)
==3101==    at 0x2978E7A: sis_tracer_advect_mp_advect_tracer_ (SIS_tracer_advect.F90:331)
==3101==    by 0x295A6C1: sis_tracer_advect_mp_advect_sis_tracers_ (SIS_tracer_advect.F90:133)
==3101==    by 0x2F67DDC: ice_transport_mod_mp_ice_transport_ (ice_transport.F90:330)
==3101==    by 0x1894B79: ice_model_mod_mp_update_ice_model_slow_ (in /short/v45/nah599/jenkins/workspace/mom-ocean.org/MOM6_pretest_run/MOM6-examples/build/intel/ice_ocean_SIS2/DEBUG/dynamic/MOM6)
==3101==    by 0x1687FF9: ice_model_mod_mp_update_ice_model_slow_dn_ (ice_model.F90:139)
==3101==    by 0x1DB0E8D: MAIN__ (coupler_main.F90:875)

Full output:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_runtime_analyzer/analyzer=valgrind,build=DEBUG,compiler=intel,experiment=ice_ocean_SIS2-Baltic,memory_type=dynamic/37/console

**Comment by Hallberg-NOAA** [comment]
This is actually a SIS2 error, but a curious one in that it does not matter to the solutions whether the logical array in question is initalized to true or false!  This issue is addressed by  SIS2 commit NOAA-GFDL/SIS2@947eca6e24ce70ef1c707f9ff2eb0ac9692ce337
