### ISSUE TITLE
OM4_025 has quite a few memory errors

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#305]
Example error output:

==20795== Conditional jump or move depends on uninitialised value(s)
==20795==    at 0x2A05773: sis_tracer_advect_mp_advect_scalar_y_ (SIS_tracer_advect.F90:1216)
==20795==    by 0x299E7E3: sis_tracer_advect_mp_advect_scalar_ (SIS_tracer_advect.F90:608)
==20795==    by 0x2F67BBA: ice_transport_mod_mp_ice_transport_ (ice_transport.F90:326)
==20795==    by 0x1894B79: ice_model_mod_mp_update_ice_model_slow_ (in /short/v45/nah599/jenkins/workspace/mom-ocean.org/MOM6_pretest_run/MOM6-examples/build/intel/ice_ocean_SIS2/DEBUG/dynamic/MOM6)
==20795==    by 0x1687FF9: ice_model_mod_mp_update_ice_model_slow_dn_ (ice_model.F90:139)
==20795==    by 0x1DB0E8D: MAIN__ (coupler_main.F90:875)

Full run output:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_runtime_analyzer/analyzer=valgrind,build=DEBUG,compiler=intel,experiment=ice_ocean_SIS2-OM4_025,memory_type=dynamic/37/consoleFull

**Comment by Hallberg-NOAA** [comment]
This is actually a SIS2 error, but a curious one in that it does not matter to the solutions whether the logical array in question is initalized to true or false!  This issue is addressed by  SIS2 commit NOAA-GFDL/SIS2@947eca6e24ce70ef1c707f9ff2eb0ac9692ce337
