### ISSUE TITLE
Fails to compile on Mac (gnu)

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#307]
I have openmpi, but not the Gnu enhancements to sched.h, leading to:

mpif90 -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -D_FILE_VERSION="`//Users/kate/ESMG/ESMG-configs/src/mkmf/bin/git-version-string //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90`" -DSTATSLABEL=\"gnu\" -DMAXFIELDMETHODS_=500   -fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check -I/usr/local/include  -O2 -fbounds-check   -c -I//Users/kate/ESMG/ESMG-configs/src/FMS/include -I//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/include    //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90
//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:14:18: error: use of
      undeclared identifier '__NR_gettid'
  return syscall(__NR_gettid);
                 ^
//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:23:3: error: use of
      undeclared identifier 'cpu_set_t'
  cpu_set_t coremask;           /\* core affinity mask */
  ^
//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:3: warning: implicit
      declaration of function 'CPU_ZERO' is invalid in C99
      [-Wimplicit-function-declaration]
  CPU_ZERO(&coremask);
  ^
//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:13: error: use of
      undeclared identifier 'coremask'
  CPU_ZERO(&coremask);

This problem isn't new: https://groups.google.com/forum/#!topic/mom-users/0SnBZmOdOtc

Also, there's weirdness with the Mac sed/awk options, so I did this instead:

diff --git a/bin/list_paths b/bin/list_paths
index c19746c..d6890ed 100755
--- a/bin/list_paths
+++ b/bin/list_paths
@@ -68,7 +68,8 @@ find $\* -type f \
  -o -name *.inc \
  ) -print >> $src

-sed 's:._/(._):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk '{print $2}' > $out
+#sed 's:._/(._):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk '{print $2}' > $out
+cat $src > $out
 echo "A list of the files you checked out is in the file $out ..."

 touch $doc     # create the file if it doesn't exist

**Comment by jkrasting** [comment]
I was successful compiling MOM6 on Mac about a year ago, but I was unable
to run any of the examples - including the single column - due to stack
size limits that are unable to be overriden in the OS.  I'm excited to see
if you are able to get it to run.

On Thursday, May 26, 2016, Kate Hedstrom <notifications@github.com> wrote:

> I have openmpi, but not the Gnu enhancements to sched.h, leading to:
>
> mpif90 -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO
> -D_FILE_VERSION="//Users/kate/ESMG/ESMG-configs/src/mkmf/bin/git-version-string
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90" -DSTATSLABEL=\"gnu\"
> -DMAXFIELDMETHODS_=500 -fcray-pointer -fdefault-double-8 -fdefault-real-8
> -Waliasing -ffree-line-length-none -fno-range-check -I/usr/local/include
> -O2 -fbounds-check -c -I//Users/kate/ESMG/ESMG-configs/src/FMS/include
> -I//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/include
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:14:18: error: use of
> undeclared identifier '__NR_gettid'
> return syscall(__NR_gettid);
> ^
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:23:3: error: use of
> undeclared identifier 'cpu_set_t'
> cpu_set_t coremask; /* core affinity mask */
> ^
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:3: warning:
> implicit
> declaration of function 'CPU_ZERO' is invalid in C99
> [-Wimplicit-function-declaration]
> CPU_ZERO(&coremask);
> ^
> //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:13: error: use of
> undeclared identifier 'coremask'
> CPU_ZERO(&coremask);
>
> This problem isn't new:
> https://groups.google.com/forum/#!topic/mom-users/0SnBZmOdOtc
>
> Also, there's weirdness with the Mac sed/awk options, so I did this
> instead:
>
> diff --git a/bin/list_paths b/bin/list_paths
> index c19746c..d6890ed 100755
> --- a/bin/list_paths
> +++ b/bin/list_paths
> @@ -68,7 +68,8 @@ find $* -type f \
> -o -name *.inc \
> ) -print >> $src
>
> -sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> '{print $2}' > $out
> +#sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> '{print $2}' > $out
> +cat $src > $out
> echo "A list of the files you checked out is in the file $out ..."
>
> touch $doc # create the file if it doesn't exist
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/307>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGSgcxKoazz6WiCGEE7HARyrK_nuUvqnks5qFiuRgaJpZM4IoCyt>
> .
>


-- 
-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by kshedstrom** [comment]
Gosh, I see what you mean:

Kates-MacBook-Pro:ESMG kate$ ulimit -s unlimited
-bash: ulimit: stack size: cannot modify limit: Operation not permitted
Kates-MacBook-Pro:ESMG kate$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

How unfortunate - it's a brand new system too!

**Comment by jkrasting** [comment]
I think there are compiler flags that can override it, but I have little
experience with them.  I wasn't successful in my tests.

On Thursday, May 26, 2016, Kate Hedstrom <notifications@github.com> wrote:

> Gosh, I see what you mean:
>
> Kates-MacBook-Pro:ESMG kate$ ulimit -s unlimited
> -bash: ulimit: stack size: cannot modify limit: Operation not permitted
> Kates-MacBook-Pro:ESMG kate$ ulimit -a
> core file size (blocks, -c) 0
> data seg size (kbytes, -d) unlimited
> file size (blocks, -f) unlimited
> max locked memory (kbytes, -l) unlimited
> max memory size (kbytes, -m) unlimited
> open files (-n) 256
> pipe size (512 bytes, -p) 1
> stack size (kbytes, -s) 8192
> cpu time (seconds, -t) unlimited
> max user processes (-u) 709
> virtual memory (kbytes, -v) unlimited
>
> How unfortunate - it's a brand new system too!
>
> On Thu, May 26, 2016 at 3:30 PM, John Krasting <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I was successful compiling MOM6 on Mac about a year ago, but I was unable
> > to run any of the examples - including the single column - due to stack
> > size limits that are unable to be overriden in the OS. I'm excited to see
> > if you are able to get it to run.
> >
> > On Thursday, May 26, 2016, Kate Hedstrom <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I have openmpi, but not the Gnu enhancements to sched.h, leading to:
> > >
> > > mpif90 -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO
> > >
> >
> -D_FILE_VERSION="//Users/kate/ESMG/ESMG-configs/src/mkmf/bin/git-version-string
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90"
> -DSTATSLABEL=\"gnu\"
> > > -DMAXFIELDMETHODS_=500 -fcray-pointer -fdefault-double-8
> -fdefault-real-8
> > > -Waliasing -ffree-line-length-none -fno-range-check
> -I/usr/local/include
> > > -O2 -fbounds-check -c -I//Users/kate/ESMG/ESMG-configs/src/FMS/include
> > > -I//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/include
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:14:18: error: use
> > of
> > > undeclared identifier '__NR_gettid'
> > > return syscall(__NR_gettid);
> > > ^
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:23:3: error: use
> of
> > > undeclared identifier 'cpu_set_t'
> > > cpu_set_t coremask; /* core affinity mask */
> > > ^
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:3: warning:
> > > implicit
> > > declaration of function 'CPU_ZERO' is invalid in C99
> > > [-Wimplicit-function-declaration]
> > > CPU_ZERO(&coremask);
> > > ^
> > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:13: error: use
> > of
> > > undeclared identifier 'coremask'
> > > CPU_ZERO(&coremask);
> > >
> > > This problem isn't new:
> > > https://groups.google.com/forum/#!topic/mom-users/0SnBZmOdOtc
> > >
> > > Also, there's weirdness with the Mac sed/awk options, so I did this
> > > instead:
> > >
> > > diff --git a/bin/list_paths b/bin/list_paths
> > > index c19746c..d6890ed 100755
> > > --- a/bin/list_paths
> > > +++ b/bin/list_paths
> > > @@ -68,7 +68,8 @@ find $* -type f \
> > > -o -name *.inc \
> > > ) -print >> $src
> > >
> > > -sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> > > '{print $2}' > $out
> > > +#sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> > > '{print $2}' > $out
> > > +cat $src > $out
> > > echo "A list of the files you checked out is in the file $out ..."
> > >
> > > touch $doc # create the file if it doesn't exist
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/NOAA-GFDL/MOM6/issues/307>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AGSgcxKoazz6WiCGEE7HARyrK_nuUvqnks5qFiuRgaJpZM4IoCyt
> > >
> > > .
> > >
> >
> >
> > --
> > -----
> > Dr. John Krasting, Physical Scientist
> > NOAA/Geophysical Fluid Dynamics Laboratory
> > Biogeochemistry, Ecosystems, and Climate Group
> > 201 Forrestal Road, Princeton, NJ 08540
> > P. (609) 452-5359 | F. (609) 987-5063
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/NOAA-GFDL/MOM6/issues/307#issuecomment-222023528>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAbIHphe6cqsM2PgWkaweHHP9NrFP2Msks5qFi0OgaJpZM4IoCyt
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/307#issuecomment-222025538>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGSgc_G2XB_9p8E2PlceycQLDeIu-FU7ks5qFjBwgaJpZM4IoCyt>
> .
>


-- 
-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by underwoo** [comment]
Not sure if the following link options will work, but they are supposed to
increase the stack size to 1GB for the application. Please add
"-Wl,-stack_size,0x40000000,-stack_addr,0xf0000000"
to the LDFLAGS make macro and relink the application.

On Thursday, May 26, 2016, John Krasting <notifications@github.com> wrote:

> I think there are compiler flags that can override it, but I have little
> experience with them. I wasn't successful in my tests.
>
> On Thursday, May 26, 2016, Kate Hedstrom <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Gosh, I see what you mean:
> >
> > Kates-MacBook-Pro:ESMG kate$ ulimit -s unlimited
> > -bash: ulimit: stack size: cannot modify limit: Operation not permitted
> > Kates-MacBook-Pro:ESMG kate$ ulimit -a
> > core file size (blocks, -c) 0
> > data seg size (kbytes, -d) unlimited
> > file size (blocks, -f) unlimited
> > max locked memory (kbytes, -l) unlimited
> > max memory size (kbytes, -m) unlimited
> > open files (-n) 256
> > pipe size (512 bytes, -p) 1
> > stack size (kbytes, -s) 8192
> > cpu time (seconds, -t) unlimited
> > max user processes (-u) 709
> > virtual memory (kbytes, -v) unlimited
> >
> > How unfortunate - it's a brand new system too!
> >
> > On Thu, May 26, 2016 at 3:30 PM, John Krasting <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > wrote:
> >
> > > I was successful compiling MOM6 on Mac about a year ago, but I was
> unable
> > > to run any of the examples - including the single column - due to stack
> > > size limits that are unable to be overriden in the OS. I'm excited to
> see
> > > if you are able to get it to run.
> > >
> > > On Thursday, May 26, 2016, Kate Hedstrom <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > I have openmpi, but not the Gnu enhancements to sched.h, leading to:
> > > >
> > > > mpif90 -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO
> > > >
> > >
> >
> -D_FILE_VERSION="//Users/kate/ESMG/ESMG-configs/src/mkmf/bin/git-version-string
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90"
> > -DSTATSLABEL=\"gnu\"
> > > > -DMAXFIELDMETHODS_=500 -fcray-pointer -fdefault-double-8
> > -fdefault-real-8
> > > > -Waliasing -ffree-line-length-none -fno-range-check
> > -I/usr/local/include
> > > > -O2 -fbounds-check -c
> -I//Users/kate/ESMG/ESMG-configs/src/FMS/include
> > > > -I//Users/kate/ESMG/ESMG-configs/src/FMS/mpp/include
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/mpp.F90
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:14:18: error:
> use
> > > of
> > > > undeclared identifier '__NR_gettid'
> > > > return syscall(__NR_gettid);
> > > > ^
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:23:3: error:
> use
> > of
> > > > undeclared identifier 'cpu_set_t'
> > > > cpu_set_t coremask; /* core affinity mask */
> > > > ^
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:3: warning:
> > > > implicit
> > > > declaration of function 'CPU_ZERO' is invalid in C99
> > > > [-Wimplicit-function-declaration]
> > > > CPU_ZERO(&coremask);
> > > > ^
> > > > //Users/kate/ESMG/ESMG-configs/src/FMS/mpp/affinity.c:25:13: error:
> use
> > > of
> > > > undeclared identifier 'coremask'
> > > > CPU_ZERO(&coremask);
> > > >
> > > > This problem isn't new:
> > > > https://groups.google.com/forum/#!topic/mom-users/0SnBZmOdOtc
> > > >
> > > > Also, there's weirdness with the Mac sed/awk options, so I did this
> > > > instead:
> > > >
> > > > diff --git a/bin/list_paths b/bin/list_paths
> > > > index c19746c..d6890ed 100755
> > > > --- a/bin/list_paths
> > > > +++ b/bin/list_paths
> > > > @@ -68,7 +68,8 @@ find $* -type f \
> > > > -o -name *.inc \
> > > > ) -print >> $src
> > > >
> > > > -sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> > > > '{print $2}' > $out
> > > > +#sed 's:.*/(.*):\0 \1:' $src | nl | sort --key 3 -u | sort -n | awk
> > > > '{print $2}' > $out
> > > > +cat $src > $out
> > > > echo "A list of the files you checked out is in the file $out ..."
> > > >
> > > > touch $doc # create the file if it doesn't exist
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/NOAA-GFDL/MOM6/issues/307>, or mute the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/AGSgcxKoazz6WiCGEE7HARyrK_nuUvqnks5qFiuRgaJpZM4IoCyt
> > > >
> > > > .
> > > >
> > >
> > >
> > > --
> > > -----
> > > Dr. John Krasting, Physical Scientist
> > > NOAA/Geophysical Fluid Dynamics Laboratory
> > > Biogeochemistry, Ecosystems, and Climate Group
> > > 201 Forrestal Road, Princeton, NJ 08540
> > > P. (609) 452-5359 | F. (609) 987-5063
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/NOAA-GFDL/MOM6/issues/307#issuecomment-222023528>,
> > or mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAbIHphe6cqsM2PgWkaweHHP9NrFP2Msks5qFi0OgaJpZM4IoCyt
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/NOAA-GFDL/MOM6/issues/307#issuecomment-222025538>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AGSgc_G2XB_9p8E2PlceycQLDeIu-FU7ks5qFjBwgaJpZM4IoCyt
> >
> > .
> >
>
>
> --
> -----
> Dr. John Krasting, Physical Scientist
> NOAA/Geophysical Fluid Dynamics Laboratory
> Biogeochemistry, Ecosystems, and Climate Group
> 201 Forrestal Road, Princeton, NJ 08540
> P. (609) 452-5359 | F. (609) 987-5063
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/307#issuecomment-222029820>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAaaSzKsUPvnFuntNYFlj-5EVqipRDQkks5qFjgigaJpZM4IoCyt>
> .
>


-- 
--
Seth Underwood

Modeling Systems Group
GFDL/NOAA/DOC
201 Forrestal Road
Princeton, NJ 08540-6649

(609) 452-5847 Office
(304) 376-9002 Cell
(609) 987-5063 Fax
Seth.Underwood@noaa.gov

**Comment by marshallward** [comment]
This looks like an FMS issue, and we also have more recent builds running on Macs, so will close for now.  (But reopen if it's still a problem).
