### ISSUE TITLE
read_netCDF_data leads to cryptic model failure when rescale value argument is not 1

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#333]
Calls to `read_netCDF_data()` are failing for some fields when the value of the rescale optional argument is not 1.  The error messages that are returned are a cryptic warning about invalid memory in the call to `handle%close()` at about line 2109 of `MOM_io.F90`, but I suspect that this the result of a segmentation fault earlier in `read_netCDF_data_2d()`.

**Comment by marshallward** [comment]
Can you show the fields or lines where this is happening?

**Comment by marshallward** [comment]
Is it in tidal mixing?

https://github.com/NOAA-GFDL/MOM6/blob/ceb4c9286df597a89977973b1f300ba1303765ee/src/parameterizations/vertical/MOM_tidal_mixing.F90#L510-L511

https://github.com/NOAA-GFDL/MOM6/blob/ceb4c9286df597a89977973b1f300ba1303765ee/src/parameterizations/vertical/MOM_tidal_mixing.F90#L525-L526

**Comment by Hallberg-NOAA** [comment]
Yes, these are the variables, but I have a pending fix for this bug.
