### ISSUE TITLE
Diagnostic output 

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#334]
Presently the user can request that a diagnostic output on z-star vertical coords through the diag table. MOM6 regrids the output during the post() call. This issue will extend this functionality to support support both isopycnal (rho) and terrain following (sigma) coordinates. 

It may also make sense to do code cleanup / refactoring of the diagnostic vertical regridding code. Perhaps this can be split into a separate file, e.g. src/framework/MOM_diag_regrid.F90 

This issue will be tested here: https://github.com/NOAA-GFDL/MOM6-examples/issues/98

**Comment by Hallberg-NOAA** [comment]
This capability has been implemented.
