### ISSUE TITLE
cannot override #define variables in memory.h by cpp inputs

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#342]
# define variables ( e.g., MAX_FIELDS_)  in memory.h cannot be overwritten at compile time by a cpp input (i.e., -DMAX_FIELDS_=60) .

This makes the user manually change the file before compile to increase this parameter.

This could be fixed by a simple modification of the file config_src/dynamic/ memory.h

+#ifndef MAX_FIELDS_
 #define MAX_FIELDS_ 50
+#endif

I can make a pull request for this mod if there is no objection.

**Comment by jkrasting** [comment]
See commit a704164 which includes this modification.

**Comment by nikizadehgfdl** [comment]
This is resolved as suggested.
