### ISSUE TITLE
Better way to configure vertical axes for diagnostic regridding 

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#355]
Presently it's necessary to have separate lines like:

DIAG_REMAP_<vertical coord>_GRID_DEF for each of Z, RHO2, RHO0, SIGMA. It would be good to find a more succinct way to specify this. If only to make it clear that all possible vertical coords can be specified with a single 'section' within the configuration file.

Alistair commented: 

"""
As we grow the list of coordinates I would like to avoid the list of input parameters growing unintentionally too.
Alternative to limiting the list, we could add a run-time parameter "NUM_DIAG_COOD" and use numbers in the coordinate parameters, DIAG_COORD_1="RHO2", DIAG_REMAP_GRID_DEF_1="FILE:..."? 
"""

**Comment by adcroft** [comment]
I just had a meeting with the bio-geochemists concerning CMIP6 diagnostics. It looks like we'll be needed multiple _z grids which breaks the current assumption of naming the diagnostics module after the coordinate. So we'll need to move reconsidering how we control the diagnostic coordinates up the todo list.

Here's a possible example use case where we specify the module name too:
> NUM_DIAG_COORDS = 3
> DIAG_COORD_01 = "Z*"                             ! Coordinate mode
> DIAG_COORD_LABEL_01 = "_z"                ! Used for module name
> DIAG_COORD_GRID_DEF_01 = "FILE:woa05_grid.nc,dz"
> DIAG_COORD_02= "Z*"
> DIAG_COORD_LABEL_02 = "_z2"
> DIAG_COORD_GRID_DEF_02 = "FNC2:1500,20"
> DIAG_COORD_03 = "RHO2"
> DIAG_COORD_LABEL_03 = "_rho2"
> DIAG_COORD_GRID_DEF_03 = "FILE:hycom1_40a.nc,sigma2"

or:
> NUM_DIAG_COORDS = 3
> DIAG_COORD_01 = "Z*,_z"                ! Coordinate mode and module name together
> DIAG_COORD_GRID_DEF_01 = "FILE:woa05_grid.nc,dz"
> DIAG_COORD_02= "Z*,_z2"
> DIAG_COORD_GRID_DEF_02 = "FNC2:1500,20"
> DIAG_COORD_03 = "RHO2,_rho2"
> DIAG_COORD_GRID_DEF_03 = "FILE:hycom1_40a.nc,sigma2"

We can start on this issue only after #348 is pulled in.

**Comment by MJHarrison-GFDL** [comment]
second option would be my preference. In the same vein, how about:

NUM_DIAG_COORDS = 3
DIAG_COORD_01 = "Z,_z,FILE:woa05_grid.nc,dz" ! Coordinate mode and module name together
DIAG_COORD_02= "Z,_z2,FNC2:1500,20"
DIAG_COORD_03 = "RHO2,_rho2,FILE:hycom1_40a.nc,sigma2"

**Comment by adcroft** [comment]
I also like to make things succinct but a good reason for keeping the
GRID_SPEC parameters separate is we can then reuse the code that the model
uses to interpret the model-coordinate parameters.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by Hallberg-NOAA** [comment]
This has been implemented.
