### ISSUE TITLE
Typo in MOM_grid.F90

### ISSUE THREAD

**Issue by suyashbire1** [NOAA-GFDL/MOM6#363]
Fails to compile because of a missing `&` in MOM_grid.F90 on line [150](https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/core/MOM_grid.F90#L150).

**Comment by Hallberg-NOAA** [comment]
Thanks for pointing this one out, Suyash!

 We just fixed this and checked in the corrected code with commit https://github.com/NOAA-GFDL/MOM6/commit/f2ab14702c4fd67c8da2dfbdb5d7a53c1a3470e3
