### ISSUE TITLE
Stack variable ssh has uninitialized parts before pass_var

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#371]
MOM_diag_to_Z.F90:229 ssh halos are filled in but only compute domain is initialized. mpp_update_domains uses size() and passes the whole array. When the MPI payload is checked by Valgrind it notices and throws errors (link below). 

We've had this problem before by I'm not sure / can't remember what the best fix is, possibilities:

1. Explicitly Initialize stack variable with a missing value 
2. Let compiler initialize stack variables (not as good as above in my opinion, different compilers do different things). 
3. mpp_update_domains only passes valid part of array
4. mpp_update_domains initializes halos before passing array, these will get overwritten on the other end

error link:
https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_runtime_analyzer/

**Comment by mjharriso** [comment]
Option 1.  

3. is correct: mpp_update_domains only touches valid points and does not initialize halos.

**Comment by MJHarrison-GFDL** [comment]
Nic, I meant to say that statement 3 is correct (mpp_update_domains only touches valid points and does not initialize halos) and option 1 is the best fix.

**Comment by nicjhan** [comment]
Thanks @MJHarrison-GFDL

**Comment by nicjhan** [comment]
This turns out not to be a problem with halos. As Matt mentions mpp_update_domains doesn't touch these. The data itself is uninitialized, see:

https://github.com/NOAA-GFDL/MOM6/issues/376
