### ISSUE TITLE
More flexibility when writing restart files

### ISSUE THREAD

**Issue by cspencerjones** [NOAA-GFDL/MOM6#372]
At the moment, [`save_restart`](https://github.com/NOAA-GFDL/MOM6/blob/debe45e732825c8fdd181081ddc320f24627b0ce/src/framework/MOM_restart.F90#L1279) is called directly by the drivers, e.g. [here](https://github.com/NOAA-GFDL/MOM6/blob/debe45e732825c8fdd181081ddc320f24627b0ce/config_src/drivers/solo_driver/MOM_driver.F90#L563-L583). I would like to option to save non-standard restart files that contain particle locations, but I cannot currently do so without writing new code in all of the drivers (which doesn't seem ideal). 

I would like it if the driver could call a  new subroutine that we could add to `MOM.F90`, and that subroutine could call `save_restart`. Then any extra steps in the save_restart process could be added only in one place in the code. This would help me directly, but is also likely to help others who might want to add to the code in the future. 

I talked to @adcroft about this several months ago. He seemed to be on board with the idea. I am posting here to create a paper trail and to start a discussion on whether/how to make this happen.

**Comment by marshallward** [comment]
I believe this has been addressed; we now have a clear space for generalizing restarts.
