### ISSUE TITLE
iceberg diags call register but not post

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#381]
This could be undesirable because:

1. the registration was unnecessary
2. the available_diags file ends up being wrong so user doesn't know what's available
3. we can't test which diags can/should be written for a given config. 

ocean_model_area_berg.nc
ocean_model_frac_ice_cover.nc
ocean_model_heat_added.nc 
ocean_model_mass_berg.nc 
ocean_model_ustar_berg.nc 
ocean_model_ustar_ice_cover.nc

In fact all of the forcing diagnostics are registered and posted under different conditions so potentially have this problem.

This is hard to fix:

1. the forcing diags should only be registered if the forcing exists
2. the forcing is only known to exist after a call to convert_IOB_to_fluxes - forcing arrays are allocated on-the-fly rather than before the model starts. 
3. the above happens within the update_ocean_model subroutine. 
4. therefore presently diag registration can only happen once the timestepping has started, not during init.

**Comment by nicjhan** [comment]
I propose doing the registration just before the posting.

**Comment by adcroft** [comment]
I spent a good part of yesterday trying P/R #382 and looking at this issue. It certainly is a hard problem. Conditional registering of diagnostic based on whether another component in the coupled system associated an array seems undoable. One option @Hallberg-NOAA suggested is we post missing_values. Another is to bracket the registration with a run-time parameter. Both of these are workarounds. The best solution, which I do not think is reachable without a lot of coordination, is to redesign the coupled-model initialization. I guess we'll be using one of the other workarounds.

**Comment by nicjhan** [comment]
@adcroft thanks for this, it seems I'd turned off my test that checks for lost diags.  I've marked heat_added as 'unfinished' (i.e. registered but not posted) in the tests because it suffers from the same problem as above. At some point I'll address these unfinished diags as a separate issue and we can reopen the conversation then.
