### ISSUE TITLE
Kd_interface diagnostic incomplete in newer diabatic_ALE

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#398]
The Kd_interface diagnostic in diabatic_ALE is a copy of Kd_heat before the double diffusion contribution, but also before the ePBL contribution. One could instead have it be Kd_heat minus KT_extra at the end, or just note that Kd_interface isn't what one should be asking for.

**Comment by Hallberg-NOAA** [comment]
This issue was corrected by PR #635.
