### ISSUE TITLE
Diagnostic of conservative temperature tendancy

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#404]
To parallel the tendency of potential temperature but using the TEOS-10 conservative temperature, as requested in OMIP6 table L1.

**Comment by Hallberg-NOAA** [comment]
@StephenGriffies feels that the community has yet to come to a consensus on how to deal with conservative temperature when this is not the model's actual state variable. This issue can be reopened if necessary when a clearer community consensus emerges.
