### ISSUE TITLE
SEGV in fms_init() (called from MOM_infra_init) on NCI's Raijin

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#409]
Build [56](https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ocean_only-nonBous_global,memory_type=dynamic/lastBuild/consoleFull) has SEGV during initialization when running nonBous_global with the dynamic+debug Intel executable.

All other experiments with this executable seem to have worked. This passed in build 55 and there have not been any obvious code changes in the infrastructure there.

**Comment by nicjhan** [comment]
ocean_only-MESO_025_23L also has a segfault. The valgrind run (running now) may reveal something.

**Comment by adcroft** [comment]
I see we have green lights on Raijin again. Was a fix used or was the original problem a system glitch?

**Comment by nicjhan** [comment]
I think so, especially since valgrind didn't find anything. Strange ...

**Comment by adcroft** [comment]
Cosmic ray.
