### ISSUE TITLE
Updating halos of tracer fields

### ISSUE THREAD

**Issue by suyashbire1** [NOAA-GFDL/MOM6#411]
I have written a subroutine to output diagnostics for thickness-weighted averaged momentum budget, using the template for `calculate_energy_diagnostics` in `MOM_diagnostics.F90`. Most of the output is working as expected except at the tile boundaries.

For example, `epfu` and `epfv` are calculated as follows:

```fortran
  if (ASSOCIATED(CS%e_Cu) .OR. ASSOCIATED(CS%epfu)) then
    do k=1,nz
      do j=js,je ; do I=Isq,Ieq
        CS%e_Cu(I,j,k) = 0.25*(CS%e(i,j,k)+CS%e(i+1,j,k)+&
          CS%e(i,j,k+1)+CS%e(i+1,j,k+1))*ishqlarge(I,J,k)
        CS%epfu(I,j,k) = ADp%PFu(I,j,k)*CS%e_Cu(I,j,k)
      enddo ; enddo
    enddo
    if (CS%id_e_Cu > 0) call post_data(CS%id_e_Cu, CS%e_Cu, CS%diag)
    if (CS%id_epfu > 0) call post_data(CS%id_epfu, CS%epfu, CS%diag)
  endif

  if (ASSOCIATED(CS%e_Cv) .OR. ASSOCIATED(CS%epfv)) then
    do k=1,nz
      do J=Jsq,Jeq ; do i=is,ie
        CS%e_Cv(i,J,k) = 0.25*(CS%e(i,j,k)+CS%e(i,j+1,k)+&
          CS%e(i,j,k+1)+CS%e(i,j+1,k+1))*ishqlarge(I,J,k)
        CS%epfv(i,J,k) = ADp%PFv(i,J,k)*CS%e_Cv(i,J,k)
      enddo ; enddo
    enddo
    if (CS%id_e_Cv > 0) call post_data(CS%id_e_Cv, CS%e_Cv, CS%diag)
    if (CS%id_epfv > 0) call post_data(CS%id_epfv, CS%epfv, CS%diag)
  endif
```
Without updating the halos, I get the vertical strips at tile boundaries.

![epfu](https://cloud.githubusercontent.com/assets/13039369/22254930/edbfe7b8-e223-11e6-87fe-385e85ab487a.png)
![epfv](https://cloud.githubusercontent.com/assets/13039369/22254931/edca5310-e223-11e6-8452-3d1f9ddce123.png)

I believe I need to use `create_group_pass, do_group_pass/start_group_pass`. But I don't understand them at all. Is this the correct way to do this?

```Fortran
  if(.not.G%symmetric) then 
    if(ASSOCIATED(CS%e_Cu) .OR. ASSOCIATED(CS%e_Cv) .OR. &
       ASSOCIATED(CS%epfu) .OR. ASSOCIATED(CS%epfv)) then 
        call create_group_pass(CS%pass_e_uv, CS%e, G%Domain)
        call do_group_pass(CS%pass_e_uv, G%domain)
    endif
    if(ASSOCIATED(CS%hw_Cu) .OR. ASSOCIATED(CS%hw_Cv) .OR. &
       ASSOCIATED(CS%hwb_Cu) .OR. ASSOCIATED(CS%hwb_Cv) .OR. &
       ASSOCIATED(CS%huwb) .OR. ASSOCIATED(CS%hvwb)) then 
        call create_group_pass(CS%pass_w_uv, CDp%diapyc_vel, G%Domain)
        call do_group_pass(CS%pass_w_uv, G%domain)
  endif
```

**Comment by Zhi-Liang** [comment]
Hi Suyash,

   The call looks fine to me. Is pass_e_uv a new variable in CS? I just
want to make sure the change will not affect existed code. For performance
purpose, I suggest the following change.

if(.not.G%symmetric) then
    if(ASSOCIATED(CS%e_Cu) .OR. ASSOCIATED(CS%e_Cv) .OR. &
       ASSOCIATED(CS%epfu) .OR. ASSOCIATED(CS%epfv)) then
        call create_group_pass(CS%pass_e_diapyc_vel, CS%e, G%Domain)
    endifdiapyc_vel
    if(ASSOCIATED(CS%hw_Cu) .OR. ASSOCIATED(CS%hw_Cv) .OR. &
       ASSOCIATED(CS%hwb_Cu) .OR. ASSOCIATED(CS%hwb_Cv) .OR. &
       ASSOCIATED(CS%huwb) .OR. ASSOCIATED(CS%hvwb)) then
        call create_group_pass(CS%pass_e_diapyc_vel, CDp%diapyc_vel,
G%Domain)
  endif
  if(mpp_group_update_is_set(CS%pass_e_diapyc_ve) )
call do_group_pass(CS%pass_e_diapyc_vel, G%domain)

Greetings,

Zhi

**Comment by suyashbire1** [comment]
Hi Zhi,

Thank you for the qiuck reply. Yes, `pass_e_uv` is a new variable. Let me try what you have suggested.

Suyash

**Comment by suyashbire1** [comment]
HI Zhi,

Yes, your suggestion did the trick. Thank you! I'll close this issue now.

![epfu_hu](https://cloud.githubusercontent.com/assets/13039369/22300701/4b63f922-e2f6-11e6-8ae7-f0f34b62ffdc.png)
![epfv_hu](https://cloud.githubusercontent.com/assets/13039369/22300724/5ebed352-e2f6-11e6-8960-b36f64b0a6eb.png)
