### ISSUE TITLE
Bug in shortwave absorption remapped diagnostics

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [NOAA-GFDL/MOM6#423]
The remapped SW absorption profile diagnostic (rsdoabsorb) is incorrect. This can be demonstrated using single column runs comparing native grid vs remapped fields. The remapped diagnostic is not conservative and exhibits subsurface maxima which are not evident in the native output which has the correct exponential decay.

**Comment by MJHarrison-GFDL** [comment]
rsdoabsorb is an extensive variable (W m-2) , so it should not be re-mapped.

**Comment by mjharriso** [comment]
Closed by commit 2cd58d8

**Comment by MJHarrison-GFDL** [comment]
Closed by commit 2cd58d8
