### ISSUE TITLE
Coupled test cases will not run within an ensemble

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#431]
The Baltic test case crashes when run within a 2 member ensemble. The crash is not reproducible - three different error messages have been seen:

1. 

At line 917 of file ../../../../src/FMS/exchange/xgrid.F90
Fortran runtime error: Index '1' of dimension 1 of array 'recv_buffer' above upper bound of -349700976

2. 

FATAL from PE     1: mpp_sync_self: size_recv does not match of data received

3. 

NOTE from PE     1: xgrid_mod: reading exchange grid information from mosaic grid file
Operating system error: Cannot allocate memory
Allocation would exceed memory limit

**Comment by nicjhan** [comment]
It seems that mpp_set_current_pelist() does not work if size(pelist) == 1. So, for example, a two member ensemble on 2 cpus is not supported.

**Comment by nicjhan** [comment]
This PR solves the issue https://github.com/NOAA-GFDL/FMS/pull/29

**Comment by Hallberg-NOAA** [comment]
The rotational tests have been functionally addressed by the .testing capabilities.  Also, recent tests show that the ice-ocean models are running successfully with ensembles.
