### ISSUE TITLE
tracer_flow_control_end is neither public nor called from anywhere

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#471]
Do you want to call it? From where?

**Comment by adcroft** [comment]
Now I believe you! :wink:

https://codecov.io/gh/NOAA-GFDL/MOM6/src/a3778b73c1fb69f9aac7191a3c7f56ad3c421fec/src/tracer/MOM_tracer_flow_control.F90#L730...749

**Comment by kshedstrom** [comment]
The fix is simple and doesn't appear to break anything . See pull request
#475. 😄

**Comment by adcroft** [comment]
Closed by 6ae82c00b1d
