### ISSUE TITLE
Non-reproducible trigonometric functions in viscous BBL

### ISSUE THREAD

**Issue by marshallward** [NOAA-GFDL/MOM6#483]
There are trigonometric functions in the calculation of the bottom boundary layer viscosity, `set_viscous_BBL()`, of the form `cos(acos(x)/3 - 2*pi/3)`.

These functions may to be responsible for an answer change when transitioning from an Intel to AMD processor:

```
@@ -298,11 +298,11 @@
 h-point: mean=   2.5651029259221975E+01 min=   0.0000000000000000E+00 max=   4.0983512515433851E+01 Start set_viscous_BBL S
 h-point: c= 937092751 sw= 934896663 se= 934896663 nw= 939288839 ne= 939288839 Start set_viscous_BBL S
 u-point: mean=   4.7372083769301478E-07 min=   0.0000000000000000E+00 max=   5.1746049326678756E-02 u Ray [uv]
-u-point: c= 575868012 u Ray [uv]
+u-point: c= 575868009 u Ray [uv]
 v-point: mean=   4.5227642461442761E-07 min=   0.0000000000000000E+00 max=   1.1190647973926611E-02 v Ray [uv]
-v-point: c= 574147674 v Ray [uv]
+v-point: c= 574147672 v Ray [uv]
 u-point: mean=   9.2146868327139069E-04 min=   0.0000000000000000E+00 max=   1.5000000000000007E-03 u kv_bbl_[uv]
```

Compilers were identical across machines.  AFAIK, Intel does not use the C math library to compute these functions.

`CHANNEL_DRAG = False` restores answers, hinting that these functions may be responsible for the change in answers.  In any case, they are recognized as a potential source of answer changes.

We may want to consider replacing these expressions with a bit-reproducible approximation.

Snippet containing the lines is shown below.

https://github.com/NOAA-GFDL/MOM6/blob/25b57f475adc648e2f69abb59a6ff875b59063e3/src/parameterizations/vertical/MOM_set_viscosity.F90#L939-L963

**Comment by Hallberg-NOAA** [comment]
This code is directly solving for the root of a cubic equation using trigonometric functions.  These roots are well bracketed and well-behaved, so we could replace this code snippet with an iterative Newton's method solver that should of comparable cost and accuracy, but we would need to preserve this code wrapped in an answer-date flag because it has been used for several years in published solutions.

**Comment by Hallberg-NOAA** [comment]
The new options for solving the cubic equations for the open face lengths that were introduced with https://github.com/NOAA-GFDL/MOM6/pull/543 allow the user to avoid using these trigonometric functions by setting TRIG_CHANNEL_DRAG_WIDTHS.  The fact that the new options are both more accurate and more efficient should be motivation for them to be used routinely, but the existing solver that uses trigonometric functions does need to be retained to avoid changing answers for existing solutions.  This issue has been as thoroughly addressed as it can be, so it should now be closed.
