### ISSUE TITLE
High resolution MOM6 in ensemble mode mis-labels restart file

### ISSUE THREAD

**Issue by wfcooke** [NOAA-GFDL/MOM6#485]
When using ensembles with higher resolution MOM6 the restart files that are output are mislabeled.

./MOM.res.ens_01.ens_01_1.nc
./MOM.res.ens_01.ens_01.ens_01_2.nc
./MOM.res.ens_01.ens_01.ens_01.ens_01_3.nc
./MOM.res.ens_01.nc
./MOM.res.ens_02.ens_02_1.nc
./MOM.res.ens_02.ens_02.ens_02_2.nc
./MOM.res.ens_02.ens_02.ens_02.ens_02_3.nc
./MOM.res.ens_02.nc

while I would expect.
./MOM.res.ens_01_1.nc
./MOM.res.ens_01_2.nc
./MOM.res.ens_01_3.nc
./MOM.res.ens_01.nc
./MOM.res.ens_02_1.nc
./MOM.res.ens_02_2.nc
./MOM.res.ens_02_3.nc
./MOM.res.ens_02.nc

I believe this is with FMS2 and should also be testable with an ice/ocean only setup.
In order to run in ensemble mode, you need to use
ensemble_nml :         ensemble_size=2

Any initial condition files need to have ens_01 and ens_02 in the file names  
e.g. /fv_core.res.ens_02.tile2.nc rather than /fv_core.res.tile2.nc

This might be why using an ice-ocean only and "cold-starting" the model might be easier.
This only seems to be an issue when the restart file exceeds whatever limit is imposed, so lower resolution (1 degree) does not trigger this.

**Comment by Hallberg-NOAA** [comment]
This issue has been corrected by https://github.com/NOAA-GFDL/MOM6/pull/562, and can now be closed.
