### ISSUE TITLE
Non-reproducibility across layouts in tracer advection

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#518]
For the Bering domain, answers match for 21 vs. 24 cores, but not for 126 vs. 128 cores. The DEBUG output points to Post-advect temp and salt. This is with the PPM:H3 advection scheme. Changing the stencil to 3 in MOM_tracer_advect.F90 seems to fix it. Does this make sense? @Hallberg-NOAA

**Comment by kshedstrom** [comment]
Trying the PPM scheme does not reproduce either. I see temperature differences at one spot near the open boundary, at the bottom.

**Comment by kshedstrom** [comment]
The tracer reservoirs update with uhtr, vhtr, which are limited to two points of valid information in the halo. This is determined in lines #1033-1038 of MOM_dynamics_split.F90. If we need more points, we can add a pass_vector for tres_x, tres_y after they get updated in update_segment_tracer_reservoirs.

**Comment by theresa-morrison** [comment]
This was addressed by PR #520 for temperature and salinity, and PR #577 for generic tracers.
