### ISSUE TITLE
OM4_025 experiment with PGI executable crashes with OOM killer terminated this process

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#552]
dev/master/2017.07.05

Made the executable with pgi 16.5.0 on gaea c4 (ncrc4),  prod target (O3) WITHOUT openmp.
Set up a 1 month run of OM4_025 (1/4 degree ocean-ice baseline)
9 days into the run the model crashes with
```
[NID 00865] 2017-07-11 22:36:24 Apid 1351768: initiated application termination
[NID 00865] 2017-07-11 22:36:25 Apid 1351768: OOM killer terminated this process.
```
This is reproducible (happened twice at the same model date). 

Adding frequent memuse does not show anything out of ordinary:

```
20170711 183108.677: Memuse(MB) at Main loop at coupling timestep=     1=  2.034E+01  2.511E+01  8.669E-01  2.076E+01
...
20170711 183621.873: Memuse(MB) at Main loop at coupling timestep=   404=  2.034E+01  2.511E+01  8.669E-01  2.076E+01
20170711 183622.459: Memuse(MB) at Main loop at coupling timestep=   405=  2.034E+01  2.511E+01  8.669E-01  2.076E+01

```

stdout
```
/lustre/f1/Niki.Zadeh/warsaw_mom6_2017.07.05/OM4_SIS2_baseline.2017.07.05/ncrc4.pgi16-prod/stdout/run/OM4_SIS2_baseline.2017.07.05_1x1m0d_1756x1o.o115896
```

**Comment by adcroft** [comment]
How many cores was that run using?

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by nikizadehgfdl** [comment]
This used 1756 cores. 
layout = "32,72"   io_layout = "1,4" mask_table="mask_table.548.32x72"

**Comment by nikizadehgfdl** [comment]
More experiments crash with OOM killer on ncrc4.pgi16 platform, all using 32 pes: 

ice_ocean_SIS/GOLD_SIS_icebergs on  MOM Day 15
ice_ocean_SIS2/SIS2_bergs_cgrid    on MOM Day 14
ice_ocean_SIS2/SIS2_icebergs         on  MOM Day 15

**Comment by nikizadehgfdl** [comment]
Crash the same way for 64 pes, so it's not hitting a memory per core limit.

Crash the same way on ncrc3.pgi16, so it's not a c4 issue.

The small test SIS2_Baltic runs 20 days. It does not reproduce across restarts or layout change! 

The crashes go away on ncrc3.pgi15 , but none of the tests reproduce across restarts or layout change.

**Comment by adcroft** [comment]
Someone just reported similar issues using PGI 11. Using 16.5.0 on c3 works fine for me, @Hallberg-NOAA, and the gitlab pipeline so this must be a environment related.

**Comment by nikizadehgfdl** [comment]
Please use a more recent version of PGI and reopen if it happens. Closing.
