### ISSUE TITLE
Symmetric memory, Intel debug-executable fials for global_ALE

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#554]
I recently checked that experiments run with **debug** executables. All pass except for one experiment with the Intel compiler in symmetric memory mode.

In a visual debugger, it appears there are NaNs appearing in an array within post_data_3d(). However, the array being posted (vmo) does not have any NaNs and worse, the arrays have completely different contents above and below the interface to post_data_3d().

Debug executables with gnu, PGI and non-symmetric Intel are all completing without errors. Given how untrustworthy the Intel compiler is becoming, I'm suspecting this might not be a code bug but a compiler problem. Unfortunately, since the experiment fails this is an issue that needs to be sorted out. 

Source code at 9b914f2cc0f36b1125f15280a73356da7ca6ba5e. Traceback is:
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               000000000257B8B0  mom_diag_vkernels         148  MOM_diag_vkernels.F90
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               00000000021243D7  mom_diag_remap_mp         418  MOM_diag_remap.F90
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               000000000130020E  mom_diag_mediator         761  MOM_diag_mediator.F90
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               000000000233BF99  mom_mp_post_trans        2848  MOM.F90
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               00000000022EB031  mom_mp_step_mom_          986  MOM.F90
> MOM6-examples/ocean_only/global_ALE/z/ocean.stats.intel: MOM6               0000000001526DB1  MAIN__                    473  MOM_driver.F90
>

**Comment by marshallward** [comment]
I've run the TCs using the Intel compilers and all tests passed (excepting REPRO, which is a separate discussion), so I'm going to assume this has been fixed in one of the many diagnostic bugfix sweeps.
