### ISSUE TITLE
Diagnostics registered but not posted (conSST, absSSS, abssalt, contemp)

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#574]
These diagnostics are registered if CS%use_temperature = .true. however will only be posted if CS%use_conT_absS = .true.

One reason we need diagnostics to be registered and posted under the same conditions is that it allows users to identify which diagnostics are available for a given configuration. 

This problem was revealed by the MOM diagnostics test: https://accessdev.nci.org.au/jenkins/job/mom-ocean.org/
(Understandably it's relevance has been diminished recently because it hasn't had a 'pass' status in a long time!)

**Comment by Hallberg-NOAA** [comment]
This issue was addressed on August 15, 2017 by PR #575.
