### ISSUE TITLE
ALE mode needs to use G%nk_rho_varies=nz

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#58]
In bulk-mixed layer mode, nk_rho_varies = nkml+nkbl, the number of mixed- and buffer-layers. Since nkml+nkbl=0 when not using the bulk-mixed layer we tested ALE using mk_rho_varies=0 so far.

Routines possibly impacted:

``` core/MOM_PressureForce_Montgomery.F90
core/MOM_PressureForce_analytic_FV.F90
diagnostics/MOM_diagnostics.F90
diagnostics/MOM_PointAccel.F90
initialization/MOM_initialization.F90
parameterizations/vertical/MOM_set_viscosity.F90
parameterizations/vertical/MOM_regularize_layers.F90
parameterizations/vertical/MOM_sponge.F90
parameterizations/vertical/MOM_set_diffusivity.F90
parameterizations/vertical/MOM_diabatic_driver.F90
parameterizations/vertical/MOM_entrain_diffusive.F90
parameterizations/vertical/MOM_geothermal.F90
parameterizations/lateral/MOM_thickness_diffuse.F90
tracer/MOM_tracer_hor_diff.F90
```

A cursory inspection reveals likely problems only with set_density_ratios() and add_drag_diffusivity() in MOM_set_viscosity.F90.

**Comment by Hallberg-NOAA** [comment]
ALE mode configurations work perfectly well with GV%nk_rho_varies=0, and the behavior in most ALE mode configurations is largely independent of the value of GV%nk_rho_varies.  It might make sense to rename this as GV%layer_mode_nk_rho_varies for greater clarity, but this does not seem necessary. I do not believe that there are any remaining MOM6 code changes needed to address this issue. If there are still specific issues related to this that need to be addressed, please open a new issue with the specific details of what needs to be corrected.
