### ISSUE TITLE
diagnostic name to be changed

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#602]
In the EPBL code 

 MOM6/src/parameterizations/vertical/MOM_energetic_PBL.F90

the diagnostic ePBL_h_ML is given the description  

`Surface mixed layer depth'

In fact, this diagnostic is for the "surface boundary layer depth".  As the "mixed layer depth" has a meaning distinct from "boundary layer depth", I recommend we change this diagnostic from 

 CS%id_ML_depth = register_diag_field('ocean_model', 'ePBL_h_ML', diag%axesT1, &
Time, 'Surface mixed layer depth', 'meter')

to be instead 

 CS%id_BL_depth = register_diag_field('ocean_model', 'ePBL_h_BL', diag%axesT1, &
Time, 'Surface boundary layer depth', 'meter')

The only experiment that enables "ePBL_h_ML" is ocean_only/single_column/EPBL/diag_table.  So there will be minimal impact by making this suggested name change.  

Making the change will reduce confusion from the MOM6 user community.  The confusion may arise when they diagnose ePBL_h_ML (which is the "boundary layer depth" but named "mixed layer depth") and the actual CMIP6 "mixed layer depth" diagnostic 

 CS%id_MLD_003 = register_diag_field('ocean_model','MLD_003',diag%axesT1,Time,        &
      'Mixed layer depth (delta rho = 0.03)', 'meter', cmor_field_name='mlotst',       &
      cmor_long_name='Ocean Mixed Layer Thickness Defined by Sigma T', cmor_units='m', &
cmor_standard_name='ocean_mixed_layer_thickness_defined_by_sigma_t')

**Comment by adcroft** [comment]
Was this meant to be closed by 9be672efa59409b2 ?

**Comment by StephenGriffies** [comment]
Yes.  This issue can be closed with that code update.

**Comment by adcroft** [comment]
Closed by 9be672efa59409b2e596e933a1d22401521da103
