### ISSUE TITLE
Z-space diagnostics should use the ALE remapping 

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#62]
The z-space diagnostics are currently using a simple interpolation in the vertical for scalars.

To do:
- Invoke the remapping routines used for ALE to access high-order conservative remapping.
- Transports are already conservatively remapped but could also be made higher-order.

**Comment by Hallberg-NOAA** [comment]
There is a consensus that this issue was resolved several years ago.
