### ISSUE TITLE
FMS update - need MOM6 changes too?

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#625]
I got a notification that my i,j diag table indexing is fixed in the latest FMS. I went to try it out and got this at link time:
```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: MOM_couplertype_infra.o: in function `mom_couplertype_infra_mp_ct_rescale_data_2d_':
//autofs/ncrc-svm1_home2/Katherine.Hedstrom/ESMG/ESMG-configs/src/MOM6/config_src/infra/FMS2/MOM_couplertype_infra.F90:313:(.text+0x1a5): undefined reference to `coupler_types_mod_mp_ct_rescale_data_2d_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: MOM_couplertype_infra.o: in function `mom_couplertype_infra_mp_ct_rescale_data_3d_':
//autofs/ncrc-svm1_home2/Katherine.Hedstrom/ESMG/ESMG-configs/src/MOM6/config_src/infra/FMS2/MOM_couplertype_infra.F90:323:(.text+0x1d5): undefined reference to `coupler_types_mod_mp_ct_rescale_data_3d_'
```

**Comment by marshallward** [comment]
I still see them in FMS:

https://github.com/NOAA-GFDL/FMS/tree/main/coupler/include

I will try to replicate if I find some time this evening.

**Comment by marshallward** [comment]
Looking closer... it is trying to find `ct_rescale_data_2d` and `ct_rescale_data_3d`, which don't exist.  Rather, there are macros `CT_RESCALE_DATA_2D_` and `CT_RESCALE_DATA_3D_` which are preprocessed into the specific functions.

@uramirez8707 Has there been any change to this API?

**Comment by marshallward** [comment]
Looking even further:  We call `coupler_type_rescale_data` interface, which is supposed to sort out these types.  Even if they changed their internal API, they have still preserved the interface.  @kshedstrom Could this just be an out-of-date .mod file or something?

**Comment by kshedstrom** [comment]
Sorry, yes, I've gotten out of practice with using my Makefile and I forgot to "make distclean" after changing the FMS version.
