### ISSUE TITLE
adjust_salt uses a positive hard-coded minimum salinity

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#630]
When adjust_salt (a routine in MOM_diabatic_aux.F90) is used to deal with water with a negative (or exessively small) salinity, it uses a hard-code minimum salinity of 0.01 ppt (or psu).

  Negative salinities are obviously very bad, but I think that a minimum value of 0 should be fine. In any case the minimum salinity should be a run-time configurable value.  This particular code can be traced back to the initial check-in of the first version of MOM6, so there is no record from the person who first introduced this (I could have been that person!) was thinking. The capability in adjust_salt is important if we use a sea-ice model with a specified positive ice salinity (which is not necessary with SIS2). Does anyone recall why we set this minimum salinity to 0.01 instead of 0?

**Comment by MJHarrison-GFDL** [comment]
You and I did this together back in the prehistoric age! I'm not sure which one of us chose this value, but it was certainly arbitrary.

**Comment by Hallberg-NOAA** [comment]
This fixed value will be converted to a runtime parameter (MIN_SALINITY) when https://github.com/NOAA-GFDL/MOM6/pull/920 is completed. We will then test using 0 and consider changing the default to 0 in due course.

**Comment by Hallberg-NOAA** [comment]
The default value for MIN_SALINITY was changed to 0 with commit https://github.com/NOAA-GFDL/MOM6/commit/613a82e6e59d35a8c162b5ccd42ec5ae32e68c44, and this was merged into the main branch of dev/gfdl with PR #1127. This issue is now considered resolved.
