### ISSUE TITLE
ocean_only experiment crash: segmentation fault

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#635]
Hi,

I was trying to run an ocean_only configuration of MOM6 but the integration got crashed _twice_ around model year-61, with different timesteps, and I got this error message repeatedly:

> forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image                        PC                                Routine                         Line                 Source
MOM6                 00000000012C4921    Unknown                     Unknown            Unknown
MOM6                 00000000012C3077    Unknown                     Unknown            Unknown
libnetcdff.so.6    00007F6A9CBEED62   Unknown                     Unknown            Unknown
libnetcdff.so.6    00007F6A9CBEEBB6   Unknown                     Unknown            Unknown
libnetcdff.so.6    00007F6A9CBD560C  Unknown                     Unknown             Unknown
libnetcdff.so.6    00007F6A9CBD9678  Unknown                      Unknown            Unknown
libpthread.so.0   00007F6A9B1D5100    Unknown                     Unknown            Unknown
MOM6                 00000000008E5F71    mom_barotropic_mp   1473                   MOM_barotropic.F90
MOM6                 0000000000C9A6E7  mom_dynamics_spli     495      MOM_dynamics_split_RK2.F90
MOM6                 0000000000ADD1EC  mom_mp_step_mom_  837                      MOM.F90
MOM6                 0000000000792673   MAIN__                         463                     MOM_driver.F90
MOM6                 0000000000406DBE  Unknown                     Unknown             Unknown
libc.so.6              00007F6A9AB24B15   Unknown                     Unknown             Unknown
MOM6               0000000000406CC9    Unknown                     Unknown             Unknown

The commits I have used (using git show) are

> modified:   src/initialization/MOM_fixed_initialization.F90
>
> diff --git a/src/initialization/MOM_fixed_initialization.F90 b/src/initialization/MOM_fixed_initialization.F90
index d43c9a0..bfbf55a 100644
--- a/src/initialization/MOM_fixed_initialization.F90
+++ b/src/initialization/MOM_fixed_initialization.F90
@@ -220,7 +220,7 @@ subroutine MOM_initialize_topography(D, max_depth, G, PF)
>     case ("ISOMIP");    call ISOMIP_initialize_topography(D, G, PF, max_depth)
>     case ("benchmark"); call benchmark_initialize_topography(D, G, PF, max_depth)
>     case ("Neverland"); call Neverland_initialize_topography(D, G, PF, max_depth)
>\-    case ("sheobox");   call shoebox_initialize_topography(D, G, PF, max_depth)
>\+    case ("shoebox");   call shoebox_initialize_topography(D, G, PF, max_depth)
>     case ("DOME2D");    call DOME2d_initialize_topography(D, G, PF, max_depth)
>     case ("Kelvin");    call Kelvin_initialize_topography(D, G, PF, max_depth)
>     case ("sloshing");  call sloshing_initialize_topography(D, G, PF, max_depth)

Actually this list is not complete... But to summarize, I had implemented a new configuration ("shoebox") with specified topography and surface wind & buoyancy conditions. All short time integrations were fine (e.g. < 20-year).  Also I could provide my git log if necessary.

Thank you for your help!

**Comment by adcroft** [comment]
Did you ever get past this? Was the crash after a restart or in the middle of the run?

The commit id's from the msg aren't in our repository so I can't be sure of the line numbers but assuming MOM_barotropic.F90 is the same as ours, line 1473 is in the vicinity of an allocate for weights in a time filter which is a function of timesteps. Can you do `grep BT MOM_parameter_doc.all` and post the output? Also confirm that line 1473 for you looks like [this](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/core/MOM_barotropic.F90#L1473). If it does, it would also be useful to know what _nstep_ and _nfilter_ evaluate to (add some print statements if you don't have a debugger).

**Comment by hlkong** [comment]
Hi Alistair,

Thank you for your message! 

I somehow was able to get around this, simply by decreasing the timestep. Yet I'm still confused at why MOM6 just didn't tell me the CFL has blown up...

The issue always occurs in a middle of a run; and the line 1473 in my version of MOM6 is the same as the one you pointed me to. Here is the output of grep:

> DTBT_RESET_PERIOD = 0.0         !   [s] default = 1.08E+04
                                ! The period between recalculations of DTBT (if DTBT <= 0).
                                ! If DTBT_RESET_PERIOD is negative, DTBT is set based
                                ! dynamic, DTBT will be set at least every forcing time
RESOLN_USE_EBT = False          !   [Boolean] default = False
KHTH_USE_EBT_STRUCT = False     !   [Boolean] default = False
BT_USE_LAYER_FLUXES = True      !   [Boolean] default = True
BOUND_BT_CORRECTION = True      !   [Boolean] default = False
                                ! less than maxCFL_BT_cont to be accommodated.
BT_CONT_CORR_BOUNDS = True      !   [Boolean] default = True
                                ! If true, and BOUND_BT_CORRECTION is true, use the
                                ! BT_cont_type variables to set limits determined by
                                ! MAXCFL_BT_CONT on the CFL number of the velocites
ADJUST_BT_CONT = False          !   [Boolean] default = False
                                ! If true, adjust the curve fit to the BT_cont type
GRADUAL_BT_ICS = False          !   [Boolean] default = False
BT_USE_VISC_REM_U_UH0 = False   !   [Boolean] default = False
USE_BT_CONT_TYPE = True         !   [Boolean] default = True
NONLINEAR_BT_CONTINUITY = True  !   [Boolean] default = False
                                ! USE_BT_CONT_TYPE is true.
NONLIN_BT_CONT_UPDATE_PERIOD = 1 !   [nondim] default = 1
                                ! If NONLINEAR_BT_CONTINUITY is true, this is the number
BT_MASS_SOURCE_LIMIT = 0.0      !   [nondim] default = 0.0
BT_PROJECT_VELOCITY = True      !   [Boolean] default = False
                                ! out the velocity tendancy by 1+BEBT when calculating the
                                ! of (1-BEBT) and BEBT.
BT_THICK_SCHEME = "FROM_BT_CONT" ! default = "FROM_BT_CONT"
                                !    FROM_BT_CONT - use the average thicknesses kept
                                !       in the h_u and h_v fields of the BT_cont_type
BT_STRONG_DRAG = False          !   [Boolean] default = False
CLIP_BT_VELOCITY = False        !   [Boolean] default = False
MAXCFL_BT_CONT = 0.25           !   [nondim] default = 0.25
DT_BT_FILTER = -0.25            !   [sec or nondim] default = -0.25
G_BT_EXTRA = 0.0                !   [nondim] default = 0.0
DEBUG_BT = False                !   [Boolean] default = False
BEBT = 0.2                      !   [nondim] default = 0.1
                                ! BEBT determines whether the barotropic time stepping
                                ! backward Euler scheme. BEBT is valid in the range from
                                ! In practice, BEBT must be greater than about 0.05.
DTBT = -0.95                    !   [s or nondim] default = -0.98
                                ! The barotropic time step, in s. DTBT is only used with
                                ! Setting DTBT to 0 is the same as setting it to -0.98.
                                ! The value of DTBT that will actually be used is an
BT_USE_OLD_CORIOLIS_BRACKET_BUG = False !   [Boolean] default = False
DIAG_EBT_MONO_N2_COLUMN_FRACTION = 0.0 !   [nondim] default = 0.0
DIAG_EBT_MONO_N2_DEPTH = -1.0   !   [m] default = -1.0

Sorry but I guess I'm not familiar with how to check nstep or nfilter - would you mind giving more hint?

Thank you so much!

**Comment by adcroft** [comment]
The model checks the barotropic CFL based on DTBT_RESET_PERIOD which currently equals 0 so should be checking every step.

To debug it, just add `print *,'msg',nstep,nfilter` above the allocate lines at line 1467.

**Comment by hlkong** [comment]
Thanks for the help! 

Yet after adding this line, the output file I got has only "msg   27   4" repeatedly for loads of times (GB size file for each 100 yr simulation), even if I have specified CFL to be diagnosed once every 30-day. (But I would assume this not to be too helpful, since the original segmentation fault did not occur?)

**Comment by adcroft** [comment]
Was this the same setup that crashed before? We're trying to find out the conditions at the point of the SEGV so you should use whatever setup was failing. Run it again to make sure it crashes and then add the `print` to find out what nstep and nfilter are. Then try this to see what changes when the SEGV happens:
`if (nstep/=27.or.nfilter/=4) print *,'oops',nstep,nfilter`

**Comment by hlkong** [comment]
I re-ran one of the previously crashed simulation and this is what I got, repeated for every single core:

> oops -2147483648  -268435456

**Comment by Hallberg-NOAA** [comment]
Given that there has not been an update in more than 3 years, we are going to assume that this issue has been fixed. If this is still a problem, please reopen this issue or another issue with a specific description of how the problem is arising with a more recent version of the code.
