### ISSUE TITLE
Remapped diagnostics have bad data

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#638]
The diagnostic thetao in z-space has bad values appearing in CM4 at k>12 on the Levitus veritcal grid:
![image](https://user-images.githubusercontent.com/5859571/32175373-24dc319e-bd5b-11e7-9800-ea921d3909c0.png)

**Comment by StephenGriffies** [comment]
The salinity field, "so", is also bad.  But there are other T-cell fields that are sensible.

**Comment by adcroft** [comment]
A clue! The bad values equal the missing_value divided by the time-averaging interval...

![image](https://user-images.githubusercontent.com/5859571/32202567-115091fc-bdb4-11e7-8af1-3003c1518a90.png)

**Comment by ashao** [comment]
I think I ran into something similar to this before when trying to output
cumulative sums of a quantity. What it boiled down to was that FMS was not
handling the case for a 3D field which includes a layer that vanishes and
reappears over the time interval. Basically it understands an entire column
being masked, but not parts of the column. I'm trying to figure out where
in the code I had tracked this down to.

**Comment by adcroft** [comment]
That's exactly what's happening. Round-off is causing a layer to briefly appear and it posts with a real value but the time averaging assuming static masking.

There are two parts to the problem:
- The use of missing_value in the remapping is awkward - the values in vanished layers should be the same as the non-vanished value above. We used to do it this way until someone insisted they wanted masking. If we did not set array values to missing_value, they couldn't propagate through (this is not actually happening but one day it will).
- We are pointing a 3d mask for each diagnostic to the 3d mask of the native grid, which is actually a 3d version of 2d data. e.g. https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/framework/MOM_diag_mediator.F90#L2117-L2122 and https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/framework/MOM_diag_mediator.F90#L2222 . This is simply wrong. If we ever diagnosed more levels than native layers then this would SEGV OOB.

I'm going to add an actual 3d mask to the axes_grp, and the axes_grp corresponding to z* will be calculated initially and assumed static. This will work if the remapping assigns vanished values as mentioned above.

**Comment by adcroft** [comment]
PS> The API documentation for set_diag_mask() says it does what I just proposed, except it doesn't. https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/framework/MOM_diag_mediator.F90#L2210

**Comment by ashao** [comment]
For the z* grid, I don't think it can be static. For example if you have
target level at 50m and 100m and the depth of a water column changed over
the averaging interval from 49 to 51 the vertical mask will have changed.

On Oct 30, 2017 6:41 PM, "Alistair Adcroft" <notifications@github.com>
wrote:

PS> The API documentation for set_diag_mask() says it does what I just
proposed, except it doesn't. https://github.com/NOAA-GFDL/
MOM6/blob/dev/gfdl/src/framework/MOM_diag_mediator.F90#L2210

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/NOAA-GFDL/MOM6/issues/638#issuecomment-340634550>, or mute
the thread

**Comment by adcroft** [comment]
The z* coordinate always stretches with the water column so if the water column was 100m deep but the sea level dropped by 50m, z*=-20m would be at z=-60m. z*=0 is always the (free-)surface.

**Comment by adcroft** [comment]
...so the masking in z*-coordinates should be static...

...luckily we're not worrying about ice-shelves or the Stern-coordinate right now...

**Comment by ashao** [comment]
Right of course....too much driving :-)

**Comment by adcroft** [comment]
This was closed by #640 (and should have been closed automatically according to the commit message - not sure why it didn't).
