### ISSUE TITLE
z-remapped frazil heat diagnostic is wrong

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#641]
Frazil heating is diagnosed insided MOM_diabatic_driver.F90.  There are two places that the diagnostic needs to be computed since frazil is called at both the start and end of diabatic processes.  

Unfortunately, there are nontrivial differences between the native level grid version of the depth-summed version of frazil_heat_tendency, indicating there is a problem with the remapped diagnostics

native version of FRAZIL_HEAT_TENDENCY[k=@sum]  NOT EQUAL    FRAZIL_HEAT_TENDENCY[k=@sum] z-remapped

I suspect there is a thickness issue.  The subtle point is that the frazil diagnostic is called twice, corresponding to the twice called frazil heating adjustment.  Presumably the layer thickness changes between these two calls.  

Can I get some help from @ashao on this issue?  He has debugged this issue elsewhere, and I suspect his expertise could find the bug quickly...

As it stands, this bug makes the heat budget for ocean_z not close.  The native layer output does close.

**Comment by ashao** [comment]
I'll have some time today to to take a look at this.

**Comment by ashao** [comment]
I think I know the reason why this diagnostic is wrong. It's slightly more
complicated than just a wrong layer thicknesses. The frazil heat flux is
the sum of the first and second call to make_frazil, but the diagnostic is
only posted at the end. In between those calls the thicknesses have all
changed.

I think the right thing to do is to call post_data both times (with the
correct thicknesses) making sure that the diagnostic manager's averaging is
for half the diabatic timestamp, and also calculating the tendency for half
the timestep.

On Nov 1, 2017 9:31 AM, "Andrew Shao" <aeshao@gmail.com> wrote:

I'll have some time today to to take a look at this.

**Comment by adcroft** [comment]
That sounds about right. I think it would still have to have yet another
carefully crafted thickness for the remapping.

**Comment by ashao** [comment]
Ok, what I previously described is only partly what's going on. I just
tried doing the call to make_frazil once (and changing the tendency routine
too) and the remapped still isn't quite right. I'll keep you posted when I
come up with another lead.

**Comment by ashao** [comment]
Tracked it down- the v_extensive flag also needed to be set. Because this issue has come up before, I suggest that we add a "v_extensive" line to available_diags in much the same way that cell_methods is attached to some of the diagnostics.

 The 3D budgets still won't close because of the aforementioned double make_frazil call. One of the annoying things about that is that we need to bring the time type into the diabatic subroutine which breaks the (soft?) convention that the enable_averaging/disable_averaging calls are in core/MOM.F90. @adcroft, @Hallberg-NOAA: do you have have any objections to that?

**Comment by StephenGriffies** [comment]
@ashao please clarify whether your code pull request fixes the frazil diagnostic.  Reading the pull request documentation makes it sound like all is now fixed.  But the comment above sounds like there are issues still to be resolved.

**Comment by ashao** [comment]
Yes the PR does fix the frazil diagnostic. There were two changes: 1)
v_extensive needed to be set and 2) the diagnostic needed to be posted
after both calls to make frazil and not just the sum of both calls

**Comment by ashao** [comment]
This issue was resolved by PR #644 and can be closed.
