### ISSUE TITLE
Heat and salt budgets do not close due to errors in remapping advective tendencies

### ISSUE THREAD

**Issue by ashao** [NOAA-GFDL/MOM6#653]
This issue supersedes #646 as it addresses the reasons why the 3D heat and salt budgets do not close using the remapped diagnostics.
1) T/S_advection_xy (and diffusive tendencies) need to be posted right after the advection happens. As coded now, for cases where DIABATIC_FIRST = False, layer thicknesses change in the diabatic routines and so the advective/diffusive tendencies get remapped onto the wrong destination grid. I will have a PR in shortly to resolve this problem.
2) The second issue is more subtle and one that I am less sure of which is that small errors in the 'reintegrate_column' subroutine in MOM_diag_vkernels.F90 end up being non-negligible when trying to reconstruct the tendency term by term. Evidence for this is shown below

Below is the cumulative integral for a single columnl of the difference between the total time tendency and the sum of the individual tendencies (e.g. advection, vertical remapping, etc.) with dots indicating the cumulative integral at the bottom of the cell. 
![image](https://user-images.githubusercontent.com/3845639/32972592-02820b2c-cba8-11e7-903a-602ab008f0e2.png)

For the native-space diagnostics, the plot is always 0 indicating that the heat budget closes perfectly. The remapped-space budget sums to 0 by the bottom, however it is not always 0 indicating non-neglible errors in the cell-by-cell heat budget. 

If we calculate the same difference, but exclude advection, the residual is
![image](https://user-images.githubusercontent.com/3845639/32972542-c7ee4ca0-cba7-11e7-9f8c-d5fac92322d7.png)
This indicates that the other terms seem to be remapped correctly as the two cumulative integrals overlap.

This does not seem to be a case where the wrong layer thicknesses are being used to remap the advective heat tendencies, but what I conjecture is that because the advective tendencies are so large, the 'typical' remapping errors are large enough to contribute to the overall budget. I'm playing around with some alternate ways to test that. In the meantime @adcroft and @StephenGriffies, any comments or suggestions?

**Comment by ashao** [comment]
I've made two changes to the code that address points 1 (e2378c4b31650cc53c7eed7dc789e258fe35c58d) and 2 (7abec55a644082d5fd369298ed99c12aa9348184) from the original post. These two fixes bring the difference between the cumulative integrals of the convergence of advective heat fluxes to something like 8000W (which is of course is too big, but an order of magnitude smaller than the original code):
![image](https://user-images.githubusercontent.com/3845639/33047607-8ee268c2-ce0b-11e7-86f3-37e74ddd1be8.png)

**Comment by ashao** [comment]
@adcroft , @StephenGriffies, @Hallberg-NOAA 

I had cast aspersions upon the reintegration algorithm, but it turned out to be that the thickness fields were not stored at the right place in the code. Now (due to the law bug conservation I'm sure), the net time tendency diagnostic (e.g. opottemptend or Th_tendency) isn't closing under remapping. This time I can't find anything obviously wrong in the thicknesses.

The tendency diagnostic is posted at this point in the algorithm:
(https://github.com/ashao/MOM6/blob/ba40ae71b578c57a4d75cdd65a56b1bfeb36b49f/src/core/MOM.F90#L856-L863)
and the post itself happens in:
https://github.com/ashao/MOM6/blob/ba40ae71b578c57a4d75cdd65a56b1bfeb36b49f/src/tracer/MOM_tracer_registry.F90#L643-L692

The grid that these diagnostics are posted on are in diag_pre_sync (which contains the model grid and remapped grids from the last time this block of code was executed). 

Can you see if I'm doing anything obviously wrong? BTW, here's what the heat tendency budget looks like now
![image](https://user-images.githubusercontent.com/3845639/35749222-beb002c4-0805-11e8-8a0b-a85148bc8de9.png)

**Comment by StephenGriffies** [comment]
What in fact resolved the problem with T_advection_xy?  Was it Bob's magic reorganization?  Or something else?  

As per your bug conservation axiom, could Bob's reorganization have shifted a bug (the same bug) from T_advection_xy to opottemptend?

**Comment by ashao** [comment]
So Bob and I both noticed that the layer thicknesses were being stored at the wrong point of the algorithm if THICKNESS_DIFFUSE_FIRST = .true. In that case, the layer thicknesses being used would have been correct for the mean circulation, but not for the residual mean transports.

Unfortunately, I don't think that fixing T_advection_xy broke opottemptend because they use different thicknesses.

**Comment by ashao** [comment]
Ah I at least tracked down the problem With the temperature tendency...I forgot that when you do something like array1 = array2 in Python, that it doesn't make copy but basically makes a pointer....

Anyway, the plots of individual tendencies now look like we expect. The full budget does not close for every point, but at this point I can't think of anything it could be other than that smaller errors in the reintegration of large terms are leading to a large residual. I'll also note that these problematic points are scattered and most cell budgets are perfectly fine (see the second figure).

Problematic Point
![image](https://user-images.githubusercontent.com/3845639/35997428-51ac7356-0cce-11e8-8ea2-6240097b1216.png)

Ok point:
![image](https://user-images.githubusercontent.com/3845639/35997596-cdcc528a-0cce-11e8-93b3-170c8db7a3f5.png)

**Comment by ashao** [comment]
@StephenGriffies : Here's a plot of the remapped total time tendency and the residual, integrated over the domain of the test which encompasses just the Mediterranean. Note that in this case, these are the actual tendencies  and not the cumulative integral like in the other cases. As you can see in the plot on the right, the percent error can be as big as O(1%) but most are significantly smaller.
![image](https://user-images.githubusercontent.com/3845639/36045523-d96ccd7e-0d8a-11e8-8318-ebaa74d65560.png)

The last step before I put in the PR to close this issue is to run for a year in OM4_025 and OM4_05. After I do that for both models, I'll include a figures for each case that has an estimate of the remapping error (vertical sum of the absolute residual).
