### ISSUE TITLE
compiling error: undefined reference to `cvmix_shear_mp_cvmix_init_shear_'

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#669]
I just had this issue out of nowhere: after making some changes to my src code and pushing them to my branch [shoebox](https://github.com/hlkong/MOM6/tree/shoebox), I was no longer able to compile my MOM6 ocean component. I got the following error message:

      MOM_KPP.o: In function `mom_kpp_mp_kpp_calculate_':
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:628: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_turbulent_scales_1d_obl_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:637: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_bulk_richardson_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:648: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_obl_depth_low_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:670: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_kobl_depth_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:710: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_bulk_richardson_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:720: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_obl_depth_low_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:734: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_kobl_depth_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:741: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_kobl_depth_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:773: undefined reference to `cvmix_kpp_mp_cvmix_coeffs_kpp_low_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:844: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_turbulent_scales_1d_sigma_'
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:857: undefined reference to `cvmix_kpp_mp_cvmix_kpp_compute_unresolved_shear_'
      MOM_KPP.o: In function `mom_kpp_mp_kpp_init_':
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_KPP.F90:297: undefined reference to `cvmix_kpp_mp_cvmix_init_kpp_'
      MOM_cvmix_shear.o: In function `mom_cvmix_shear_mp_calculate_cvmix_shear_':
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_cvmix_shear.F90:115: undefined reference to `cvmix_shear_mp_cvmix_coeffs_shear_low_'
      MOM_cvmix_shear.o: In function `mom_cvmix_shear_mp_cvmix_shear_init_':
      /project2/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/parameterizations/vertical/MOM_cvmix_shear.F90:192: undefined reference to `cvmix_shear_mp_cvmix_init_shear_'
      make: *** [MOM6] Error 1

which seems not to make any sense because I didn't change the KPP parameterization code at all, which can also be seen by comparing my [shoebox](https://github.com/hlkong/MOM6/tree/shoebox) branch with the original [dev/gfdl](https://github.com/NOAA-GFDL/MOM6) branch: all green and no red. 

What's more wired is that I was able to get around this before (a few hours ago) simply by deleting and re-installing the MOM6 ocean component under my branch, but now I even cannot make it by doing this. 

Thanks ahead for your help!

**Comment by ashao** [comment]
This sounds almost like you need to initialize and checkout the CVMix submodule in the MOM6 source. try exectuing the following two commands in your MOM6-examples/src/MOM6 directory:
`git submodule init ; git submodule update`

**Comment by hlkong** [comment]
Thank you so much! Now it works : )
