### ISSUE TITLE
Channels not being implemented and no ERROR

### ISSUE THREAD

**Issue by wfcooke** [NOAA-GFDL/MOM6#683]
When using the 
 MOM6-examples/ice_ocean_SIS2/OM4_025/INPUT/MOM_channels_global_025
file to create channels in SPEAR (1 deg coupled ocean) we are finding that the channels are not being implemented.
The problem occurs at 
https://github.com/NOAA-GFDL/MOM6/blob/85c2ea0bf81b12a316fe40bc7713520f14a558fb/src/initialization/MOM_shared_initialization.F90#L907

and L926 where the input values are compared to the model values. If the input limits fall within a gridbox then the code does not create the limiting channel **but does not report that it is not being created**.

e.g.
U_width,  -5.9,  -5.4, 35.8, 36.2,  12000.0  ! Gibraltar
from ocean_static.nc
geolat_u  34.67->35.49->36.30 (in SPEAR)
geolon_u -6 -> -5 -> -4

-5.9, -5.4 falls between -6 and -5 
 35.8, 36.2, falls between 35.49->36.30

so we end up with a full width gridbox for the Gibraltar channel.

All 5 channels are not set for our setup

SUGGESTED FIX : 
Add a FATAL error to bring the model down if the channel is not implemented.
(and then update the MOM_channel  file for your model)

**Comment by Hallberg-NOAA** [comment]
This issue has been addressed by the improved channel list error handling in PR#1251.
