### ISSUE TITLE
salt_flux_restore diagnostics do not get written out to history files

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#690]
OMIP runs [e.g. 848](http://dora.gfdl.noaa.gov/experiments/view.php?id=848) have the following lines in diag_table but the diagnostics  are absent from both history files. 

```
 "ocean_model", "salt_flux_restore",  "salt_flux_restore",  "ocean_annual", "all", "mean", "none",2
 "ocean_model", "salt_flux_restore",  "salt_flux_restore",  "ocean_month", "all", "mean", "none",2
```

**Comment by StephenGriffies** [comment]
It was fine in earlier versions.  Perhaps it got removed with the recent tracer reorganization?

**Comment by nikizadehgfdl** [comment]
I think the problem is at some point the  diagnostics code id string got renamed from "salt_flux_restore" to 'salt_flux_added'  and we neglected to change it in the diag_table. Is that right?

**Comment by adcroft** [comment]
Yes, it looks like the diagnostic was renamed two years ago. We will need to update the diag_tables.
