### ISSUE TITLE
Turning on all the new bug-fix options makes ice-ocean model blow up

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#707]
It is blowing up with ice velocities out of bounds in the first month. An example of sispeed is here. Notable is some hint of the tile boundaries which are ten grids apart in x. At @theresa-morrison's suggestion, I turned off all the new OM4_SUBCELLS options and it is running longer.
![Screenshot 2024-08-07 at 2 31 05 PM](https://github.com/user-attachments/assets/ec70699a-e01a-42eb-b495-97fd853cfa93)

**Comment by kshedstrom** [comment]
No, it still looks like crap, including the tile hints. It must be one of the other new changes.

**Comment by kshedstrom** [comment]
OK, following the usual DEBUG comparison of 4x6 cores vs 3x7 gives:

```
h-point: c= 934507767 sw= 934794058 se= 934691555 nw= 934814696 ne= 934712693 Post-mixedlayer_restrat h
```
This is Bodner, reading Cr and timescale fields from a file.

**Comment by theresa-morrison** [comment]
Thanks for testing this Kate. I am going to set up some short tests with each flag.

**Comment by kshedstrom** [comment]
Bodner not reading from a file still differs in the DEBUG output.

I've got guests now and won't be able to dig in until next week. I don't think the Bodner trouble is causing the sea ice trouble.

**Comment by theresa-morrison** [comment]
I wasn't able to use the files restrat_vars files because I didn't have read access. If you have a minute to change the permissions that would be great. Otherwise I will test the bug fixes without the restrat vars files.

**Comment by kshedstrom** [comment]
OK, done.

**Comment by theresa-morrison** [comment]
thanks!

**Comment by theresa-morrison** [comment]
Hi Kate, I was able to get your experiment running with the Bodner files and the bug fixes. I am seeing the bad sea-ice coverage and velocities. I tried turning off the Bodner files (using the default constants) and some of the bug fixes, but neither helped.

I'm not sure what else you changed from your previous experiment, but maybe skip the bug fixes until you are sure those changes are working well?

**Comment by kshedstrom** [comment]
Can you try the code without Bob’s parentheses?

**Comment by theresa-morrison** [comment]
I am not sure that the FMA paretntheses are something that can be turned on/off with a flag. 

I took a more careful look at my experiments. The Bodner files do seem to be causing the issues - although there is still a lot of excess ice without the files which is what I was looking at. 

Left is with the default restratification parameters, right is using the spatially varying files. 
![image](https://github.com/user-attachments/assets/3363b374-42c8-49ad-b41f-4b8ff854546b)

**Comment by kshedstrom** [comment]
Yes, I see your point. I will try PR #711 on gaea to see if it cleans things up. Thanks for testing it!

**Comment by theresa-morrison** [comment]
Kate can we close this issue now that the fix has been merged into dev/gfdl?

**Comment by kshedstrom** [comment]
Indeed!
