### ISSUE TITLE
CMOR variables thetao and so are incorrect when using the GSW equation of state

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#709]
In the block https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/core/MOM.F90#L2707-L2724  we are changing the name of the MOM6-native variable but the associated CMOR names need to change. Conservative temperature should be "bigthetao", according to https://doi.org/10.5194/gmd-9-3231-2016 . I didn't see a variable for absolute salinity. We need to check with CMIP7 if there is one...

**Comment by StephenGriffies** [comment]
Thanks for flagging this issue @adcroft .  OM5 team leads also found this issue to be a problem with their new simulations with the Roquet EOS, which is TEOS10 compliant.    

In regards to the suggestion from @Hallberg-NOAA:  I recommend against offering to diagnose Conservative Temperature and Absolute Salinity when running pre-TEOS10 simulations (i.e., models with potTemp and pracSaln as prognostic).  The following McDougall et al (2021) paper suggests that even when running a pre-TEOS10 model, the best interpretation of the model's prognostic fields are, in fact, ConsTemp and AbsSaln.  Yea, this interpretation sounds a bit confusing.  But details matter and they are articulated by McDougall et al.  So if we then add new diagnostics, that would be confusing.  So, I recommend against writing that diagnostic code. 

https://gmd.copernicus.org/articles/14/6445/2021/gmd-14-6445-2021-discussion.html

**Comment by adcroft** [comment]
Concerning McDougall et al., @baylorfk and I think their statements make sense for budgets (think heat budgets) but when directly comparing to observations or comparing with other models, putting AbsSaln into the CMIP "so" variable would lead to big apparent differences. @jetesdal showed us differences for salinity of order 0.2 g/kg in the OM5 plots today. I think I've convinced @baylorfk that we need to update the protocol paper to add a new variable for AbsSaln and write it out IF writing out bigthetao, but always write out equivalent potTemp and pracSaln for the sake of comparisons and backward compatibility.

The name of the new AbsSaln needs to be defined. Currently "bigso", "absso", "aso", "sao" seem to be available.

**Comment by StephenGriffies** [comment]
I concur. Thanks for adding this comment.
