### ISSUE TITLE
Save a tracer bit count in ocean.stats.*

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#722]
There's currently no way to check for changed answers in tracers such as dye concentration. We talked about creating an issue to make sure this gets done in the hangout.
@adcroft @Hallberg-NOAA

**Comment by marshallward** [comment]
This should now be trackable in the `chksum_diag` output, which includes tracer diagnostics.  We can re-open this, or open a new issue, if it doesn't include the info.
