### ISSUE TITLE
Elliptic stream function for GM transport

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#74]
Ferarri et al., 20xx, describe a elliptic solve in the vertical for a bolus smooth stream function.

**Comment by StephenGriffies** [comment]
Would be nice to allow for biharmonic form of this operator, to be more scale selective.

**Comment by StephenGriffies** [comment]
Is this enhancement still desired?  Should it be something for the CPT?  Or is the GM implementation sufficient for the CPT?  If sufficient for the CPT then perhaps we should remove this issue.

**Comment by adcroft** [comment]
As you sya, the original enhancement has been implemented and I'm not aware of any push for the biharmonic option. I'm closing on this basis.
