### ISSUE TITLE
Initialising areaC

### ISSUE THREAD

**Issue by anton-seaice** [NOAA-GFDL/MOM6#740]
Hi 

I was going through the code to intialise the MOM grid, and have a question about the areas used on for the C grid U and v points.

The normal grid areas (for the tracer points and the the b-grid velocity point are [initialised](https://github.com/mom-ocean/MOM6/blob/05d8cc395c1c3c04dd04885bf8dd6df50a86b862/src/initialization/MOM_grid_initialize.F90#L284-L295) from the mom_mosaic grid file:

```
  call MOM_read_data(filename, 'area', tmpT, SGdom, scale=US%m_to_L**2)
  call pass_var(tmpT, SGdom)
  call extrapolate_metric(tmpT, 2*(G%jsc-G%jsd)+2, missing=0.)


  do j=G%jsd,G%jed ; do i=G%isd,G%ied ; i2 = 2*i ; j2 = 2*j
    G%areaT(i,j) = (tmpT(i2-1,j2-1) + tmpT(i2,j2)) + &
                   (tmpT(i2-1,j2) + tmpT(i2,j2-1))
  enddo ; enddo
  do J=G%JsdB,G%JedB ; do I=G%IsdB,G%IedB ; i2 = 2*i ; j2 = 2*j
    G%areaBu(I,J) = (tmpT(i2,j2) + tmpT(i2+1,j2+1)) + &
                    (tmpT(i2,j2+1) + tmpT(i2+1,j2))
  enddo ; enddo
```

This seems as expected - it sums the area of the relevant four cells in the mosaic file.

However the area for the C-grid points are [initialised](https://github.com/mom-ocean/MOM6/blob/05d8cc395c1c3c04dd04885bf8dd6df50a86b862/src/initialization/MOM_grid_initialize.F90#L1251-L1263) assuming each grid cell is square and multiplying the side-lengths:

```
  do j=G%jsd,G%jed ; do I=G%IsdB,G%IedB
    ! This open face length may be revised later.
    G%dy_Cu(I,j) = G%mask2dCu(I,j) * G%dyCu(I,j)
    G%areaCu(I,j) = G%dxCu(I,j) * G%dy_Cu(I,j)
    G%IareaCu(I,j) = G%mask2dCu(I,j) * Adcroft_reciprocal(G%areaCu(I,j))
  enddo ; enddo


  do J=G%JsdB,G%JedB ; do i=G%isd,G%ied
    ! This open face length may be revised later.
    G%dx_Cv(i,J) = G%mask2dCv(i,J) * G%dxCv(i,J)
    G%areaCv(i,J) = G%dyCv(i,J) * G%dx_Cv(i,J)
    G%IareaCv(i,J) = G%mask2dCv(i,J) * Adcroft_reciprocal(G%areaCv(i,J))
  enddo ; enddo
```

Why is areaCu and areaCv not initialised following the same method as areaT and areaBu? The differences will be significant near the poles of the grid ...

Thanks

Anton

**Comment by herrwang0** [comment]
Hi @anton-seaice,

The reason is that grid widths at velocity point  `G%dy_Cu` and `G%dx_Cv` can be later modified by `CHANNEL_CONFIG`. This allows narrow channels to have their actual widths, rather than limited by the model's grid size.

See about how `G%dy_Cu`, `G%dx_Cv` and velocity point areas are modified by the following subroutines, depending on the choices of `CHANNEL_CONFIG`. This is 14 lines after subroutine `initialize_masks` is called.

https://github.com/NOAA-GFDL/MOM6/blob/80d8b5ff0d21dca62477c7004cf7724805ff7d28/src/initialization/MOM_fixed_initialization.F90#L113-L132

**Comment by anton-seaice** [comment]
Thanks for the help!

I'm slightly surprised, but I guess it works, so I will close this.

**Comment by herrwang0** [comment]
No problem. Also note that for global runs, we normally use a tri-polar grid that places singularities (poles) over the land.
