### ISSUE TITLE
Restart issue? Checksum error

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#824]
The issue reported below seems to occur whenever a restart run is performed using a different number of nodes. It can be stepped over (although not resolved) by adding 

`RESTART_CHECKSUMS_REQUIRED = False`

when submitting the job (e.g. in a sbatch file). 

-------------------------------------------------------------------------------------------
Hi,

I wasn't able to resume simulations since a few days ago and the error message I got was
`FATAL from PE     0: MOM_restart(restore_state): Checksum of input field DTBT 159599859F773C38 does not match value  ACACCC2CFBB9E1C stored in RESTART1/MOM.res.nc   `

`forrtl: error (69): process interrupted (SIGINT)`
`Image              PC                Routine            Line        Source`
`MOM6               00000000012E08D5  Unknown               Unknown  Unknown`
`MOM6               00000000012DE4F7  Unknown               Unknown  Unknown`
`MOM6               00000000012877D4  Unknown               Unknown  Unknown`
`MOM6               00000000012875E6  Unknown               Unknown  Unknown`
`MOM6               0000000001210816  Unknown               Unknown  Unknown`
`MOM6               00000000012155FE  Unknown               Unknown  Unknown`
`libpthread.so.0    00007FDE5712A5E0  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE57A15FB2  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE5785BFBC  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE57967E39  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE5796847A  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE5784322B  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE57831245  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE57834B51  Unknown               Unknown  Unknown`
`libmpi.so.12       00007FDE57834382  Unknown               Unknown  Unknown`
`libmpifort.so.12   00007FDE57F66427  Unknown               Unknown  Unknown`
`MOM6               000000000115CEAE  mpp_mod_mp_mpp_ch          21  mpp_sum_mpi.h`
`MOM6               000000000115E8A9  mpp_mod_mp_mpp_ch          16  mpp_chksum.h`
`MOM6               0000000000651528  mom_restart_mp_re        1130  MOM_restart.F90`
`MOM6               000000000060F486  mom_state_initial         491  MOM_state_initialization.F90`
`MOM6               0000000000B8731A  mom_mp_initialize        2144  MOM.F90`
`MOM6               00000000007E4FEC  MAIN__                    309  MOM_driver.F90`
`MOM6               000000000040C31E  Unknown               Unknown  Unknown`
`libc.so.6          00007FDE56A77C05  Unknown               Unknown  Unknown`
`MOM6               000000000040C229  Unknown               Unknown  Unknown`

I noticed that the restart checksum seems to have been discussed yesterday (Mon) during the MOM6 developer's call which I wasn't able to attend (5:00 am local time...) and I'm wondering was it the same issue that was discussed?

Thanks!

**Comment by MJHarrison-GFDL** [comment]
This may be an indication that the restart file is corrupted.  Is the value of DTBT plausible?  The discussion in the dev call involved restarting after changing the PE layout when using mask tables.

**Comment by hlkong** [comment]
@MJHarrison-GFDL  Thanks for your reply!

I think the restart file is not corrupted, and the value of DTBT is reasonable - with DT = 720, DTBT is ~ 14.9. 

I made a few tests and realized I shouldn't have changed the number of cores that were used. Is this the issue you mentioned during the dev call? Is there anything I can do to avoid this issue?

Thanks!

**Comment by adcroft** [comment]
In MOM.res DTBT(Time) is a 1D variable of length 1. This checksum should be independent of the processor-masking decomposition issue we discussed yesterday.

1. Does the model work without a restart file as input? e.g. Do a cold start test (e.g. double_gyre)
2. Does a newly created restart file work as input? e.g. Does double_gyre restart properly?

If the answer to either of the above is no then the file itself is likely not the problem but something else has gone wrong.
If the answers are both yes then there is possibly something wrong with the restart file.

3. Did you change timesteps, topography, or gravity, between segments of the run? This would change the calculated dtbt. Not sure how that fits with the restart checksum problem though.

@hlkong If the code is correct but the file still does not work, you could remove the checksums from the file with `ncatted -a checksum,,d,, -O MOM.res.nc`. I don't recommend this in general since the checksums serve a very good purpose which is to detect data corruption.

**Comment by hlkong** [comment]
@adcroft Thanks Alistair!

The cold test runs fine, and it restarts fine, despite changes in timestep. I didn't test topography or other model parameters but I believe it should work fine, too. Interestingly, when I increased timestep from 5400 to 7200, DTBT remains constant (~149), while it is always -0.95 in MOM_input. Furthermore, when the timestep was set as 120, DTBT still remains ~ 149, which confuses me since it says in the MOM_parameter_doc.all that "The value of DTBT that will actually be used is an integer fraction of DT, rounding down" and clearly 149 is not any integer fraction of 120...

Despite all these, the same checksum error occurred when I changed the number of cores that the model is parallelized on...

**Comment by MJHarrison-GFDL** [comment]
I can reproduce this error @hlkong .  The checksums are computed on the local data by MOM6 , then passed to FMS/mpp for I/O. I don't see where the local checksums are recalculated for the global array if single threaded I/O is enabled. Rather, it appears to be the checksum associated with the PE used for I/O. I'll bring this up on the developer call today.

**Comment by hlkong** [comment]
Thanks @MJHarrison-GFDL ! Sorry that I missed yesterday's call - it was too late when I saw your reply... Did people find a way to resolve the issue?

**Comment by MJHarrison-GFDL** [comment]
We did get to this on the conference calll, but you can set 

RESTART_CHECKSUMS_REQUIRED = False
