### ISSUE TITLE
Potential for use of uninitialized arrays in remap_all_state_vars (MOM_ALE.90)

### ISSUE THREAD

**Issue by raymenzel** [NOAA-GFDL/MOM6#829]
The local arrays:
```
real, dimension(SZI_(G), SZJ_(G), SZK_(GV)) :: work_conc
real, dimension(SZI_(G), SZJ_(G), SZK_(GV)) :: work_cont
```
in
```
subroutine remap_all_state_vars(...)
```
in the file MOM_ALE.F90 may be used before they are initialized if:
- their diagnostic ids (Tr%id_remap_conc, Tr%id_remap_cont) are > 0 
- the point is masked out (G%mask2dT(i,j) .le. 0) or the dt argument is not present.

**Comment by adcroft** [comment]
@raymenzel I assume #831 should have closed this issue?

**Comment by raymenzel** [comment]
Yes I believe so.

**Comment by Hallberg-NOAA** [comment]
This issue has been addressed with PR https://github.com/NOAA-GFDL/MOM6/pull/831 and is therefore being closed.
