### ISSUE TITLE
Update 1D axis data to use COMODO convention

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#848]
The netcdf dimensions in output files have and associated 1d dimensions variable (unnecessarily imposed by CF conventions). We have historically populated these 1D dimension variables with quasi-geographic coordinates which allow lazy plotting but which are misleading except for straight-up geographic coordinate grids.

For a long time we have discussed replacing the quasi-geographic values with the grid-location. Namely, the non-integer i,j-indices of the data in global array space. This has many downstream functionalities:
- A variable's staggered location can be inferred by the values of the axis data. If T is at i=0.5,1.5,2.5,... and U is at i=1.0,2.0,3.0,... we can infer the U data is staggered and to the right of T.
- The symmetric or non-symmetric nature of data is trivial to indicate. A symmetric output mode would have U at i=0.0,1.0,2.0,3.0,...

The above is very close to the COMODO [convention](http://pycomodo.forge.imag.fr/norm.html#coordinate-variables) except:
- Their indexing includes the halo regions. Since we want our output to be independent of halo size (we do not even write out the halo) then this is not possible. Luckily, it seems a halo size of 0 works in their convention.
- COMODO uses attributes to indicate the shifts and non-halo regions of data. This is unnecessary if the domain is 0:ni,0:nj and we use half integer values as above.

The COMODO convention is understood by some packages assocated with Pangeo, e.g. [xgcm](https://xgcm.readthedocs.io/en/latest/api.html). Adopting the half-index values for the 1D axis data will avoid bad plotting and get us a little way towards compatibility with the community efforts represented by pangeo. See pangeo-data/pangeo-example-notebooks#11

**Comment by MJHarrison-GFDL** [comment]
closed by #1179
