### ISSUE TITLE
Unable to print out CPU_stats

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#853]
I got this issue when running [my configuration](https://github.com/hlkong/MOM6/tree/shoebox_std) under 0.1 deg resolution: I would only be able to get the first few lines written into CPU_stats. For example,

> Startup CPU time:     1928.374 sec summed across  168 PEs.
>        Day, Step number,     CPU time, CPU time change
>  256042.000,           0,     1928.374,     1928.374

and I wouldn't get any more lines. I checked MOM_PARAMETER_DOC.all but everything seems fine: 

> WRITE_CPU_STEPS = 1000
> MAXCPU = -1.0
> CPU_TIME_FILE = "CPU_stats"

This has only occurred at high resolution runs. At 1 deg it never happened. 

Does anyone happen to know what may be the issue?

Thanks!!

**Comment by Hallberg-NOAA** [comment]
@hlkong, it sounds to me like your symptoms are most consistent with either a run that is either finishing (or crashing or timing out) without flushing all of its I/O buffers, or your  frequency with which you are writing the CPU stats is inconsistent with the length of your run.

  Try making WRITE_CPU_STEPS much shorter (like 2) to see whether you start to see more entries written to the CPU_stats file. Also check whether the other text output files (like the ocean.stats files) are being written, and how long your simulation is actually going based on the output to std_out.

  It is also possible that we may need to add an explicit call to flush the buffer to the CPU time I/O file at line 176 of MOM_write_cputime.F90 (although doing so could slow the model down), or that we should add a new MOM_write_cputime_end routine to flush and close the I/O unit number.

  Please advise us, @hlkong, if the above steps give you a better idea of what might be going on.

**Comment by ashao** [comment]
It sounds like a buffer issue to me, have you tried adding 
```
FLUSH(CS%fileCPU_ascii)
```
after https://github.com/NOAA-GFDL/MOM6/blob/e23fac15852ee3a90f4adbf8c910d39482d41f23/src/framework/MOM_write_cputime.F90#L176?

Out of curiosity too, how many processors are you using and does the problem go away if you decrease the number of processors for the same test case?

**Comment by hlkong** [comment]
@ashao Thanks for the advice! I haven't tried with the command but a test case seemed to be fine when I used less number of nodes. But I'm not sure if this is the reason because the test case also had less online diagnosis to perform. Unfortunately I can't test the full case until Sep 30th because I have run out of computational resource... Will keep you updated though!

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by PR#1189, and can now be closed. Please reopen a new issue if similar issues reappear.
