### ISSUE TITLE
Dimensional inconsistency in biharm Smagorinsky viscosity

### ISSUE THREAD

**Issue by gustavo-marques** [NOAA-GFDL/MOM6#870]
@septicscuzzy and I have found a possible dimensional inconsistency in regular biharmonic Smag vs. (bound Coriolis) Smag.  Regular biharm Smag should have units of m^4/s, but it looks like (bound Coriolis) Smag has units of m^6/s^2, see [here](https://github.com/NOAA-GFDL/MOM6/blob/ef9ecf2572b2a792395bf87eb43d5bea772d8f7f/src/parameterizations/lateral/MOM_hor_visc.F90#L1453).  These are being added together [here](https://github.com/NOAA-GFDL/MOM6/blob/ef9ecf2572b2a792395bf87eb43d5bea772d8f7f/src/parameterizations/lateral/MOM_hor_visc.F90#L627).

**Comment by Hallberg-NOAA** [comment]
Thank you, @gustavo-marques and @septicscuzzy, for your close scrutiny of the MOM6 code, but I do not believe that this expression is dimensionally inconsistent.

  The bound Coriolis case has dimensional coefficient out front (with units of s/m^2) that is the magnitude of the Coriolis parameter divided by the square of the grid-scale velocities for which the Coriolis accelerations are dominated by the lateral biharmonic viscosity terms.  This "bound Coriolis" contribution to the biharmonic coefficient scales with the square of the grid-scale shears, whereas the usual Smagorinsky coefficient scales with the magnitidude of the grid-scale shears to the first power.  All of the contributions to biharmonic viscosity have units of m4 s-1, as they should.

  This conversation is a good argument for extending the dimensional consistency testing to included lateral distances and time.

  @gustavo-marques and @septicscuzzy, if you are convinced that I am correct, please close this issue.

**Comment by gustavo-marques** [comment]
@Hallberg-NOAA, thanks for the clarification.
