### ISSUE TITLE
Re-factor initialize-from-z to work on individual tracers

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#88]
The initialize-from-z code works in two modes, one assuming the isopycnal layer coordinate and the second assume T and S are the only inputs.

The second mode needs to be re-factored so we can call it for individual tracers and thus provide an initialize-from-z function to COBALT.

**Comment by MJHarrison-GFDL** [comment]
...working on finalizing a new interface for generic tracers.  

current version based on discussions with @nikizadehgfdl  and Jasmin John:

MOM_initialize_tracer_from_z(h,tr,G,PF,src_file,src_var,*unit_conversion,*recnum, *homogenize,*useALE,*remappingScheme,*src_gridspec)

*==optional 

Defaults are based on USE_REGRIDDING and REMAPPING_SCHEME parameters.

**Comment by nikizadehgfdl** [comment]
@MJHarrison-GFDL  , do you mean  to create a new routine to generalize MOM_temp_salt_initialize_from_Z()  to step through all the known tracers (COBALT tracers, ...) and initialize the ones that are requested to be initialized by the generic_tracer package?
So the call sequence in MOM_initialize.F90 would be something like:
```
    if (from_Z_file) then
!     Initialize thickness and T/S from z-coordinate data in a file.
      if (.NOT.use_temperature) call MOM_error￼(FATAL,"MOM_initialize : "//&
         "use_temperature must be true if INIT_LAYERS_FROM_Z_FILE is true")

      call MOM_temp_salt_initialize_from_Z￼(h, tv, G, PF, dirs)

>     call  MOM_initialize_tracer_from_z(h,tr,G, ...)   !Loops through tracers in tr and asks generics which should be initialized and mimic the above temp_salt call for them 
 
      call pass_var￼(h, G%Domain)
    else
```

**Comment by nikizadehgfdl** [comment]
MOM6 does not know about the generic tracers until after the call to tracer_flow_control_init() in MOM.F90
So a call  like MOM_initialize_tracer_from_z above must appear after  the call to tracer_flow_control_init() in MOM.F90
and cannot happen along with T&S.

So why not enhance the existing function tracer_Z_init() that is currently being called to regrid properly ? What does this function do? Doesn't it regrid already? I am getting confused !

**Comment by adcroft** [comment]
Status on this issue?

**Comment by Hallberg-NOAA** [comment]
This capability has existed via calls to MOM_initialize_tracer_form_Z for 5 years now (since September 1, 2015). This issue can be closed. If there are specific issues that remain, please open a new issue ticket describing them.
