### ISSUE TITLE
spurious energy after changing the number of nodes

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#888]
This occurs whenever I change the number of nodes to **RESTART** a run: the total energy (En) recorded in OUTPUT/ocean.stats will always experience a sudden jump, when thousands of truncations occur, at this first timestep (or within the first model year after restart?), but resumed in later steps (years). Correspondingly, the flow pattern will be shifted significantly, e.g. AMOC strength will shift up or down. 

I have turned RESTART_CHECKSUMS_REQUIRED = False to allow the model to restart with different number of nodes - not sure if this is where the issue comes from...

**Comment by awallcraft** [comment]
Are you converting the restart to serial?  For SIS2 I use:

mppnccombine -64 ice_model.res.nc ice_model.res.nc.????

Alan.

**Comment by hlkong** [comment]
Thanks Alan @awallcraft ! No I never used this command. After doing some research I realized this command is necessary only when multiple restart files are written out which is not my case... In my case, only one MOM.res.nc file has been created in RESTART folder.

**Comment by MJHarrison-GFDL** [comment]
Can you point to your test case?

**Comment by hlkong** [comment]
[This branch](https://github.com/hlkong/MOM6/tree/spuriousE_test) contains the 

> MOM_input
> MOM_override

files for testing. I've also included a file called 

>run

 which is just an encapsulation of the commands I used to start the run. Perhaps the only thing worth pointing out is the specification of stack size in that file: I have to use 

`ulimit -s 30000`

in order not to have the model blow up - because running such a high resolution configuration (600 grid points in lon, 550 grid points in lat, 30 layers) on 112 CPUs requires larger stack size than default. 

I didn't upload the restart file since it's too large (895mb) but one can test the issue I mentioned by, e.g. running the configuration with 224 CPUs (that's 8 nodes on the machine I used) for a very short time, creating a restart file, changing the CPU number to 112 (4 nodes), and restarting thereafter. 

The spurious energy may not always be the case; in fact, in some other runs where the number of CPUs also changed, it did not happen...

**Comment by Hallberg-NOAA** [comment]
Combining domain-decomposed restart files using a tool like mppnccombine is necessary when the layout changes to one that is incompatible with the previous layout and I/O layout.  In some cases with an I/O layout, it may be possible to reuse domain-decomposed restart files from a different layout, provided that the processor boundaries that the I/O layout inherits happen to coincide, but this is not something that can be relied upon. However, it is always possible to use the properly combined restart file, even if the restart files are being written out in parallel by setting `PARALLEL_RESTARTFILES  = True` at runtime

  The fact that you are encountering these apparent restart errors even with `PARALLEL_RESTARTFILES = False` strongly suggests that something else entirely is going on. My guess is that there is something about how the topography is being set up in these cases that does not reproduce across PEs. If you use the same thicknesses via the restart files, but there are large changes in the bottom depth, that would be reflected in the free surface, which in turn could create huge tsunamis. My recommendation to figure out what is going on here is to use a very short baroclinic timestep after your restart (adequate to resolve the O(200 m/s) external gravity waves associated with the tsunamis), and save the diagnostics of the free surface height and velocities frequently after the restart. With short enough timesteps, the model should survive this shock, and you should have more than enough information from animating these fields to figure out what is going on.  Assuming that this will be traced back to the way the topography or one of the other static (or restart-independent) fields is being initialized, the fact that this case is using mostly non-standard user code for initialization will lead us to conclude that there are no changes needed to the standard MOM6 code. I am therefore going to close this issue, but if it can be traced back to a recent version of the standard MOM6 code, please reopen this issue. Good luck.
