### ISSUE TITLE
Possible issue in the North pole when using a tripolar grid

### ISSUE THREAD

**Issue by gustavo-marques** [NOAA-GFDL/MOM6#902]
As discussed during the last MOM6 dev meeting, we see noise radiating from the North pole in NCAR's configuration (2/3 degree tripolar grid) run in ocean-only mode. The problem also occurs in ice-ocean and fully-coupled simulations. As an example, below is a snapshot of SSV after 12 hours of simulation. 

![image](https://user-images.githubusercontent.com/11339137/54213024-59e74000-44a9-11e9-8e7e-47071372161a.png)
 
Buoyancy and wind forcing have been turned off in the simulation shown above and the model was built using the latest dev/master, compiled in ocean-only mode. Therefore, I have ruled-out the forcing as the culprit. I've also checked that the issue occurs in both symmetric and non-symmetric modes. 

This issue also seems to be present in GFDL's ocean_only/global_ALE/z experiment, as shown below (no forcing applied).

![image](https://user-images.githubusercontent.com/11339137/54216773-e5fc6600-44af-11e9-82c4-88d482a6fe02.png)

In the cases shown above the following flags have been set, but the issue occurs regardless of their value:

```
USE_TRIPOLAR_GEOLONB_BUG = False
GRID_ROTATION_ANGLE_BUGS = False
```

###  Debugging exercise

I've used a debugger to check halo points near the North pole in the ocean_only/global_ALE/z experiment. Below is a table showing geolonCu values in the two processors (A and B) that contain points near the North pole. Column 94 is highlighted in both processors. Row 31 is the last physical point and 4 halo points have been filled (as expected).

![image](https://user-images.githubusercontent.com/11339137/54217095-9a968780-44b0-11e9-99a1-2362c0eb997d.png)

Similarly, the table below shows values for the eastward velocity component (u) near the North pole. Halo points are being updated properly between processors A and B but unlike geolonCu, only 3 halo points are being filled. 

![image](https://user-images.githubusercontent.com/11339137/54218977-2cec5a80-44b4-11e9-8e4d-300c4e7f7a7a.png)

Again, this happens in both symmetric and non-symmetric modes. The northward velocity (v) also has only 3 halos being updated. We don't think that this is the reason we get noise near the North pole since the entire row is not being filled with 4 halos. However, not having 4 halos might be a problem with certain options (although we could not think of any). We tried 1) turning off BIHARMONIC and 2) using 5 halos, but the issue persisted.  

**Any suggestions? Can this be an issue?**

**Comment by StephenGriffies** [comment]
This smells like a similar issue encountered with the Aussies working with MOM5 and CICE.  Here is the Github thread.  Might be worth giving it a read.  

I do not recall whether they resolved the issue, but they did do some digging around.

https://github.com/OceansAus/access-om2/issues/86

**Comment by awallcraft** [comment]
Interpolation from lat-lon input fields might be an issue, but one
debugging option is to compare to a doubled tripole globe.  It has no
seam.  For HYCOM I also used a 6 degree grid for debugging the tripole halo.

[image: depth_2.gif]

[image: depth_1.gif]

Alan.

**Comment by gustavo-marques** [comment]
Thanks, @awallcraft. I've turned off all the forcing and the issue still occurs. Therefore, interpolation from lat-lon input fields is not the cause of the problem.

I am not familiar with a "double tripole grid". Can you please show an example of this grid?

Also, for some reason, the GIF files were not attached to your post.

**Comment by awallcraft** [comment]
The gifs are plots of the grid:

![depth_2](https://user-images.githubusercontent.com/29555153/54302518-71045b80-4597-11e9-890b-dcfb64e3bf92.gif)
![depth_1](https://user-images.githubusercontent.com/29555153/54302519-71045b80-4597-11e9-9a12-d18c268a06cf.gif)

The "issue" with lon-lat interpolation might occur with a doubled tripole grid, which include every standard tripole grid point twice.

**Comment by MJHarrison-GFDL** [comment]
The GOLD configuration is using NE grid staggering for the stresses reported by the coupler.  You turned off the atm-ice stresses, but presumably still have ocn-ice stresses being applied.  Can you verify if u* as calculated by MOM6 is non-zero and if so, then are there discontinuities across the fold in this field?

**Comment by gustavo-marques** [comment]
Thanks, @MJHarrison-GFDL. u* is zero in my tests. I am using the ocean_only executable with the following options:

#override VARIABLE_WINDS = False
#override VARIABLE_BUOYFORCE =  False
#override BUOY_CONFIG = "zero"
#override WIND_CONFIG = "zero"
#override RESTOREBUOY = False
#override GUST_CONST = 0.0
#override READ_GUST_2D = False
#override TIDES = False
#override DO_GEOTHERMAL = False

**Comment by gustavo-marques** [comment]
I just confirmed that the noise radiating from the North pole in both NCAR and GFDL simulations is a consequence of the initial conditions (we all use WOA05). This dataset has some interpolation issues in the Arctic. I am not sure if WOA13 is any better. I will look into it next week. If anybody has a better suggestion, please let us know.

**Comment by gustavo-marques** [comment]
I've set DEBUG_REDUNDANT = True, following @Hallberg-NOAA suggestion, and the mode run just fine without reporting any issue.
