### ISSUE TITLE
spurious use of flux_units for transport diagnostics  

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#934]
**Summary**

MOM6/src/tracer/MOM_tracer_registry.F90 sets up advective and diffusive diagnostics to compute heat, salt, and tracer transports in the x,y directions.  We use these diagnostics for poleward heat and salt traansports. The registered units are W/m2 for heat and kg/(m2 sec) for salt. However, these units are wrong. They should be W for heat and kg/sec for salt.  That is, we are diagnosing **transports** rather than **fluxes**.  So the diagnostics should be registered with transport units rather than flux units.  

I ask that others please confirm this situation.  If indeed wrong, the code changes to the registered units can/could impact those who have already setup analysis scripts.  I particularly wish to ask @Hallberg-NOAA to check, as I believe some of this code originates from him, though it likely was right at some point in the past.  Others please take a look as well, particular @gustavo-marques as I presume you have diagnostics for poleward heat transports.  

**Details**

The diagnostics are registered in MOM6/src/tracer/MOM_tracer_registry.F90 and include the following ids

advection: id_adx, id_ady, id_adx_2d, id_ady_2d
diffusion: id_diffx, id_diffy, id_diffx_2d, id_diffy_2d

**Comments**

There could be other places where we register flux units but in fact diagnose a transport.  Please keep this possible error in mind as you look through the code.  Transports add (they are extensive) whereas fluxes do not add (they are intensive).

**Comment by gustavo-marques** [comment]
Thanks for letting us know.

**Comment by ashao** [comment]
@StephenGriffies is correct about the units. Here's the salient part of the code that actually calculates those diagnostics for the meridional component.

https://github.com/NOAA-GFDL/MOM6/blob/7cfb69b73a6dd316114ca01e8c22fba258645c61/src/tracer/MOM_tracer_advect.F90#L968-L988

Once we come to agreement on this, changing the units is pretty straightforward:
https://github.com/NOAA-GFDL/MOM6/blob/7cfb69b73a6dd316114ca01e8c22fba258645c61/src/core/MOM.F90#L2011-L2029

I also double-checked that the remapping was being done correctly and have verified that `v_extensive=.true.` for both the advective and diffusive components.

**Comment by StephenGriffies** [comment]
One approach is to add "transport_units" to the tracer type, in line with the present "flux_units".  For temperature, transport_units = W whereas flux_units stays at its current W m-2.  

Thoughts?

**Comment by StephenGriffies** [comment]
@Hallberg-NOAA and I just met.  He convinced me that it is only heat that is wrong, with salt transport units in fact set to "psu m3 s-1".  Although awkward, since psu is not a mass unit, it still gets things ok.  Whereas the "W m-2" for heat is a hard-coded mistake on line 2021 of MOM.F90.  Fixing that three characters is all that is needed to make the heat transport diagnostics correct.

**Comment by StephenGriffies** [comment]
We need to modify the following python script when making the MOM6 code change 

see line 80 of MOM6-examples/tools/analysis/poleward_heat_transport.py 

which checks for units of W m-2 rather than W.  I suggest we keep the W m-2 check to allow for backward compatibility, but also add a check for units of W to allow for use with the updated MOM6 code.
