### ISSUE TITLE
Ice shelf module is not working in ALE mode

### ISSUE THREAD

**Issue by gustavo-marques** [NOAA-GFDL/MOM6#938]
The following breaks the ice shelf module in ALE mode.

https://github.com/NOAA-GFDL/MOM6/blob/bf81b4af4e3ce49bc8937db1db8675820750db96/src/core/MOM.F90#L2800-L2801

In this case `state%Hml(i,j)` is always zero, so the following can never be true.

https://github.com/NOAA-GFDL/MOM6/blob/bf81b4af4e3ce49bc8937db1db8675820750db96/src/ice_shelf/MOM_ice_shelf.F90#L352-L354

Uncommenting the line above fixes the issue. Another option is to delete `(state%Hml(i,j) > 0.0)` in `shelf_calc_flux`.

**Comment by Hallberg-NOAA** [comment]
This portion of the MOM_ice_shelf.F90 code was changed as suggested with commit e88732c, which was committed as a part of PR #1083.
