### ISSUE TITLE
Problems reading split restart files. 

### ISSUE THREAD

**Issue by jbusecke** [NOAA-GFDL/MOM6#958]
I am running MOM6/SIS2 + COBALT on the NASA discovery cluster and have the parameters matched to `OM4p125_IAF_csf_JRA55do1-3_r5`. 

I am using input namelists, and *_parameter_doc.all files in `/lustre/f2/scratch/gfdl/oar.gfdl.ogrp-account/work/CMIP6/OMIP/xanadu_mom6_20181101/OM4p125_IAF_csf_JRA55do1-3_r5_cycle4.o348634/output.stager/lustre/f2/scratch/oar.gfdl.ogrp-account/CMIP6/OMIP/xanadu_mom6_20181101/OM4p125_IAF_csf_JRA55do1-3_r5_cycle4/ncrc4.intel16f2-prod/archive` as reference.

I am trying to use the restart files from that run to start our spin-up of the biogeochemistry, but the restart files my configuration produces are formatted differently than the restart files provided:

My configuration produces something like this:
```
MOM.res_1.nc
MOM.res_2.nc
....
```

but the restart files I am trying to use from above are additionally split in space it seems:
```
MOM.res_1.nc.0000
MOM.res_1.nc.0001
....
MOM.res_2.nc.0000
MOM.res_2.nc.0001
...
```

Is this a configurable option that I haven't set or should I merge these files manually before linking them to my `INPUT` folder? 

Many thanks for any advice.

**Comment by MJHarrison-GFDL** [comment]
The restart files from the previous run were produced with the flag "PARALLEL_RESTARTFILES = True"

Your newer configuration has this set to False. In order to use the previous files, you have two options, either toggle to True but you will be restricted to running with the same number of cores, or manually combine.  The "mppnccombine" tool in FRE-nctools will do the combining for you.

**Comment by jbusecke** [comment]
Fantastic! Thanks.

**Comment by jbusecke** [comment]
Do you recommend to turn that option off for my full run? Will this have performance penalties?
Or can I combine the files and still turn on the option, so that split restart files are created after running the first year (in case that is much faster)?

**Comment by MJHarrison-GFDL** [comment]
Recommendation is to toggle off. This gives you more flexibility if you want to change the core count or use for different experiments. The cost is minimal since typically only writing once per job at the end of the run.

**Comment by jbusecke** [comment]
When using `mppnccombine` I am getting rather broad error messages:
```
Error: cannot write variable "Layer"'s values!
Error: cannot write variable "0"'s values!
Warning: output file may be incomplete!
```
Is there a compiled version on analysis somewhere that I could use to test this again? Cheers

**Comment by MJHarrison-GFDL** [comment]
on the GFDL analysis cluster, 

module load fre/bronx-15

**Comment by jbusecke** [comment]
Thanks everyone. I was able to achieve this using only xarray and my setup is running. If there is interest in the method I could contribute an example notebook. Will close this for now.
