### ISSUE TITLE
Bad logic in diabatic_diff_salt_tend diagnostic

### ISSUE THREAD

**Issue by gmacgilchrist** [NOAA-GFDL/MOM6#968]
In MOM_diabatic_driver.F90, in the subroutine `diagnose_diabatic_diff_tendency`, calculation of the _salt_ tendency has a dependency on whether or not the _salinity_ tendency calculation is also called - through it's dependence on the variable `work_3d`. If the salt tendency diagnostic is switched on while salinity is not, the salt tendency is evaluated from the previous specification of `work_3d`, which is in the calculation of the temperature or heat tendencies, leading to large errors. 

https://github.com/NOAA-GFDL/MOM6/blob/0c1a1e8595b59075e415a6f6a52c2c803e7f1a10/src/parameterizations/vertical/MOM_diabatic_driver.F90#L2965-L2977

**Comment by marshallward** [comment]
Probably easiest to move the whole block in a single conditional (if A .or. B .or. C), then conditionally write the output.  I can do this unless someone else has a better suggestion.

**Comment by marshallward** [comment]
Fix submitted here: https://github.com/NOAA-GFDL/MOM6/pull/969

**Comment by marshallward** [comment]
Fix has been merged, hopefully fixed.  Closing this issue.

**Comment by marshallward** [comment]
ok closing for real this time.
