### ISSUE TITLE
dev/gfdl does not compile with -openmp 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#973]
There are many files that need to be touched (!$OMP variable definitions) to fix this. 
But then unfortunately, OMIP models do not reproduce between openmp and non-openmp executables (using 1 thread).  Needs more work to figure out what is changing answers with -openmp. Till then it's probably safer for  the -openmp compile to crash!

**Comment by marshallward** [comment]
We are now doing an openmp build in the test suite.
