### ISSUE TITLE
Dumbbell open boundary test case does not reproduce across restarts

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [NOAA-GFDL/MOM6#975]
@kshedstrom @awallcraft 

Isolated the issue to tracer advection - incoming transports are currently overwritten at the boundaries , i.e.

https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/tracer/MOM_tracer_advect.F90#L587

but outgoing transports are not updated. The tracer reconstructions are using values outside of the domain in either case, so it's not surprising that it is causing a problem.  

I tested by removing the dependency on the sign of the flow  and it reproduces across restarts now.

**Comment by MJHarrison-GFDL** [comment]
if ((uhr(I,j,k) > 0.0) .and. (G%mask2dT(i,j) < 0.5) .or. &
               (uhr(I,j,k) < 0.0) .and. (G%mask2dT(i+1,j) < 0.5)) then

becomes,

            if (G%mask2dT(i,j) < 0.5 .or. G%mask2dT(i+1,j) < 0.5) then

Similarly at

https://github.com/ESMG/MOM6/blob/dev/esmg/src/tracer/MOM_tracer_advect.F90#L926


Also need to merge the following commit on the ESMG fork:

https://github.com/ESMG/MOM6/commit/02248a40e894184fc597e7efc8c72d294dc81563

This appears to fix the restart issue in the dumbbell and NWA test cases, but will change answers. PR will follow via the ESMG/MOM6 fork.

**Comment by kshedstrom** [comment]
Great job, look forward to the PR.

**Comment by MJHarrison-GFDL** [comment]
PR is pending based on @adcroft recommendation to use the tracer reconstructions after substituting external values for outflow

**Comment by MJHarrison-GFDL** [comment]
PR is pending based on @adcroft recommendation to use the tracer reconstructions after substituting external values for outflow

**Comment by MJHarrison-GFDL** [comment]
This remains a live issue.

**Comment by MJHarrison-GFDL** [comment]
The above fix no longer works for my test case, however the restart issue is associated with finite reservoirs.  Setting the tracer reservoir sizes to zero passes restart tests.

**Comment by nikizadehgfdl** [comment]
@MJHarrison-GFDL  , I am looking for the root cause for NWA restart issue. Could it be that the right hand side of the formula [on line 5103 of MOM_open_boundary.F90](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/core/MOM_open_boundary.F90#L5103) should be %t rather than %tres? This seems to fix my restart issue, but I cannot justify it by following the algorithm and I cannot see why the two arrays (%t and %tres) should differ at any time.
```
-          segment%tr_Reg%Tr(m)%tres(I,j,k) = (1.0/fac1)*(segment%tr_Reg%Tr(m)%tres(I,j,k) + &
+          segment%tr_Reg%Tr(m)%tres(I,j,k) = (1.0/fac1)*(segment%tr_Reg%Tr(m)%t(I,j,k) + &
                             (u_L_out*Reg%Tr(m)%t(I+ishift,j,k) - &
                              u_L_in*segment%tr_Reg%Tr(m)%t(I,j,k)))
```

**Comment by kshedstrom** [comment]
Isn't this defeating the purpose of the reservoir and its memory of the flow going by? The state of the reservoir should be saved so that restarts work.

**Comment by nikizadehgfdl** [comment]
I see only OBC%tres_x and OBC%tres_y being restarted. The flow is like:
```
open_boundary_register_restarts() 
                  read OBC%tres_x  from restart
MOM_initialize_state() call fill_temp_salt_segments() 
rotate_OBC_init() call fill_temp_salt_segments() 
                  Tr(m)%t(IsdB)= tv%T(IsdB)
                  Tr(m)%tres=Tr(m)%t 
                  call setup_OBC_tracer_reservoirs() 
                       OBC%tres_x(IsdB)=Tr(m)%t(IsdB)           <------ overwrite    
                       call open_boundary_init() 
                           call pass_vector(OBC%tres_x,OBC%tres_y)

loop:
step_MOM_dynamics 
            call update_OBC_data()
                    call update_OBC_segment_data
                    if(first time call) Tr(m)%tres = Tr(m)%t
            call radiation_open_bdry_conds() 
                  Tr(m)%tres(IsdB) = OBC%tres_x(IsdB)
                  Tr(m)%tres(JsdB) = OBC%tres_y(JsdB)
step_MOM_tracer_dyn call update_segment_tracer_reservoirs() 
                  Tr(m)%tres(IsdB) = (1.0/fac1)*(Tr(m)%tres(IsdB) +u_L_out*Tr(m)%t(IsdB) - u_L_in*Tr(m)%t(IsdB)))
                  OBC%tres_x(IsdB)= Tr(m)%tres(IsdB)
                  OBC%tres_y(JsdB)= Tr(m)%tres(JsdB)

```

**Comment by MJHarrison-GFDL** [comment]
@nikizadehgfdl . Thanks for this. This initialization process is really convoluted by the additional mapping from segments to 3-d restart pointers.  The call to setup_OBC_tracer_reservoirs is over-writing the updated reservoir values as you are pointing out.  This should only be done for a new simulation. 

fill_temp_salt_segments was code which preceded the introduction of the reservoirs. As a start , we should move the call to setup_OBC_tracer_reservoirs from fill_temp_salt_segments, and make the call conditional on new_sim. 

I can run some tests with dumbbell and let you know if that gets us any closer to resolving this issue. Thanks @nikizadehgfdl

**Comment by MJHarrison-GFDL** [comment]
Unfortunately, that suggestion did not work...

**Comment by nikizadehgfdl** [comment]
@MJHarrison-GFDL  I can't fix the issue in NWA test either. No matter how I rearrange the code, the OBC%tres_x and OBC%tres_y do not restart correctly. I do not understand this [business of HI%turns](https://github.com/NOAA-GFDL/MOM6/blob/350809a205bd914e176fd115385c9d409174b97d/src/core/MOM_open_boundary.F90#L5030) where sometimes OBC%tres_x is registered to go into tres_y restart, do you?

**Comment by marshallward** [comment]
@nikizadehgfdl That is for the rotational testing.  For odd numbers of quarter-turns, an x-field is rotated into the y-field position, and is registered as if it were its original x-field variable.

**Comment by nikizadehgfdl** [comment]
@marshallward do you mean HI%turn is 0 , unless we are  running a rotation test?

**Comment by marshallward** [comment]
@nikizadehgfdl Yes, that's right.

**Comment by kshedstrom** [comment]
Has this been fixed yet?

**Comment by nikizadehgfdl** [comment]
How did this get fixed? Is there a PR that fixed it?

**Comment by nikizadehgfdl** [comment]
For my own reference.  Please ignore this update! 

In the recent code base of Andrew Ross, the restart issue of the physical (no COBALT tracers) OBC-NWA model can be resolved with a small fix [here](https://github.com/nikizadehgfdl/MOM6/commit/7274f3051232ddb9624b5b68a06c64305089f537).

There remains a restart issue for the COBALT OBC-NWA when the "in" length scale of the tracer reservoirs are non-zero (i.e., restart issue is bypassed via #override OBC_TRACER_RESERVOIR_LENGTH_SCALE_IN  = 0.0). Which means somehow the array segment%tr_Reg%Tr(m)%t(I,j,k) is not updated or is wrong after a restart. 

Here's a sketch of the new code stack in my branch:

```
open_boundary_register_restarts() 
     allocate and register OBC%tres_x, OBC%tres_y


MOM_initialize_state() 
    call fill_temp_salt_segments()      <---- initialize Tr(1&2)%t and Tr(1&2)%tres 
         Tr(m)%t(IsdB)= tv%T(IsdB)
         Tr(m)%tres=Tr(m)%t 
    call setup_OBC_tracer_reservoirs()
         OBC%tres_x(IsdB)=Tr(m)%t(IsdB) 

    **call restore_state()**                   <---- restart all tracers and  OBC%tres_x, OBC%tres_y

    if (.not. OBC%needs_IO_for_data)   call update_OBC_segment_data         

rotate_OBC_init()      
    call rotate_OBC_segment_data()
    call fill_temp_salt_segments()           <---- re-initialize!
         Tr(m)%t(IsdB)= tv%T(IsdB)
         Tr(m)%tres=Tr(m)%t 
         !!call setup_OBC_tracer_reservoirs()   <--- Not called anymore 
             !!OBC%tres_x(IsdB)=Tr(m)%t(IsdB)           <------ overwrites the restart    
    call open_boundary_init() 
          call pass_vector(OBC%tres_x,OBC%tres_y)

tracer_flow_control_init
   initialize_MOM_generic_tracer
      either Z-initialize call MOM_initialize_tracer_from_Z(tr_ptr)
      or           restart   call MOM_read_data(CS%IC_file, trim(g_tracer_name), tr_ptr, G%Domain)
      call fill_obgc_segments(tr_ptr)
           segment%tr_Reg%Tr(nt)%t = tr_ptr
           segment%tr_Reg%Tr(nt)%tres(:,:,:) = segment%tr_Reg%Tr(nt)%t(:,:,:)

loop:
step_MOM_dynamics() 
            call update_OBC_data()
                    call update_OBC_segment_data
                         if(first time call) Tr(m)%tres = Tr(m)%t
            call radiation_open_bdry_conds() 
                  Tr(m)%tres(IsdB) = OBC%tres_x(IsdB)
                  Tr(m)%tres(JsdB) = OBC%tres_y(JsdB)
step_MOM_tracer_dyn()
           call update_segment_tracer_reservoirs() 
               Tr(m)%tres(IsdB) = (1.0/fac1)*(Tr(m)%tres(IsdB) +u_L_out*Tr(m)%t(IsdB) - u_L_in*Tr(m)%t(IsdB))) !original, not repro
               Tr(m)%tres(IsdB) = (1.0/fac1)*(Tr(m)%tres(IsdB) +u_L_out*Tr(m)%t(IsdB) - u_L_in*Tr(m)%tres(IsdB))) !mod1, repro
               Tr(m)%tres(IsdB) = (1.0/fac1)*(Tr(m)%tres(IsdB) +u_L_out*Tr(m)%t(IsdB) - u_L_in*OBC%tres_x(IsdB))) !mod2, repro
               OBC%tres_x(IsdB)= Tr(m)%tres(IsdB)
               OBC%tres_y(JsdB)= Tr(m)%tres(JsdB)

```
